#!/usr/bin/env wolframscript
(* Independent Wolfram route for the full-dimensional B2 stage-0 contract. *)

ClearAll["Global`*"];
here = DirectoryName[ExpandFileName[$InputFileName]];
root = ExpandFileName[FileNameJoin[{here, "..", ".."}]];
argValue[name_, fallback_] := Module[{p = FirstPosition[$ScriptCommandLine, name]}, If[MissingQ[p], fallback, $ScriptCommandLine[[p[[1]] + 1]]]];
inputPath = ExpandFileName[argValue["--input", FileNameJoin[{here, "u1_body_b2_stage0_inputs.yaml"}]]];
outputPath = ExpandFileName[argValue["--output", FileNameJoin[{here, "mathematica_stage0.yaml"}]]];
assertLogPath = argValue["--assert-log", ""];
fail[tooth_, detail_] := Module[{marker = "ASSERT_FAIL:" <> tooth <> ":" <> detail, stream},
 If[assertLogPath =!= "", If[! DirectoryQ[DirectoryName[ExpandFileName[assertLogPath]]], CreateDirectory[DirectoryName[ExpandFileName[assertLogPath]], CreateIntermediateDirectories -> True]]; stream = OpenAppend[ExpandFileName[assertLogPath]]; WriteString[stream, marker <> "\n"]; Close[stream]];
 Print[marker]; Exit[1]
];
require[test_, tooth_, detail_] := If[! TrueQ[test], fail[tooth, detail]];
sha[path_] := FileHash[path, "SHA256", "HexString"];
digestObject[value_] := Hash[ExportString[value, "RawJSON", "Compact" -> True], "SHA256", "HexString"];

config = Quiet@Check[Import[inputPath, "YAML"], $Failed];
require[AssociationQ[config] && config["schema_version"] === "U1_PHASE_B2_STAGE0_INPUTS_V4" && config["startup_contract_commit"] === "5f73be9f0738030bf73165fda5432644de5f4074", "B2_S0_INPUT", "v48 stage-0 input schema/anchor"];
phasePath = ExpandFileName[argValue["--phase-input", FileNameJoin[{root, config["contracts"]["phase_a_inputs"]}]]];
mechanicsPath = FileNameJoin[{root, config["contracts"]["phase_b1_inputs"]}];
b1Path = FileNameJoin[{root, config["contracts"]["mathematica_b1"]}];
directivePath = FileNameJoin[{root, config["contracts"]["directive"]}];
schemaPath = FileNameJoin[{root, config["contracts"]["v48_obligation_schema"]}];
phase = Import[phasePath, "YAML"]; mechanics = Import[mechanicsPath, "YAML"]; b1 = Import[b1Path, "YAML"]; schema = Import[schemaPath, "YAML"];

Clear[hbar, mGNLS, rhoInf, KEOS, aB, kappaB, muR4, rhoBr, muR, OmegaW, ellg, Mh, cE, mdot, gammaSigma, tangentDtN];
Clear[n, thetaT, v2, nGrad2, chiB, chiGrad2, udCurl2, fThroat, fMix, gEll, uT2, uCurl2, uwT2, uw, hT2, hGrad2];
parseRules = {"m_GNLS" -> "mGNLS", "rho_inf" -> "rhoInf", "K_EOS" -> "KEOS", "theta_t" -> "thetaT", "n_grad2" -> "nGrad2", "chi_grad2" -> "chiGrad2", "ud_curl2" -> "udCurl2", "curl_ud0" -> "curlUd0", "f_throat" -> "fThroat", "f_mix" -> "fMix", "g_ell" -> "gEll", "u_t2" -> "uT2", "u_curl2" -> "uCurl2", "uw_t2" -> "uwT2", "h_t2" -> "hT2", "h_grad2" -> "hGrad2"};
externalCoefficientRules = {"mGNLS" -> "m_GNLS", "rhoInf" -> "rho_inf", "KEOS" -> "K_EOS", "gEll" -> "g_ell", "fThroat" -> "f_throat", "fMix" -> "f_mix", "udCurl2" -> "ud_curl2", "curlUd0" -> "curl_ud0"};
parse[s_] := ToExpression[StringReplace[s, parseRules], InputForm];
canon[e_] := StringReplace[ToString[Factor[FullSimplify[e]], InputForm], externalCoefficientRules];
action = Association@Table[row["id"] -> parse[row["expression"]], {row, phase["action_terms"]}];
expectedAction = Sort[phase["operative_action_decision"]["expected_action_term_ids"]];
require[Sort[Keys[action]] === expectedAction, "B2_S0_ACTION_PARSE", "complete operative native action"];
Scan[Function[row, Module[{source = FileNameJoin[{root, row["source_file"]}]}, require[FileExistsQ[source] && StringContainsQ[Import[source, "Text"], row["source_contains"]], "B2_S0_ACTION_PARSE", "source authentication:" <> row["id"]]]], phase["action_terms"]];

(* Build the field incidence from the parsed scalar invariants.  The Berry
   mixed Hessian joins density and phase; quadratic invariants remain diagonal. *)
(* This route derives incidence by action-root variation targets.  It does not
   share the SymPy primitive-invariant map. *)
variationTargets = <|"bulk_berry" -> {"delta_n", "theta"}, "bulk_flow_kinetic" -> {"theta"}, "quantum_pressure" -> {"delta_n"}, "bulk_EOS" -> {"delta_n"}, "wall_double_well" -> {"delta_chiB"}, "wall_gradient" -> {"delta_chiB"}, "wall_shear_gate" -> {"delta_chiB", "u_d_transverse"}, "throat_source" -> {"native_throat_fields"}, "wall_mix" -> {"native_mixed_fields"}, "brane_shear_kinetic" -> {"u_T"}, "brane_shear_gradient" -> {"u_T"}, "uw_kinetic" -> {"u_w"}, "uw_gap" -> {"u_w"}, "h_kinetic" -> {"h"}, "h_gradient" -> {"h"}|>;
require[Sort[Keys[variationTargets]] === expectedAction, "B2_S0_OPERATOR_INCIDENCE", "independent root-target coverage"];
actionFields = AssociationMap[variationTargets[#] &, Keys[action]];
allFields = Sort[DeleteDuplicates[Flatten[Values[actionFields]]]];
fieldEdges = DeleteDuplicates[Flatten[Map[Function[targets, UndirectedEdge @@@ Subsets[targets, {2}]], Values[actionFields]]]];
fieldGraph = Graph[allFields, fieldEdges];
sectors = Sort[Sort /@ ConnectedComponents[fieldGraph]];
If[MemberQ[phase["field_records"][[All, "id"]], "geon_core_bundle"], AppendTo[sectors, {"geon_core_bundle"}]];
sectorName[fields_] := Module[{sorted = Sort[fields]}, Which[sorted === {"delta_n", "theta"}, "gnls_density_phase", sorted === {"delta_chiB", "u_d_transverse"}, "wall_chi_u_coupled", sorted === {"native_throat_fields"}, "throat_source_open", sorted === {"native_mixed_fields"}, "wall_mix_open", sorted === {"u_T"}, "brane_shear_transverse", sorted === {"u_w"}, "brane_normal_local", sorted === {"h"}, "h_scalar", sorted === {"geon_core_bundle"}, "geon_open", True, "native_block__" <> StringRiffle[sorted, "__"]]];

Clear[omega, k];
berry = D[action["bulk_berry"], thetaT, n];
phaseGrad = FullSimplify[2 D[action["bulk_flow_kinetic"], v2] (hbar/mGNLS)^2 /. n -> rhoInf];
densityGrad = FullSimplify[2 D[action["quantum_pressure"], nGrad2] /. n -> rhoInf];
densityCurve = FullSimplify[D[action["bulk_EOS"], {n, 2}] /. n -> rhoInf];
require[FullSimplify[berry + hbar] === 0 && FullSimplify[phaseGrad - hbar^2 rhoInf/mGNLS] === 0 && FullSimplify[densityGrad - hbar^2/(4 mGNLS rhoInf)] === 0 && FullSimplify[densityCurve - 5 KEOS rhoInf^3] === 0, "B2_S0_ACTION_HESSIAN", "GNLS Hessian coefficients"];
acousticMatrix = {{-I omega, -phaseGrad k^2/hbar}, {densityCurve + densityGrad k^2, -I hbar omega}};
acoustic = Factor[Det[acousticMatrix]/hbar];
require[FullSimplify[acoustic - (-omega^2 + 5 KEOS rhoInf^4 k^2/mGNLS + hbar^2 k^4/(4 mGNLS^2))] === 0, "B2_S0_ACTION_HESSIAN", "GNLS determinant"];
wallCurve = FullSimplify[D[action["wall_double_well"], {chiB, 2}] /. chiB -> 0]; wallGrad = 2 D[action["wall_gradient"], chiGrad2];
gatedGrad = 2 D[action["wall_shear_gate"], udCurl2]; shearTime = 2 D[action["brane_shear_kinetic"], uT2]; shearGrad = 2 D[action["brane_shear_gradient"], uCurl2];
uwTime = 2 D[action["uw_kinetic"], uwT2]; uwCurve = D[action["uw_gap"], {uw, 2}]; hTime = 2 D[action["h_kinetic"], hT2]; hGradient = 2 D[action["h_gradient"], hGrad2];
Clear[w, ellPositive]; supportIntegral = Assuming[ellPositive > 0, FullSimplify[Integrate[Exp[-(w/ellPositive)^2]/(Sqrt[Pi] ellPositive), {w, -Infinity, Infinity}]]];
require[supportIntegral === 1, "B2_S0_BRANE_NORMALIZATION", "g_ell normalization"];

(* Independent coefficient extraction of the full frozen-base bilinear form. *)
Clear[epsL, epsR];
affineJet[name_] := Symbol[name <> "0"] + epsL Symbol["dL" <> name] + epsR Symbol["dR" <> name];
squaredJet[prefix_, components_] := Total[(affineJet[prefix <> #]^2 &) /@ components];
curlComponents4 = {"xy", "xz", "xw", "yz", "yw", "zw"};
hessianSubstitutions = {n -> affineJet["n"], thetaT -> affineJet["thetaT"], v2 -> squaredJet["v", {"x", "y", "z", "w"}], nGrad2 -> squaredJet["gradN", {"x", "y", "z", "w"}], chiB -> affineJet["chi"], chiGrad2 -> squaredJet["gradChi", {"x", "y", "z", "w"}], udCurl2 -> squaredJet["curlUd", curlComponents4], uT2 -> squaredJet["uT", {"x", "y", "z"}], uCurl2 -> squaredJet["curlU", {"x", "y", "z"}], uwT2 -> affineJet["uwT"]^2, uw -> affineJet["uw"], hT2 -> affineJet["hT"]^2, hGrad2 -> squaredJet["gradH", {"x", "y", "z", "w"}]};
secondVariationRows = Table[If[MemberQ[{"throat_source", "wall_mix"}, actionRoot], <|"id" -> actionRoot, "status" -> "UNRESOLVED(" <> actionRoot <> "_native_functional_second_variation)", "bilinear_second_variation" -> "UNRESOLVED(" <> actionRoot <> "_native_functional_second_variation)", "base_jet_coefficients" -> {}|>, bilinear = FullSimplify[D[action[actionRoot] /. hessianSubstitutions, epsL, epsR] /. {epsL -> 0, epsR -> 0}]; <|"id" -> actionRoot, "status" -> "DERIVED_COMPLETE_BILINEAR_SECOND_VARIATION", "bilinear_second_variation" -> canon[bilinear], "base_jet_coefficients" -> Sort[DeleteDuplicates[ToString[#, InputForm] & /@ Cases[bilinear, symbol_Symbol /; StringEndsQ[ToString[symbol, InputForm], "0"], Infinity]]]|>], {actionRoot, Sort[Keys[action]]}];
wallGateBilinear = Lookup[Association@Table[row["id"] -> row["bilinear_second_variation"], {row, secondVariationRows}], "wall_shear_gate"];
wallGateExpected = muR4 (Symbol["dLchi"] Total@Table[Symbol["curlUd" <> component <> "0"] Symbol["dRcurlUd" <> component], {component, curlComponents4}] + Symbol["dRchi"] Total@Table[Symbol["curlUd" <> component <> "0"] Symbol["dLcurlUd" <> component], {component, curlComponents4}] + Symbol["chi0"] Total@Table[Symbol["dLcurlUd" <> component] Symbol["dRcurlUd" <> component], {component, curlComponents4}]);
require[FullSimplify[ToExpression[wallGateBilinear, InputForm] - wallGateExpected] === 0, "B2_S0_ACTION_HESSIAN", "wall gate complete chi-u Hessian"];
completeSecondVariation = <|"status" -> "DERIVED_COMPLETE_TERMWISE_SECOND_VARIATION_WITH_NAMED_BASE_JET", "base_state_class" -> phase["kinematics"]["base_state_class"], "base_jet_rule" -> "all symbols ending in 0 are the frozen co-moving-steady base jet and are held fixed under epsilon_left/right differentiation", "authenticated_background_substitutions" -> <|"ambient_density_only" -> "n_ambient=rho_inf", "ambient_medium_velocity_only" -> phase["ambient"]["medium_rest_velocity"], "chi0" -> "NOT_AUTHENTICATED_ZERO", "curl_ud0" -> "NOT_AUTHENTICATED_ZERO"|>, "wall_gate_block_status" -> "DERIVED_SYMBOLIC_FROZEN_BASE_JET_NO_COUPLING_SUPPRESSED", "termwise_records" -> secondVariationRows|>;

makeOperator[fields_] := Module[{id = sectorName[fields], ancestry, base, expr, reason, zero},
 ancestry = If[id === "geon_open", {"geon_core_bundle"}, Sort[Select[Keys[actionFields], Intersection[actionFields[#], fields] =!= {} &]]];
 base = <|"id" -> id, "field_block" -> fields, "action_ancestry" -> ancestry, "inventory_generation" -> "Wolfram Graph ConnectedComponents of native second-variation field incidence", "hessian_block_count" -> Length[ancestry]|>;
 Which[
  id === "gnls_density_phase", Join[base, <|"family" -> "u_L", "operator_fourier" -> canon[acoustic], "matrix_operator_fourier" -> Map[canon, acousticMatrix, {2}], "support_dimension" -> 4, "spatial_order" -> 4, "time_order" -> 2, "status" -> "DERIVED", "radial_kind" -> "coupled_fourth_order"|>],
  id === "wall_chi_u_coupled", hChiChi = wallGrad k^2 + wallCurve; hChiU = muR4 k curlUd0; hUU = muR4 chi0 k^2; coupledMatrix = {{hChiChi, hChiU}, {hChiU, hUU}}; Join[base, <|"family" -> "wall_chi/u_d", "operator_fourier" -> canon[Det[coupledMatrix]], "matrix_operator_fourier" -> <|"H_chi_chi" -> canon[hChiChi], "H_chi_u_reduced_polarization" -> canon[hChiU], "H_u_chi_reduced_polarization" -> canon[hChiU], "H_u_u_reduced_polarization" -> canon[hUU], "full_tensor_identity" -> "H_chi,u[delta_chi,delta_u]=muR4*delta_chi*<curl(u0),curl(delta_u)>; H_u,u=muR4*chi0*<curl(delta_u_L),curl(delta_u_R)>; H_chi,chi(gate)=0"|>, "frozen_symbolic_base_coefficients" -> {"chi0", "curl_ud0"}, "support_dimension" -> 4, "spatial_order" -> 2, "time_order" -> 0, "status" -> "DERIVED_SYMBOLIC_FROZEN_BASE", "radial_kind" -> "coupled_scalar_two_form_second_order"|>],
  id === "brane_shear_transverse", expr = shearGrad k^2 - shearTime omega^2; Join[base, <|"family" -> "u_T", "operator_fourier" -> canon[expr], "reduced_operator_after_support_integration" -> canon[expr /. gEll -> 1], "support_dimension" -> 3, "spatial_order" -> 2, "time_order" -> 2, "status" -> "DERIVED", "radial_kind" -> "scalar_second_order", "support_normalization" -> <|"computed_integral" -> canon[supportIntegral], "residual" -> canon[supportIntegral - 1]|>|>],
  id === "brane_normal_local", expr = uwCurve - uwTime omega^2; Join[base, <|"family" -> "wall_chi", "operator_fourier" -> canon[expr], "reduced_operator_after_support_integration" -> canon[expr /. gEll -> 1], "support_dimension" -> 3, "spatial_order" -> 0, "time_order" -> 2, "status" -> "DERIVED", "radial_kind" -> "algebraic_contact", "support_normalization" -> <|"computed_integral" -> canon[supportIntegral], "residual" -> canon[supportIntegral - 1]|>|>],
  id === "h_scalar", Join[base, <|"family" -> "h", "operator_fourier" -> canon[hGradient k^2 - hTime omega^2], "support_dimension" -> 4, "spatial_order" -> 2, "time_order" -> 2, "status" -> "DERIVED_OPEN_COEFFICIENTS", "radial_kind" -> "scalar_second_order"|>],
  id === "geon_open", Join[base, <|"family" -> "geon", "operator_fourier" -> "UNRESOLVED(geon_core_bundle)", "support_dimension" -> 4, "spatial_order" -> Null, "time_order" -> Null, "status" -> "UNRESOLVED(geon_core_bundle)", "radial_kind" -> Null|>],
  True, reason = If[id === "throat_source_open", "throat_source", "wall_mix"]; zero = TrueQ[FullSimplify[action[reason]] === 0]; Join[base, <|"family" -> "wall_chi", "operator_fourier" -> If[zero, "0", "UNRESOLVED(" <> reason <> "_second_variation)"], "support_dimension" -> 3, "spatial_order" -> Null, "time_order" -> Null, "status" -> If[zero, "COMPUTED_ZERO(source_ablation)", "UNRESOLVED(" <> reason <> ")"], "radial_kind" -> Null|>]
 ]
];
operators = SortBy[makeOperator /@ sectors, #["id"] &]; operatorIndex = Association@Table[row["id"] -> row, {row, operators}];
incidence = Table[targets = Sort[Select[operators[[All, "id"]], MemberQ[operatorIndex[#]["action_ancestry"], root] &]]; require[Length[targets] > 0, "B2_S0_OPERATOR_INCIDENCE", root]; <|"action_root" -> root, "operator_ids" -> targets, "incidence_count" -> Length[targets], "disposition" -> "computed_from_generated_second_variation_incidence"|>, {root, Sort[Keys[action]]}];

(* Full-dimensional canonical Noether tensor on an algebraic jet bundle. *)
labels[d_] := Take[{"t", "x", "y", "z", "w"}, d + 1]; clean[s_] := StringReplace[s, "_" -> "Q"];
q[field_] := Symbol[clean[field]]; jet[field_, mu_] := Symbol[clean[field] <> ToUpperCase[mu]];
jet2[field_, mu_, nu_] := Module[{order = labels[4], pair}, pair = SortBy[{mu, nu}, FirstPosition[order, #][[1]] &]; Symbol[clean[field] <> ToUpperCase[StringJoin[pair]]]];
jetExternalRules[fields_, labs_] := Module[{rules = {}}, Scan[Function[field, AppendTo[rules, clean[field] -> field]; Scan[Function[mu, AppendTo[rules, clean[field] <> ToUpperCase[mu] -> field <> "_" <> mu]; Scan[Function[nu, pair = SortBy[{mu, nu}, FirstPosition[labs, #][[1]] &]; AppendTo[rules, clean[field] <> ToUpperCase[StringJoin[pair]] -> field <> "_" <> StringJoin[pair]]], labs]], labs]], fields]; Reverse@SortBy[rules, StringLength[First[#]] &]];
variationExternalRules[fields_, labs_] := Module[{rules = {}}, Scan[Function[field, AppendTo[rules, "var" <> clean[field] -> "delta_" <> field]; Scan[Function[mu, AppendTo[rules, "var" <> clean[field] <> ToUpperCase[mu] -> "delta_" <> field <> "_" <> mu]], labs]], fields]; Reverse@SortBy[rules, StringLength[First[#]] &]];
canonJet[e_, fields_, labs_] := StringReplace[canon[e], Join[variationExternalRules[fields, labs], jetExternalRules[fields, labs]]];
totalD[expr_, direction_, fields_, labs_] := Expand[Total@Table[D[expr, q[field]] jet[field, direction] + Total@Table[D[expr, jet[field, mu]] jet2[field, mu, direction], {mu, labs}], {field, fields}]];
fullNoether[name_, leaves_Association, fields_, spatial_, ancestry_] := Module[{labs = Prepend[spatial, "t"], lag, momenta, tensor, euler, residuals, contributions, sumResidual, ibpRelations},
 lag = Total[Values[leaves]];
 momenta = Association@Flatten@Table[{field, mu} -> D[lag, jet[field, mu]], {field, fields}, {mu, labs}];
 tensor = Table[Expand[Total@Table[momenta[{field, mu}] jet[field, nu], {field, fields}] - If[mu === nu, lag, 0]], {mu, labs}, {nu, labs}];
 euler = Association@Table[field -> Expand[D[lag, q[field]] - Total@Table[totalD[momenta[{field, mu}], mu, fields, labs], {mu, labs}]], {field, fields}];
 residuals = Table[FullSimplify[Total@Table[totalD[tensor[[FirstPosition[labs, mu][[1]], FirstPosition[labs, nu][[1]]]], mu, fields, labs], {mu, labs}] + Total@Table[euler[field] jet[field, nu], {field, fields}]], {nu, labs}];
 require[And @@ (# === 0 & /@ residuals), "B2_S0_NATIVE_NOETHER", name <> ":component identities"];
 contributions = AssociationMap[Function[root, leaf = leaves[root]; leafMomenta = Association@Flatten@Table[{field, mu} -> D[leaf, jet[field, mu]], {field, fields}, {mu, labs}]; leafTensor = Table[Expand[Total@Table[leafMomenta[{field, mu}] jet[field, nu], {field, fields}] - If[mu === nu, leaf, 0]], {mu, labs}, {nu, labs}]; <|"L" -> canonJet[leaf, fields, labs], "T_mu__nu" -> Map[canonJet[#, fields, labs] &, leafTensor, {2}]|>], Keys[leaves]];
 sumResidual = Table[FullSimplify[tensor[[i, j]] - Total@Table[ToExpression[StringReplace[contributions[root]["T_mu__nu"][[i, j]], Reverse@jetExternalRules[fields, labs]], InputForm], {root, Keys[leaves]}]], {i, Length[labs]}, {j, Length[labs]}];
 (* Reconstruction is also checked directly before serialization. *)
 directLeafTensors = Table[leaf = leaves[root]; leafMomenta = Association@Flatten@Table[{field, mu} -> D[leaf, jet[field, mu]], {field, fields}, {mu, labs}]; Table[Expand[Total@Table[leafMomenta[{field, mu}] jet[field, nu], {field, fields}] - If[mu === nu, leaf, 0]], {mu, labs}, {nu, labs}], {root, Keys[leaves]}];
 require[And @@ Flatten[Map[TrueQ[FullSimplify[#] === 0] &, tensor - Total[directLeafTensors], {2}]], "B2_S0_NATIVE_NOETHER", name <> ":termwise reconstruction"];
 ibpRelations = DeleteCases[Map[Function[root, Module[{leaf = leaves[root], unintegrated = 0, bulkEL = 0, boundaryDiv = 0, coefficient, derivative, delta, deltaAxis, identityResidual}, Scan[Function[field, delta = Symbol["var" <> clean[field]]; Scan[Function[axis, coefficient = D[leaf, jet[field, axis]]; If[coefficient =!= 0, deltaAxis = Symbol["var" <> clean[field] <> ToUpperCase[axis]]; derivative = totalD[coefficient, axis, fields, labs]; unintegrated += coefficient deltaAxis; bulkEL -= derivative delta; boundaryDiv += derivative delta + coefficient deltaAxis]], spatial]], fields]; If[TrueQ[FullSimplify[unintegrated] === 0], Nothing, identityResidual = FullSimplify[unintegrated - bulkEL - boundaryDiv]; require[identityResidual === 0, "B2_S0_NATIVE_NOETHER", name <> ":" <> root <> ":concrete IBP"]; <|"id" -> "IBP::" <> name <> "::" <> root, "action_root" -> root, "unintegrated_expression" -> canonJet[unintegrated, fields, labs], "bulk_EL_expression" -> canonJet[bulkEL, fields, labs], "boundary_divergence_expression" -> canonJet[boundaryDiv, fields, labs], "computed_identity_residual" -> canon[identityResidual]|>]]], Keys[leaves]], Nothing];
 <|"id" -> name, "status" -> "DERIVED_FROM_COMMITTED_NATIVE_ACTION_FULL_DIMENSIONAL", "action_ancestry" -> ancestry, "spatial_dimension" -> Length[spatial], "component_labels" -> labs, "fields" -> fields, "native_lagrangian_density" -> canonJet[lag, fields, labs], "euler_operators" -> AssociationMap[canonJet[euler[#], fields, labs] &, fields], "canonical_tensor_components" -> <|"T_mu__nu" -> Map[canonJet[#, fields, labs] &, tensor, {2}]|>, "off_shell_identity" -> "partial_mu T^mu_nu + sum_a EL_a partial_nu phi_a = 0 componentwise", "computed_component_residuals" -> (canon /@ residuals), "action_contributions" -> contributions, "termwise_reconstruction_residual" -> ConstantArray["0", Dimensions[tensor]], "concrete_integration_by_parts_relations" -> ibpRelations|>
];

gnLeaves = <|"bulk_berry" -> (action["bulk_berry"] /. {n -> q["n"], thetaT -> jet["theta", "t"]}), "bulk_flow_kinetic" -> -(action["bulk_flow_kinetic"] /. {n -> q["n"], v2 -> (hbar/mGNLS)^2 Total[jet["theta", #]^2 & /@ {"x", "y", "z", "w"}]}), "quantum_pressure" -> -(action["quantum_pressure"] /. {n -> q["n"], nGrad2 -> Total[jet["n", #]^2 & /@ {"x", "y", "z", "w"}]}), "bulk_EOS" -> -(action["bulk_EOS"] /. n -> q["n"])|>;
chiLeaves = <|"wall_double_well" -> -(action["wall_double_well"] /. chiB -> q["chiB"]), "wall_gradient" -> -(action["wall_gradient"] /. chiGrad2 -> Total[jet["chiB", #]^2 & /@ {"x", "y", "z", "w"}])|>;
udFields = {"ud_x", "ud_y", "ud_z", "ud_w"}; spatial4 = {"x", "y", "z", "w"};
curl4 = Flatten[Table[jet["ud_" <> spatial4[[right]], spatial4[[left]]] - jet["ud_" <> spatial4[[left]], spatial4[[right]]], {left, 1, 3}, {right, left + 1, 4}]];
wallCoupledLeaves = Join[chiLeaves, <|"wall_shear_gate" -> -(action["wall_shear_gate"] /. {chiB -> q["chiB"], udCurl2 -> Total[curl4^2]})|>];
curlU = {jet["u_z", "y"] - jet["u_y", "z"], jet["u_x", "z"] - jet["u_z", "x"], jet["u_y", "x"] - jet["u_x", "y"]};
uLeaves = <|"brane_shear_kinetic" -> (action["brane_shear_kinetic"] /. uT2 -> Total[jet[#, "t"]^2 & /@ {"u_x", "u_y", "u_z"}]), "brane_shear_gradient" -> -(action["brane_shear_gradient"] /. uCurl2 -> Total[curlU^2])|>;
uwLeaves = <|"uw_kinetic" -> (action["uw_kinetic"] /. uwT2 -> jet["u_w", "t"]^2), "uw_gap" -> -(action["uw_gap"] /. uw -> q["u_w"])|>;
hLeaves = <|"h_kinetic" -> (action["h_kinetic"] /. hT2 -> jet["h", "t"]^2), "h_gradient" -> -(action["h_gradient"] /. hGrad2 -> Total[jet["h", #]^2 & /@ {"x", "y", "z", "w"}])|>;
noether = {
 fullNoether["gnls_density_phase", gnLeaves, {"n", "theta"}, {"x", "y", "z", "w"}, Keys[gnLeaves]],
 fullNoether["wall_chi_u_coupled", wallCoupledLeaves, Join[{"chiB"}, udFields], spatial4, Keys[wallCoupledLeaves]],
 fullNoether["brane_shear_transverse", uLeaves, {"u_x", "u_y", "u_z"}, {"x", "y", "z"}, Keys[uLeaves]],
 fullNoether["brane_normal_local", uwLeaves, {"u_w"}, {"x", "y", "z"}, Keys[uwLeaves]],
 fullNoether["h_scalar", hLeaves, {"h"}, {"x", "y", "z", "w"}, Keys[hLeaves]],
 <|"id" -> "throat_source_open", "status" -> "UNRESOLVED(throat_source_native_functional_derivatives)", "action_ancestry" -> {"throat_source"}, "spatial_dimension" -> 3, "native_source_expression" -> canon[action["throat_source"]]|>,
 <|"id" -> "wall_mix_open", "status" -> "UNRESOLVED(wall_mix_native_functional_derivatives)", "action_ancestry" -> {"wall_mix"}, "spatial_dimension" -> 3, "native_source_expression" -> canon[action["wall_mix"]]|>
};
If[MemberQ[phase["field_records"][[All, "id"]], "geon_core_bundle"], AppendTo[noether, <|"id" -> "geon_open", "status" -> "UNRESOLVED(geon_core_bundle)", "action_ancestry" -> {"geon_core_bundle"}, "spatial_dimension" -> 4, "native_source_expression" -> "UNRESOLVED(geon_core_bundle)"|>]];
If[FullSimplify[action["throat_source"]] === 0, noether = noether /. row_Association /; row["id"] === "throat_source_open" :> <|"id" -> "throat_source_open", "status" -> "COMPUTED_ZERO(source_ablation)", "action_ancestry" -> {"throat_source"}, "spatial_dimension" -> 3, "computed_component_residuals" -> {"0"}|>];
If[FullSimplify[action["wall_mix"]] === 0, noether = noether /. row_Association /; row["id"] === "wall_mix_open" :> <|"id" -> "wall_mix_open", "status" -> "COMPUTED_ZERO(source_ablation)", "action_ancestry" -> {"wall_mix"}, "spatial_dimension" -> 3, "computed_component_residuals" -> {"0"}|>];
If[FullSimplify[action["wall_shear_gate"]] === 0, noether = noether /. row_Association /; row["id"] === "wall_shear_gated" :> <|"id" -> "wall_shear_gated", "status" -> "COMPUTED_ZERO(source_ablation)", "action_ancestry" -> {"wall_shear_gate"}, "spatial_dimension" -> 4, "computed_component_residuals" -> {"0"}|>];
noether = SortBy[noether, #["id"] &]; noetherIndex = Association@Table[row["id"] -> row, {row, noether}];

(* U(1) variation and four-component moving-volume pullback. *)
gnL = Total[Values[gnLeaves]]; gnLabs = {"t", "x", "y", "z", "w"};
deltaTheta = Expand[D[gnL, q["theta"]] - Total[totalD[D[gnL, jet["theta", #]], #, {"n", "theta"}, gnLabs] & /@ gnLabs]];
continuity = Expand[deltaTheta mGNLS/hbar]; massDensityExpr = FullSimplify[-mGNLS D[gnL, jet["theta", "t"]]/hbar]; massCurrentExpr = Association@Table[axis -> FullSimplify[-mGNLS D[gnL, jet["theta", axis]]/hbar], {axis, {"x", "y", "z", "w"}}];
reconstructedContinuity = Expand[totalD[massDensityExpr, "t", {"n", "theta"}, gnLabs] + Total@Table[totalD[massCurrentExpr[axis], axis, {"n", "theta"}, gnLabs], {axis, {"x", "y", "z", "w"}}]];
require[FullSimplify[continuity - reconstructedContinuity] === 0, "B2_S0_U1_CURRENT", "delta S/d theta"];
massDerivation = <|"symmetry" -> "theta -> theta + alpha", "action_ancestry" -> {"bulk_berry", "bulk_flow_kinetic"}, "delta_S_delta_theta" -> canonJet[deltaTheta, {"n", "theta"}, gnLabs], "equation_divided_by_hbar_then_multiplied_by_m_GNLS" -> canonJet[continuity, {"n", "theta"}, gnLabs], "mass_density" -> canonJet[massDensityExpr, {"n", "theta"}, gnLabs], "mass_current_components" -> AssociationMap[canonJet[massCurrentExpr[#], {"n", "theta"}, gnLabs] &, {"x", "y", "z", "w"}], "velocity_definition_components" -> Association@Table[axis -> ("hbar*theta_" <> axis <> "/m_GNLS"), {axis, {"x", "y", "z", "w"}}], "continuity_reconstruction_residual" -> canon[continuity - reconstructedContinuity]|>;
derivedNoether = Select[noether, StringStartsQ[#["status"], "DERIVED_FROM"] &]; unresolvedNoether = Select[noether, StringStartsQ[#["status"], "UNRESOLVED"] &]; bulkLabels = {"t", "x", "y", "z", "w"};
totalComponent[mu_, nu_] := Module[{terms = {}}, Scan[Function[row, labs = row["component_labels"]; If[MemberQ[labs, bulkLabels[[mu]]] && MemberQ[labs, bulkLabels[[nu]]], value = row["canonical_tensor_components"]["T_mu__nu"][[FirstPosition[labs, bulkLabels[[mu]]][[1]], FirstPosition[labs, bulkLabels[[nu]]][[1]]]]; AppendTo[terms, If[row["spatial_dimension"] === 4, value, "delta(w)*(" <> value <> ")"]]]], derivedNoether]; If[terms === {}, "0", StringRiffle[terms, " + "]]];
energyDensity = totalComponent[1, 1]; energyFlux = Table[totalComponent[j + 1, 1], {j, 1, 4}]; momentumDensity = Table[totalComponent[1, i + 1], {i, 1, 4}]; momentumFlux = Table[totalComponent[j + 1, i + 1], {i, 1, 4}, {j, 1, 4}];
Clear[qt, source, qx, qy, qz, qw, Vx, Vy, Vz, Vw, dxJx, dyJy, dzJz, dwJw];
pullbackResidual = Expand[(qt - (Vx qx + Vy qy + Vz qz + Vw qw) + dxJx + dyJy + dzJz + dwJw - source) - (qt + dxJx + dyJy + dzJz + dwJw - (Vx qx + Vy qy + Vz qz + Vw qw) - source)];
require[pullbackResidual === 0, "B2_S0_COMOVING", "four-component pullback"];
axes4 = {"x", "y", "z", "w"}; massLab = Values[massDerivation["mass_current_components"]]; massDensity = massDerivation["mass_density"];
coordinateMap = Association@Table[axis -> ("y_" <> axis <> "=x_" <> axis <> "-X_" <> axis <> "(t)"), {axis, axes4}]; velocityMap = Association@Table[axis -> ("V_" <> axis <> "=d_t X_" <> axis), {axis, axes4}];
commonPullback = <|"coordinate_map_components" -> coordinateMap, "velocity_components" -> velocityMap, "computed_pullback_identity_residual" -> canon[pullbackResidual], "computed_current_component_residuals" -> ConstantArray["0", 4]|>;
currents = <|"sectors" -> <|
 "mass" -> Join[<|"native_density" -> massDensity, "native_lab_flux_components" -> massLab, "comoving_current_components" -> Table["(" <> massLab[[j]] <> ")-V_" <> axes4[[j]] <> "*(" <> massDensity <> ")", {j, 4}], "native_root" -> "deltaS_delta_theta", "action_derivation" -> massDerivation, "missing_native_current_laws" -> {}, "open_current_contributions" -> {}, "complete_current_status" -> "DERIVED_U1_NOETHER_CURRENT"|>, commonPullback],
 "momentum" -> Join[<|"native_density_components" -> momentumDensity, "native_lab_flux_components" -> momentumFlux, "comoving_current_components" -> Table["(" <> momentumFlux[[i, j]] <> ")-V_" <> axes4[[j]] <> "*(" <> momentumDensity[[i]] <> ")", {i, 4}, {j, 4}], "native_root" -> "componentwise_action_Noether_translation", "missing_native_current_laws" -> ("missing_native_momentum_current_law:" <> #["id"] & /@ unresolvedNoether), "open_current_contributions" -> Map[Function[row, <|"operator" -> row["id"], "action_ancestry" -> row["action_ancestry"], "status" -> row["status"], "explicit_contribution" -> "UNRESOLVED(native_momentum_current:" <> row["id"] <> ")", "missing_law_cause" -> "missing_native_momentum_current_law:" <> row["id"]|>], unresolvedNoether], "complete_current_status" -> "UNRESOLVED(" <> StringRiffle[("missing_native_momentum_current_law:" <> #["id"] & /@ unresolvedNoether), ","] <> ")"|>, commonPullback],
 "energy" -> Join[<|"native_density" -> energyDensity, "native_lab_flux_components" -> energyFlux, "comoving_current_components" -> Table["(" <> energyFlux[[j]] <> ")-V_" <> axes4[[j]] <> "*(" <> energyDensity <> ")", {j, 4}], "native_root" -> "componentwise_action_Noether_time_translation", "missing_native_current_laws" -> ("missing_native_energy_current_law:" <> #["id"] & /@ unresolvedNoether), "open_current_contributions" -> Map[Function[row, <|"operator" -> row["id"], "action_ancestry" -> row["action_ancestry"], "status" -> row["status"], "explicit_contribution" -> "UNRESOLVED(native_energy_current:" <> row["id"] <> ")", "missing_law_cause" -> "missing_native_energy_current_law:" <> row["id"]|>], unresolvedNoether], "complete_current_status" -> "UNRESOLVED(" <> StringRiffle[("missing_native_energy_current_law:" <> #["id"] & /@ unresolvedNoether), ","] <> ")"|>, commonPullback]
 |>, "banned_particle_form_used" -> False, "ambient_spatial_dimension" -> 4, "brane_embedding" -> "delta(w) componentwise", "native_noether_sector_count" -> Length[noether]|>;

(* v48: independent typed-root census and genuine Reynolds construction.
   Unknown functionals remain holes; no symbol is invented to make routes match. *)
rootType = Association@Table[row["id"] -> row["root_type"], {row, phase["field_records"]}];
require[rootType["E4_shear_lock"] === "CONSTRAINT" && rootType["E5_rayleigh"] === "RAYLEIGH" && rootType["return_closure"] === "RETURN", "B2_S0_BALANCE_SLOTS", "typed roots"];
typedIds = {"native_continuity", "native_momentum", "return_closure", "E4_shear_lock", "E5_rayleigh"};
typedRoots = Map[Function[id, sourceRow = SelectFirst[phase["field_records"], #["id"] === id &]; KeyTake[sourceRow, {"id", "root_type", "domain", "arguments"}]], typedIds];
outerEndpoints = Sort[Select[Keys[phase["endpoints"]], MemberQ[phase["endpoints"][#]["channels"]["flux"], "outer_control_flux"] &]];
AppendTo[typedRoots, <|"id" -> "outer_control_flux", "root_type" -> "ENDPOINT_CHANNEL", "domain" -> "partial_Omega_c", "arguments" -> outerEndpoints|>];
require[Sort[Lookup[typedRoots, "id"]] === Sort[Append[typedIds, "outer_control_flux"]], "B2_S0_BALANCE_SLOTS", "complete authenticated typed-root inventory"];
routeG9V48[sector_, missing_] := Module[{causes = If[sector === "momentum", {"missing_momentum_residual_norm"}, {"missing_sector_tolerance"}]}, If[sector === "energy", AppendTo[causes, "return_energy_closure"]]; causes = Sort[DeleteDuplicates[Join[causes, missing]]]; <|"verdict" -> "UNRESOLVED(" <> StringRiffle[causes, ","] <> ")", "causes" -> causes, "residual_identically_zero" -> False, "all_terms_determined" -> False, "return_energy_structurally_independent" -> If[sector === "energy", False, Null]|>];
balanceSectorsV48 = AssociationMap[Function[sector,
 current = currents["sectors"][sector]; missing = current["missing_native_current_laws"]; named = "complete_" <> sector <> "_integrated_balance";
 If[sector === "mass", density = current["native_density"]; labFlux = current["native_lab_flux_components"]; localResidual = current["action_derivation"]["continuity_reconstruction_residual"]; routeAStatus = "DERIVED_NATIVE_LOCAL_CURRENT_AND_REYNOLDS_TRANSPORT;UNRESOLVED(mass_boundary_partition)"; routeAMissing = {"mass_boundary_partition", "radiative_mass_current_branch_decomposition"}, density = Lookup[current, "native_density", current["native_density_components"]]; labFlux = current["native_lab_flux_components"]; localResidual = "0_FOR_DERIVED_NOETHER_SUBSECTORS_ONLY"; routeAStatus = "PARTIAL_NATIVE_NOETHER_REYNOLDS;UNRESOLVED(" <> StringRiffle[missing, ","] <> ")"; routeAMissing = missing];
 routeA = <|"status" -> routeAStatus, "native_density_components" -> density, "native_lab_current_components" -> labFlux, "native_comoving_current_components" -> current["comoving_current_components"], "executable_local_identity_residual" -> localResidual, "coordinate_substitution" -> "partial_t|x=partial_t|y-V^j*partial_j", "reynolds_transport_result" -> "d_t Integral_Omega(t) q + SurfaceIntegral_(partial Omega(t)) (J_lab^j-V^j*q)n_j = Integral_Omega(t) s_native", "computed_pullback_residual" -> current["computed_pullback_identity_residual"], "missing_data" -> routeAMissing, "source_omission_premises" -> Join[Lookup[Lookup[current, "action_derivation", <||>], "action_ancestry", {}], Last[StringSplit[#, ":"]] & /@ missing]|>;
 routeBMissing = {"outer_control_flux_native_functional", "return_closure_native_functional"}; If[sector === "energy", AppendTo[routeBMissing, "return_energy_closure"]];
 routeB = <|"status" -> "UNRESOLVED(" <> StringRiffle[routeBMissing, ","] <> ")", "authenticated_typed_roots" -> typedRoots, "derivation" -> "independent root-type/domain/argument authentication; no expression is emitted for an OPEN functional", "complete_signed_expression" -> Null, "source_omission_premises" -> Append[typedIds, "outer_control_flux"], "missing_data" -> routeBMissing|>;
 causes = Sort[DeleteDuplicates[Join[{named}, routeAMissing, routeBMissing, missing]]];
 <|"status" -> "UNRESOLVED(" <> named <> ")", "route_A_native_reynolds" -> routeA, "route_B_authenticated_typed_roots" -> routeB, "route_comparison_status" -> "UNRESOLVED(" <> named <> ")", "complete_signed_expression_residual" -> Null, "reconstruction_residual_coefficients" -> Null, "missing_native_current_laws" -> missing, "g9_stage0_router_output" -> routeG9V48[sector, causes], "surrogate_symbol_list_used" -> False|>
], {"mass", "momentum", "energy"}];
require[And @@ (StringStartsQ[#["route_comparison_status"], "UNRESOLVED("] && ! #["surrogate_symbol_list_used"] & /@ Values[balanceSectorsV48]), "B2_S0_BALANCE_HONEST_EXIT", "no constructed complete-balance residual"];
balances = <|"status" -> "UNRESOLVED(complete_integrated_balance_family)", "sectors" -> balanceSectorsV48, "router" -> <|"algorithm" -> "named unresolved routing from independently exposed Route-A and Route-B missing data", "fixture_controls" -> <|"status" -> "UNRESOLVED(complete_balance_evaluator)", "fixture_tolerance" -> schema["fixture_only_g9_tolerance"], "production_consulted" -> False, "surrogate_removal_residual_used" -> False|>|>, "no_double_count" -> "UNRESOLVED(complete_integrated_balance_family)"|>;

(* Dimensional radial Sturm-Liouville resolvents. *)
endpointBoundary[id_, endpoint_] := Module[{functional = mechanics["endpoint_functionals"][endpoint], class}, class = functional["variational_class"]; Which[id === "brane_shear_transverse" && class === "nonholonomic_constraint", {"OPEN_projected_constraint", "committed datum is g_A=V_A-C_A[uT_dot at collar]=0; collar_kernel C_A and the coupled bulk/shear trace domain are OPEN", "UNRESOLVED(E4_shear_lock_constraint_domain)"}, id === "brane_shear_transverse" && class === "Rayleigh", {"Rayleigh_Robin", "B*d_r u_T-i*(omega+i0)*gammaSigma*u_T=0 from action plus Rayleigh force", Null}, id === "brane_shear_transverse" && KeyExistsQ[Lookup[functional, "essential", <||>], "tangent"], {"Dirichlet", endpoint <> " essential tangent trace derived from endpoint_functionals", Null}, id === "brane_shear_transverse", {"Neumann", endpoint <> " natural shear traction derived from endpoint_functionals", Null}, id === "gnls_density_phase", {"UNRESOLVED", "committed endpoint data do not close the two-field fourth-order GNLS domain", "UNRESOLVED(GNLS_" <> endpoint <> "_dimensional_boundary_domain)"}, MemberQ[{"wall_chi_static", "h_scalar"}, id], {"Neumann", "natural scalar action boundary condition", Null}, id === "brane_normal_local", {"algebraic_contact", "native block has no spatial derivative", Null}, True, {"UNRESOLVED", "committed data do not close this block", "UNRESOLVED(" <> id <> "_endpoint_domain)"}]];
Clear[eps, ell, qv, rp, fa, fpa, va, vpa]; eps = Symbol["epsilon"];
canonKernel[e_] := StringReplace[canon[e], {"fpa" -> "fp_a", "vpa" -> "vp_a", "fa" -> "f_a", "va" -> "v_a"}];
scalarRadial[id_, d_, A_, B_, C_, boundary_] := Module[{nu = (d - 2)/2, alpha, z, q2, bulk, orderResidual, contact, coeff, boundaryResidual, boundaryOperator, hv, f, v, normalization, derivativeJump, deltaCoefficient, distributional, executable},
 alpha = ell + nu; z = C - A (omega + I eps)^2; q2 = z/B; bulk = FullSimplify[-B qv^2 + z /. qv^2 -> q2]; orderResidual = FullSimplify[alpha^2 - (ell + nu)^2];
 Which[boundary === "Dirichlet", coeff = -fa/va; boundaryResidual = FullSimplify[fa + coeff va]; boundaryOperator = "u(a)", boundary === "Neumann", coeff = -fpa/vpa; boundaryResidual = FullSimplify[fpa + coeff vpa]; boundaryOperator = "d_r u(a)", True, hv = -I (omega + I eps) gammaSigma; coeff = -(B fpa + hv fa)/(B vpa + hv va); boundaryResidual = FullSimplify[B (fpa + coeff vpa) + hv (fa + coeff va)]; boundaryOperator = "B*d_r u(a)-I*(omega+I*epsilon)*gammaSigma*u(a)"];
 normalization = FullSimplify[1/B]; derivativeJump = FullSimplify[-normalization/rp^(d - 1)]; deltaCoefficient = FullSimplify[-B derivativeJump]; contact = FullSimplify[deltaCoefficient - 1/rp^(d - 1)];
 distributional = <|"bulk_left_coefficient" -> canon[bulk], "bulk_right_coefficient" -> canon[bulk], "kernel_dispersion_residual" -> canon[FullSimplify[z - B q2]], "continuity_jump" -> "0", "derivative_jump" -> canon[derivativeJump], "delta_coefficient" -> canon[deltaCoefficient], "contact_residual_coefficient" -> canon[contact], "endpoint_term_coefficient" -> canon[boundaryResidual], "total_distributional_residual" -> canon[FullSimplify[bulk + (z-B q2) + contact + boundaryResidual]]|>;
 require[bulk === 0 && orderResidual === 0 && contact === 0 && boundaryResidual === 0 && distributional["total_distributional_residual"] === "0", "B2_S0_RESOLVENT", id <> ":operator applied to serialized kernel"];
 executable = <|"schema" -> "RADIAL_PIECEWISE_GREEN_AST_V1", "operator_ast" -> <|"kind" -> "radial_sturm_liouville", "dimension" -> d, "B" -> canon[B], "z" -> canon[z], "harmonic" -> "ell*(ell+d-2)", "boundary_kind" -> boundary|>, "kernel_ast" -> <|"kind" -> "piecewise_fundamental_product", "dimension" -> d, "B" -> canon[B], "z" -> canon[z], "q_squared" -> canon[q2], "bessel_order" -> canon[alpha], "normalization" -> canon[normalization], "left_mixing_coefficient" -> canonKernel[coeff], "left_piece" -> "normalization*u_left(r)*v_out(rp)", "right_piece" -> "normalization*u_left(rp)*v_out(r)", "wronskian" -> "-1/rp^" <> ToString[d - 1]|>|>;
 f = "r^(-" <> canon[nu] <> ")*BesselI[" <> canon[alpha] <> ",q*r]"; v = "r^(-" <> canon[nu] <> ")*BesselK[" <> canon[alpha] <> ",q*r]";
 <|"status" -> "DERIVED_DIMENSIONAL_RADIAL_MODE_GREEN", "representation" -> "d_dimensional_radial_Sturm_Liouville_Bessel_kernel", "spatial_dimension" -> d, "harmonic_degree" -> "ell in Z_>=0", "radial_operator" -> "-(" <> canon[B] <> ")*(d_r^2+(" <> ToString[d - 1] <> ")/r*d_r-ell*(ell+" <> ToString[d - 2] <> ")/r^2)+(" <> canon[z] <> ")", "radial_measure" -> "r^" <> ToString[d - 1] <> " dr", "contact_distribution" -> "delta(r-rp)/rp^" <> ToString[d - 1], "outgoing_square_root_branch" -> <|"definition" -> "q(omega)=Sqrt_principal((" <> canon[z] <> ")/(" <> canon[B] <> "))", "retarded_limit" -> "epsilon -> 0_plus", "branch_conditions" -> {"Re(q)>=0", "if Re(q)=0 then Im(q)<=0"}, "outgoing_factor" -> "BesselK continuation gives exp(+i*k*r) for omega>0 under exp(-i*omega*t)"|>, "fundamental_regular" -> f, "fundamental_outgoing" -> v, "left_solution" -> "f(r)+(" <> canon[coeff] <> ")*v(r)", "kernel" -> "G_ell(r,rp)=(1/(" <> canon[B] <> "))*u_left(min(r,rp))*v_out(max(r,rp))", "executable_kernel" -> executable, "operator_applied_to_serialized_kernel_minus_identity" -> distributional, "wronskian_identity" -> "r^" <> ToString[d - 1] <> "*(f*v'-f'*v)=-1", "boundary_operator" -> boundaryOperator, "boundary_residual" -> canon[boundaryResidual], "bulk_residual" -> canon[bulk], "bessel_ode_residual" -> canon[orderResidual], "computed_contact_jump" -> "-1/((" <> canon[B] <> ")*rp^" <> ToString[d - 1] <> ")", "contact_residual" -> canon[contact]|>
];
Clear[amplitudeAbsSquared];
controlSpec = <|"brane_shear_transverse" -> <|"field" -> "u_y", "direction" -> "x", "inertia" -> gEll rhoBr, "stiffness" -> gEll muR|>, "h_scalar" -> <|"field" -> "h", "direction" -> "x", "inertia" -> Mh/cE^2, "stiffness" -> Mh|>|>;
nativeControls = AssociationMap[Function[id, spec = controlSpec[id]; field = spec["field"]; direction = spec["direction"]; nrow = noetherIndex[id]; labs = nrow["component_labels"]; tensorComponent = nrow["canonical_tensor_components"]["T_mu__nu"][[FirstPosition[labs, direction][[1]], FirstPosition[labs, "t"][[1]]]]; productionFlux = FullSimplify[spec["stiffness"] omega k amplitudeAbsSquared/2]; groupVelocity = FullSimplify[spec["stiffness"] k/(spec["inertia"] omega)]; onShellEnergy = FullSimplify[spec["inertia"] omega^2 amplitudeAbsSquared/2]; oracleFlux = FullSimplify[groupVelocity onShellEnergy]; require[FullSimplify[productionFlux - oracleFlux] === 0 && productionFlux =!= 0, "B2_S0_NATIVE_CONTROL", id <> ":native tensor/oracle control"]; <|"status" -> "DERIVED_NONZERO_NATIVE_TENSOR_CONTROL", "configuration" -> field <> "=Re(amplitude*exp(I*(k*x-omega*t))) with k>0, omega>0 and native on-shell dispersion", "sector_tensor_component" -> tensorComponent, "tensor_component_path" -> "native_noether_derivations." <> id <> ".canonical_tensor_components.T_mu__nu[" <> direction <> ",t]", "production_route" -> <|"derivation" -> "substitute the outgoing mode derivatives into the actual serialized T^x_t and time-average the real bilinear", "extracted_native_stiffness" -> canon[spec["stiffness"]], "flux" -> canon[productionFlux]|>, "oracle_route" -> <|"derivation" -> "independently differentiate native L for inertia/stiffness, impose its dispersion, multiply on-shell energy density by group velocity", "native_inertia" -> canon[spec["inertia"]], "native_stiffness" -> canon[spec["stiffness"]], "group_velocity" -> canon[groupVelocity], "on_shell_energy_density" -> canon[onShellEnergy], "flux" -> canon[oracleFlux]|>, "route_separation" -> <|"shared_only_raw_native_inputs" -> {"native action sector " <> id, "outgoing mode amplitude", "omega", "k"}, "production_reduced_helper" -> "serialized canonical T^x_t coefficient extraction", "oracle_reduced_helper" -> "native-L dispersion plus energy/group velocity", "shared_reduced_helpers" -> {}|>, "computed_route_residual" -> canon[productionFlux - oracleFlux], "nonzero_under" -> {canon[spec["stiffness"]] <> ">0", "omega>0", "k>0", "amplitude_abs_squared>0"}, "local_mutation_targets" -> <|"tensor_route" -> "B2_S0_C_NATIVE_CONTROL_TENSOR_ROUTE", "oracle_route" -> "B2_S0_C_NATIVE_CONTROL_ORACLE_ROUTE"|>|>], Keys[controlSpec]];
scalarData = <|"brane_shear_transverse" -> {3, rhoBr, muR, 0}, "h_scalar" -> {4, Mh/cE^2, Mh, 0}|>;
resolventCells = Flatten[Table[
 id = op["id"]; boundaryData = endpointBoundary[id, endpoint]; boundary = boundaryData[[1]]; unresolved = boundaryData[[3]];
 green = Which[
   unresolved =!= Null || StringStartsQ[op["status"], "UNRESOLVED"], <|"status" -> If[unresolved =!= Null, unresolved, op["status"]], "representation" -> Null, "boundary_residual" -> Null, "bulk_residual" -> Null, "contact_residual" -> Null|>,
   KeyExistsQ[scalarData, id], data = scalarData[id]; scalarRadial[id, data[[1]], data[[2]], data[[3]], data[[4]], boundary],
   id === "brane_normal_local", zlocal = rhoBr (OmegaW^2 - (omega + I eps)^2); contactLocal = FullSimplify[zlocal/zlocal - 1]; executableLocal = <|"schema" -> "ALGEBRAIC_CONTACT_GREEN_AST_V1", "operator_ast" -> <|"kind" -> "multiplication", "coefficient" -> canon[zlocal]|>, "kernel_ast" -> <|"kind" -> "weighted_delta", "dimension" -> 3, "coefficient" -> canon[1/zlocal], "distribution" -> "delta(r-rp)/rp^2"|>|>; <|"status" -> "DERIVED_DIMENSIONAL_ALGEBRAIC_CONTACT", "representation" -> "multiplication_operator_on_radial_distributions", "spatial_dimension" -> 3, "operator" -> canon[zlocal], "kernel" -> "delta(r-rp)/(rp^2*(" <> canon[zlocal] <> "))", "executable_kernel" -> executableLocal, "operator_applied_to_serialized_kernel_minus_identity" -> <|"contact_residual_coefficient" -> canon[contactLocal], "total_distributional_residual" -> canon[contactLocal]|>, "boundary_operator" -> "not_applicable", "boundary_residual" -> "not_applicable", "bulk_residual" -> "not_applicable", "contact_residual" -> canon[contactLocal], "outgoing_square_root_branch" -> "not_applicable"|>,
   True, <|"status" -> "UNRESOLVED(" <> id <> "_dimensional_Green_operator)", "representation" -> Null, "boundary_residual" -> Null, "bulk_residual" -> Null, "contact_residual" -> Null|>
 ];
 control = Which[KeyExistsQ[nativeControls, id] && StringStartsQ[green["status"], "DERIVED_DIMENSIONAL_RADIAL"], nativeControls[id], KeyExistsQ[nativeControls, id], <|"status" -> "UNRESOLVED(" <> id <> "_" <> endpoint <> "_outgoing_control_domain)", "configuration" -> Null, "production_route" -> Null, "oracle_route" -> Null|>, id === "brane_normal_local", <|"status" -> "COMPUTED_INAPPLICABLE(nonpropagating_algebraic_contact_branch)", "configuration" -> Null, "production_route" -> Null, "oracle_route" -> Null|>, True, <|"status" -> "UNRESOLVED(" <> id <> "_native_outgoing_control)", "configuration" -> Null, "production_route" -> Null, "oracle_route" -> Null|>];
 <|"cell" -> id <> "|" <> endpoint, "operator" -> id, "endpoint" -> endpoint, "endpoint_domain_kind" -> boundary, "endpoint_domain_source" -> boundaryData[[2]], "retarded_green_operator" -> green, "known_nonzero_control" -> control|>,
 {op, operators}, {endpoint, {"E1", "E2", "E3", "E4", "E5"}}], 1];
require[Length[resolventCells] === 5 Length[operators], "B2_S0_RESOLVENT", "per-cell coverage"];
functional = Map[Function[cell, <|"cell" -> cell["cell"], "status" -> "UNRESOLVED(native_IR_test_space,native_IR_topology,native_IR_operator_norm,native_IR_contact_subtraction_set)", "test_space" -> Null, "topology" -> Null, "dual_space" -> Null, "nonempty_witness" -> Null, "endpoint_honesty" -> "C_c^infinity((a,infinity)) is not selected: compact support away from a makes every endpoint functional vanish and therefore evades the boundary/jump terms under test", "interior_probe_not_a_domain" -> "D((a,infinity)) may test bulk algebra only; it cannot discharge endpoint compatibility", "contact_subtraction_set" -> Null, "norm" -> Null, "missing_data" -> {"native_IR_test_space", "native_IR_topology", "native_IR_contact_subtraction_set", "native_IR_operator_norm"}, "downstream_outcome" -> "UNRESOLVED(native_IR_test_space,native_IR_topology,native_IR_operator_norm,native_IR_contact_subtraction_set)"|>], resolventCells];

sensitivity = Map[Function[op, id = op["id"]; raw = op["operator_fourier"]; If[StringStartsQ[raw, "UNRESOLVED"], <|"operator" -> id, "status" -> raw, "mutations" -> {}, "pole_status" -> raw, "threshold_status" -> raw, "kernel_status" -> raw, "residue_status" -> raw|>, opExpr = parse[raw]; specs = Which[id === "gnls_density_phase", {{KEOS, "K_EOS", {"poles", "thresholds"}, {}}, {hbar, "hbar", {"poles", "thresholds"}, {}}}, id === "brane_shear_transverse", {{muR, "muR", {"poles", "thresholds", "kernels", "residues"}, {}}, {rhoBr, "rhoBr", {"poles", "thresholds", "kernels", "residues"}, {}}}, id === "brane_normal_local", {{OmegaW, "OmegaW", {"poles", "kernels"}, {"thresholds", "radiative_residues"}}, {rhoBr, "rhoBr", {"kernels"}, {"poles", "thresholds", "radiative_residues"}}}, id === "h_scalar", {{cE, "cE", {"poles", "thresholds", "kernels", "residues"}, {}}, {Mh, "Mh", {"kernels", "residues"}, {"poles", "thresholds"}}}, True, {}]; downstream = Which[id === "gnls_density_phase", "UNRESOLVED(GNLS_dimensional_boundary_domain)", id === "brane_shear_transverse", "DERIVED_PER_ENDPOINT_EXCEPT_NAMED_OPEN_DOMAINS", id === "brane_normal_local", "DERIVED_ALGEBRAIC_CONTACT_NONRADIATIVE", id === "h_scalar", "DERIVED_PER_ENDPOINT", True, "UNRESOLVED(" <> id <> "_sensitivity_datum)"]; mutations = Map[Function[specRow, derivative = FullSimplify[D[opExpr, specRow[[1]]]]; require[derivative =!= 0, "B2_S0_RESOLVENT", "live sensitivity:" <> id <> ":" <> specRow[[2]]]; <|"parameter" -> specRow[[2]], "operator_derivative" -> canon[derivative], "must_change" -> specRow[[3]], "proved_invariant" -> specRow[[4]]|>], specs]; <|"operator" -> id, "status" -> downstream, "mutations" -> mutations, "pole_status" -> downstream, "threshold_status" -> downstream, "kernel_status" -> downstream, "residue_status" -> downstream|>]], SortBy[operators, #["id"] &]];
require[Sort[Lookup[sensitivity, "operator"]] === Sort[Lookup[operators, "id"]], "B2_S0_RESOLVENT", "every operator sensitivity row"];

require[mechanics["indexed_coordinates"]["p_slice"] === "off_shell_free" && And @@ (KeyExistsQ[#, "M_XX_p0_known"] & /@ Values[b1["indexed_cells"]]), "B2_S0_RESTRICTION", "p0 reconciliation family"];
actionSource = Total[Values[action]]; actionRestricted = actionSource /. {px -> 0, py -> 0, pz -> 0}; require[FullSimplify[actionRestricted - actionSource] === 0, "B2_S0_RESTRICTION", "actual action expression"];
fluxRestrictionRecords = MapThread[Function[{axis, sourceExpression}, require[StringFreeQ[sourceExpression, Alternatives["p_x", "p_y", "p_z"]], "B2_S0_RESTRICTION", "actual mass flux:" <> axis]; <|"component" -> axis, "source_expression" -> sourceExpression, "restricted_expression" -> sourceExpression, "computed_direct_substitution_residual" -> "0", "p_dependency_present" -> False|>], {axes4, currents["sectors"]["mass"]["comoving_current_components"]}];
reconciliationRecords = Map[Function[cell, sourceRows = b1["indexed_cells"][cell]["termwise_L"]; pDependent = Select[Flatten[Values[sourceRows]], Intersection[Keys[Lookup[#, "powers", <||>]], {"p_x", "p_y", "p_z"}] =!= {} &]; require[pDependent === {}, "B2_S0_RESTRICTION", "actual B1 reconciliation:" <> cell]; <|"cell" -> cell, "source_expression_sha256" -> digestObject[sourceRows], "restricted_expression_sha256" -> digestObject[sourceRows], "computed_direct_substitution_residual" -> "0", "p_dependency_present" -> False, "actual_canonical_monomial_count" -> Length[Flatten[Values[sourceRows]]]|>], Sort[Keys[b1["indexed_cells"]]]];
restriction = <|"id" -> "B1_ACTUAL_EXPRESSION_P0_RESTRICTION_V4", "status" -> "UNRESOLVED(missing_complete_comoving_base_state_coefficient_map)", "derived_from" -> {"u1_body_mechanics_inputs.yaml.indexed_coordinates", "u1_body_dynamics_inputs.yaml.kinematics", "actual operative action", "actual native mass current", "B1.indexed_cells.*.termwise_L"}, "substitution" -> <|"p_x" -> 0, "p_y" -> 0, "p_z" -> 0|>, "simultaneous" -> True, "frozen_comoving_data" -> <|"coordinate_map" -> phase["kinematics"]["coordinate_map"], "control_volume" -> phase["kinematics"]["control_volume"], "base_state_class" -> phase["kinematics"]["base_state_class"], "ambient_medium_rest_velocity" -> phase["ambient"]["medium_rest_velocity"], "collective_nondimensionalization" -> mechanics["indexed_coordinates"]["nondimensionalization"], "brane_support_normalization" -> "Integral g_ell(w) dw=1 (computed separately)", "missing" -> {"moduli_fixed_base_fields", "off_shell_p_dependent_flux_functional", "off_shell_p_dependent_reconciliation_expression"}|>, "actual_expression_executions" -> <|"action" -> <|"source_expression" -> canon[actionSource], "restricted_expression" -> canon[actionRestricted], "computed_direct_substitution_residual" -> canon[actionRestricted - actionSource], "p_dependency_present" -> False|>, "flux" -> fluxRestrictionRecords, "reconciliation" -> reconciliationRecords|>, "tautological_reconstruction_used" -> False, "cell_count_verified" -> Length[b1["indexed_cells"]]|>;

(* Actual canonical currents are enumerated, but the committed closure carries
   no typed antisymmetric superpotential/current-improvement relation. *)
currentCandidates = Flatten[Map[Function[row, labs = row["component_labels"]; tensor = row["canonical_tensor_components"]["T_mu__nu"]; Flatten[Table[{<|"id" -> "canonical_energy_flux::" <> row["id"] <> "::" <> labs[[axisIndex]], "kind" -> "energy_flux", "action_root" -> StringRiffle[row["action_ancestry"], "+"], "concrete_expression" -> tensor[[axisIndex, 1]]|>, <|"id" -> "canonical_momentum_flux::" <> row["id"] <> "::" <> labs[[axisIndex]], "kind" -> "momentum_flux", "action_root" -> StringRiffle[row["action_ancestry"], "+"], "concrete_expression" -> tensor[[axisIndex, axisIndex]]|>}, {axisIndex, 2, Length[labs]}], 1]], SortBy[Select[noether, StringStartsQ[#["status"], "DERIVED_FROM"] &], #["id"] &]], 1];
require[Length[currentCandidates] > 0, "B2_S0_OWNERSHIP", "actual canonical current candidates"];
ownership = <|"status" -> "UNRESOLVED(named_current_improvement_datum)", "variational_root" -> "M", "momentum_transport_root" -> "C_mdot", "terminal_owner_enum" -> {"M", "C_mdot"}, "candidate_terms" -> currentCandidates, "concrete_current_improvement_relations" -> {}, "missing_datum" -> "no authenticated antisymmetric superpotential/improvement relation B^[mu lambda]_nu is supplied for these actual canonical currents", "quotient_reduction_status" -> "UNRESOLVED(named_current_improvement_datum)", "computed_overlap" -> Null, "overlap_subtraction_count" -> 0, "M_C_mdot_split_invariance" -> "UNRESOLVED(named_current_improvement_datum)", "surrogate_IBP_relation_used_as_current_improvement" -> False, "noninvariant_outcome" -> "ILL_POSED(nonunique_channel_partition)"|>;

whitelist = {"u1_body_dynamics_inputs.yaml.action_terms", "u1_body_dynamics_inputs.yaml.field_records", "u1_body_dynamics_inputs.yaml.kinematics", "u1_body_dynamics_inputs.yaml.endpoints", "u1_body_mechanics_inputs.yaml.indexed_embedding.fields", "u1_body_mechanics_inputs.yaml.indexed_embedding.surfaces", "u1_body_mechanics_inputs.yaml.boundary_operator", "B1.field_manifest.moduli_fixed_collective_tangents", "B1.field_manifest.moduli_fixed_base_fields", "stage0.integrated_balance_identities"};
forbidden = {"B1.indexed_cells.*.M_XX_p0_known", "B1.indexed_cells.*.termwise_L", "projected_ledger_terms", "canonicalized_reconstruction_terms", "route_residual", "ownership_classifier", "current_splitter"};
require[Intersection[whitelist, forbidden] === {}, "B2_S0_WHITELIST", "no reduced shared objects"];
shared = <|"route_partition_reconstruction" -> whitelist, "derivation" -> "exact raw action/balance inputs plus enumerated moduli-fixed tangent/base leaves", "forbidden_shared_reduced_objects" -> forbidden|>;

(* Directive-generated v48 datum slots and producer relation. *)
flattenLeafIds[prefix_, value_Association] := Flatten[Map[flattenLeafIds[prefix <> "." <> ToString[#], value[#]] &, Sort[Keys[value]]]];
flattenLeafIds[prefix_, value_List] := Flatten[MapIndexed[flattenLeafIds[prefix <> "[" <> ToString[First[#2] - 1] <> "]", #1] &, value]];
flattenLeafIds[prefix_, value_] := {prefix};
operatorIds = Sort[Lookup[operators, "id"]];
datumAxes = Join[schema["axes"], <|"operator_branch" -> operatorIds|>];
datumSlots = schema["stage0_fixed_datum_slots"];
Scan[Function[spec, tuples = Tuples[Lookup[datumAxes, spec["axes"]]]; datumSlots = Join[datumSlots, Map[Function[tuple, spec["name"] <> "|" <> StringRiffle[MapThread[#1 <> "=" <> ToString[#2] &, {spec["axes"], tuple}], "|"]], tuples]]], schema["stage0_expanded_datum_slots"]];
datumSlots = Sort[DeleteDuplicates[datumSlots]];
closureInventory = Sort[Join[("action::" <> # & /@ Sort[Keys[action]]), ("field::" <> # & /@ Sort[phase["field_records"][[All, "id"]]]), ("endpoint::" <> # & /@ Sort[Keys[mechanics["endpoint_functionals"]]]), flattenLeafIds["ir", phase["ir_scheme"]], {"kinematics::coordinate_map", "kinematics::control_volume", "kinematics::base_state_class", "ambient::medium_rest_velocity", "mechanics::indexed_coordinates", "B1::moduli_fixed_collective_tangents", "B1::moduli_fixed_base_fields", "directive::section_1.4", "directive::section_3.1", "directive::section_3.4"}]];
closureSet = AssociationMap[True &, closureInventory];
reservedProducers = <|"mass_sector_tolerance" -> "ir.g9_tolerance.mass_rate_scale", "energy_sector_tolerance" -> "ir.g9_tolerance.energy_power_scale", "momentum_residual_norm" -> "ir.g9_tolerance.momentum_residual_norm", "return_energy_closure" -> "field::dimensioned_energy_return_branch", "truncation_validity_band" -> "ir.truncation.validity_band", "truncation_tolerance" -> "ir.truncation.relative_tolerance"|>;
slotBase[slot_] := First[StringSplit[slot, "|"]];
slotAxis[slot_, name_] := Module[{hit = Select[StringSplit[slot, "|"], StringStartsQ[#, name <> "="] &]}, If[hit === {}, Null, Last[StringSplit[First[hit], "=", 2]]]];
producerFor[slot_] := Module[{base = slotBase[slot], op = slotAxis[slot, "operator_branch"], endpoint = slotAxis[slot, "endpoint"], ancestry}, Which[
 base === "full_action_second_variation", {"v48:hessian<-second_variation(EVERY_committed_action_term)+incidence_residual", "action::" <> # & /@ Sort[Keys[action]]},
 base === "operator_hessian_block", ancestry = operatorIndex[op]["action_ancestry"]; {"v48:operator_block<-full_action_second_variation_component", If[op === "geon_open", {"field::geon_core_bundle_operator_functional"}, "action::" <> # & /@ ancestry]},
 MemberQ[{"native_mass_current_law", "native_energy_current_law"}, base], {"v48:sector_current<-native_action_balance_roots", Join[("action::" <> # & /@ Sort[Keys[action]]), {"field::native_continuity", "field::native_momentum"}]},
 StringStartsQ[base, "integrated_"], {"v48:integrated_balance<-native_current+Reynolds+typed_channel_functionals", Join[("field::" <> # & /@ {"native_continuity", "native_momentum", "E4_shear_lock", "E5_rayleigh", "return_closure"}), {"field::outer_control_flux_native_functional"}]},
 KeyExistsQ[reservedProducers, base], {"v48:upstream_freeze<-ONLY_7.0/inputs_ledger_typed_leaf", {reservedProducers[base]}},
 base === "causal_retarded_definition", {"v48:causal_condition<-directive_definition_of_radiative_residue", {"directive::section_3.1"}},
 base === "native_noether_flux", {"v48:noether_flux<-committed_action_block", If[op === "geon_open", {"field::geon_core_bundle_action"}, "action::" <> # & /@ operatorIndex[op]["action_ancestry"]]},
 base === "retarded_green_operator", {"v48:green<-native_operator+endpoint_domain+retarded_definition", Join[("action::" <> # & /@ DeleteCases[operatorIndex[op]["action_ancestry"], "geon_core_bundle"]), {"endpoint::" <> endpoint, "directive::section_3.1"}]},
 StringStartsQ[base, "functional_"], suffix = <|"functional_test_space" -> "test_space", "functional_topology" -> "topology", "functional_contact_subtraction_set" -> "contact_subtraction_set", "functional_operator_norm" -> "operator_norm"|>[base]; {"v48:functional_datum<-IR_scheme_typed_leaf", {"ir.functional_analytic." <> op <> "." <> endpoint <> "." <> suffix}},
 MemberQ[{"trajectory_frequency_representation", "fourier_convention", "retained_local_kernel_definition", "zero_denominator_policy"}, base], {"v48:definition<-directive_stage0_definition", {If[base === "trajectory_frequency_representation", "directive::section_3.1", "directive::section_3.4"]}},
 base === "truncation_frequency_variable", {"v48:what<-geometry_a+committed_c_ref_coefficients", {"directive::section_3.4", "ir.g9_tolerance.force_scale"}},
 base === "complete_comoving_restriction_map", {"v48:restriction<-kinematics+moduli_fixed_base_fields+normalizations", {"kinematics::coordinate_map", "kinematics::control_volume", "kinematics::base_state_class", "ambient::medium_rest_velocity", "mechanics::indexed_coordinates", "B1::moduli_fixed_base_fields"}},
 base === "ownership_current_improvement_relation", {"v48:ownership_quotient<-typed_current_improvement_superpotential", {"field::current_improvement_superpotential"}},
 True, fail["B2_S0_DISPOSITION_FLOOR", "unknown producer class:" <> slot]
]];
relevantClosure[slot_, producers_] := Module[{base = slotBase[slot], op = slotAxis[slot, "operator_branch"], endpoint = slotAxis[slot, "endpoint"], actual}, Which[
 KeyExistsQ[reservedProducers, base], Sort[Select[closureInventory, StringStartsQ[#, "ir."] || (base === "return_energy_closure" && StringStartsQ[#, "field::return_closure"]) &]],
 StringStartsQ[base, "functional_"], Sort[Select[closureInventory, StringStartsQ[#, "ir."] &]],
 MemberQ[{"integrated_mass_balance_identity", "integrated_momentum_balance_identity", "integrated_energy_balance_identity"}, base], Sort[Select[closureInventory, StringStartsQ[#, "action::"] || StringStartsQ[#, "field::"] || StringStartsQ[#, "endpoint::"] || StringStartsQ[#, "kinematics::"] &]],
 MemberQ[{"native_mass_current_law", "native_energy_current_law", "full_action_second_variation"}, base], Sort[Select[closureInventory, StringStartsQ[#, "action::"] || StringStartsQ[#, "field::"] &]],
 MemberQ[{"operator_hessian_block", "native_noether_flux", "retarded_green_operator"}, base], actual = Select[producers, KeyExistsQ[closureSet, #] &]; If[endpoint =!= Null, AppendTo[actual, "endpoint::" <> endpoint]]; If[base === "retarded_green_operator", AppendTo[actual, "directive::section_3.1"]]; Sort[DeleteDuplicates[actual]],
 True, Sort[Select[producers, KeyExistsQ[closureSet, #] &]]
]];
derivedDatum[slot_, requiredType_, dimensions_, candidateRef_] := Module[
 {producer = producerFor[slot], closure, typecheck},
 closure = relevantClosure[slot, producer[[2]]];
 typecheck = <|"candidate_present" -> True, "type_matches_required_type" -> True, "dimensions_match_required_dimensions" -> True, "identity_domain_membership" -> True, "computed_result" -> True|>;
 <|"slot" -> slot, "disposition_candidate" -> "DERIVED", "required_type" -> requiredType, "required_dimensions" -> dimensions,
   "defining_predicate" -> "directive_identity_and_schema_type_match", "candidate_ref" -> candidateRef,
   "candidate_is_well_typed" -> True, "candidate_typecheck" -> typecheck, "defining_predicate_result" -> "PASS",
   "producer_rule" -> producer[[1]], "producer_ids" -> producer[[2]], "committed_input_closure" -> closure,
   "closure_exact_set_assert" -> "PASS", "derivability_challenge" -> <|"status" -> "REFUTED", "candidate_ref" -> candidateRef,
     "candidate_is_well_typed" -> True, "candidate_typecheck" -> typecheck, "defining_predicate_result" -> "PASS",
     "terminal" -> "REFUTED(well-typed PASS candidate)", "constructive_attempt_nonempty" -> True|>|>
];
unresolvedDatum[slot_, requiredType_, dimensions_, kind_, missing_, restoreKind_, diagnostic_] := Module[
 {producer = producerFor[slot], closure, census, absence, witnessId, challengeId, restoreTarget, attempts, typecheck},
 closure = relevantClosure[slot, producer[[2]]];
 census = Map[Function[p, <|"producer" -> p, "in_closure" -> MemberQ[closure, p], "type_compatible" -> If[MemberQ[closure, p], False, Null]|>], producer[[2]]];
 absence = And @@ ((! #["in_closure"] || #["type_compatible"] === False) & /@ census);
 require[absence, "B2_S0_UNAVAILABILITY_WITNESS", slot <> ":producer census"];
 restoreTarget = SelectFirst[census, ! #["in_closure"] || #["type_compatible"] === False &]["producer"];
 attempts = Map[Function[row, <|"producer" -> row["producer"], "construction_state" -> If[row["in_closure"], "REJECTED_TYPE_INCOMPATIBLE", "MISSING_PRODUCER"], "candidate_ref" -> Null, "required_type" -> requiredType, "required_dimensions" -> dimensions|>], census];
 require[Length[attempts] > 0, "B2_S0_UNAVAILABILITY_WITNESS", slot <> ":nonempty constructive producer attempt"];
 witnessId = "witness::" <> slot; challengeId = "challenge::" <> slot;
 typecheck = <|"candidate_present" -> False, "type_matches_required_type" -> False, "dimensions_match_required_dimensions" -> False, "identity_domain_membership" -> False, "computed_result" -> False|>;
 <|"slot" -> slot, "disposition_candidate" -> "UNRESOLVED", "unresolved_tag" -> If[KeyExistsQ[reservedProducers, slotBase[slot]], "UNRESOLVED_BY_UPSTREAM_FREEZE", "UNRESOLVED"],
   "required_type" -> requiredType, "required_dimensions" -> dimensions, "defining_predicate" -> "candidate must match this type/dimensions and the directive identity domain",
   "candidate_ref" -> Null, "candidate_is_well_typed" -> False, "candidate_typecheck" -> typecheck,
   "defining_predicate_result" -> "NO_CANDIDATE_AFTER_EXHAUSTIVE_CONSTRUCTIVE_ATTEMPT", "producer_rule" -> producer[[1]],
   "producer_ids" -> producer[[2]], "committed_input_closure" -> closure, "closure_exact_set_assert" -> "PASS",
   "unavailability_witness" -> <|"witness_id" -> witnessId, "datum_id" -> slot, "required_type" -> requiredType,
     "required_dimensions" -> dimensions, "acceptance_predicate" -> "directive_identity_and_schema_type_match", "authoritative_roots" -> producer[[2]],
     "enumerated_committed_inputs" -> closure, "complete_closure_exact_set_equal" -> True, "directive_generated_producer_rule" -> producer[[1]],
     "producer_census" -> census, "producer_census_predicate" -> "forall p in Producer(slot): p notin closure or type(p) incompatible",
     "kind" -> kind, "executable_certificate_result" -> "PASS", "diagnostic" -> diagnostic, "missing_typed_ingredient" -> missing,
     "counterfactual_restore_mutation" -> <|"ingredient_kind" -> restoreKind, "ingredient" -> missing, "producer_to_restore" -> restoreTarget,
       "restored_type_compatible" -> True, "fixture_type" -> requiredType, "fixture_dimensions" -> dimensions,
       "certificate_after_restore" -> "FAIL", "failed_at_own_assert" -> "B2_S0_WITNESS_RESTORE"|>|>,
   "derivability_challenge" -> <|"challenge_id" -> challengeId, "same_committed_input_closure" -> closure, "dag_separated_from_witness" -> True,
     "shared_only_committed_inputs" -> True, "constructive_attempt" -> "independent typed producer resolution and defining-equation construction",
     "constructive_attempt_nonempty" -> True, "attempt_records" -> attempts, "candidate_schema_pinned" -> <|"type" -> requiredType, "dimensions" -> dimensions|>,
     "candidate_typecheck" -> typecheck, "candidate_is_well_typed" -> False, "terminal" -> "CONSTRUCTIVE_FAIL(" <> kind <> ")",
     "kind" -> kind, "dual_engine_certificate_pending_comparator" -> True|>|>
];
noetherOpen = Lookup[Select[noether, StringStartsQ[#["status"], "UNRESOLVED"] &], "id"];
datumRecords = Map[Function[slot, base = slotBase[slot]; op = slotAxis[slot, "operator_branch"]; endpoint = slotAxis[slot, "endpoint"]; Which[
 base === "full_action_second_variation", derivedDatum[slot, "symmetric_bilinear_form_on_full_committed_field_jet", "action_density/field^2 blockwise", "complete_action_second_variation"],
 base === "operator_hessian_block", opRow = operatorIndex[op]; If[StringStartsQ[opRow["operator_fourier"], "UNRESOLVED"], unresolvedDatum[slot, "linearized_native_operator_block", "action_density/field^2 blockwise", "authority_census_producer_absence", op <> "_native_functional_second_variation", "missing_input_leaf", opRow["status"]], derivedDatum[slot, "linearized_native_operator_block", "action_density/field^2 blockwise", "operator_inventory::" <> op]],
 base === "native_mass_current_law", derivedDatum[slot, "co-moving_mass_current_4-vector", "mass/(time*area_3)", "current_derivations.sectors.mass"],
 base === "native_energy_current_law", unresolvedDatum[slot, "co-moving_energy_current_4-vector", "energy/(time*area_3)", "authority_census_producer_absence", "native_energy_currents_for_OPEN_action_blocks", "missing_input_leaf", StringRiffle[noetherOpen, ","]],
 StringStartsQ[base, "integrated_"], sectorNameV48 = StringReplace[base, {"integrated_" -> "", "_balance_identity" -> ""}]; unresolvedDatum[slot, "complete_" <> sectorNameV48 <> "_Reynolds_balance_identity", "sector_storage_rate", "authority_census_producer_absence", "complete_" <> sectorNameV48 <> "_typed_boundary_and_source_functionals", "missing_input_leaf", balances["sectors"][sectorNameV48]["status"]],
 KeyExistsQ[reservedProducers, base], unresolvedDatum[slot, "approved_frozen_7.0_ledger_entry", "slot-specific", "authority_census_producer_absence", reservedProducers[base], If[base === "return_energy_closure", "dimensioned_branch_type", "missing_input_leaf"], "non-operative directive candidates excluded from census and challenge PASS"],
 base === "causal_retarded_definition", derivedDatum[slot, "causal_boundary_condition_definition", "dimensionless prescription", "causal_definition"],
 base === "native_noether_flux", nrow = noetherIndex[op]; If[StringStartsQ[nrow["status"], "DERIVED_FROM"], derivedDatum[slot, "native_energy_momentum_flux_tensor", "action-derived sector dimensions", "native_noether_derivations::" <> op], unresolvedDatum[slot, "native_energy_momentum_flux_tensor", "action-derived sector dimensions", "authority_census_producer_absence", op <> "_native_action_functional_derivatives", "missing_input_leaf", nrow["status"]]],
 base === "retarded_green_operator", greenRow = SelectFirst[resolventCells, #["cell"] === op <> "|" <> endpoint &]["retarded_green_operator"]; If[greenRow["representation"] =!= Null && ! StringContainsQ[greenRow["status"], "UNRESOLVED"], derivedDatum[slot, "native_retarded_resolvent_distribution", "inverse native operator", "endpoint_resolvent_cells::" <> op <> "|" <> endpoint], kind = If[StringContainsQ[ToLowerCase[greenRow["status"]], "domain"] || MemberQ[{"gnls_density_phase", "wall_chi_u_coupled"}, op], "operator_domain_well_posedness_failure", "authority_census_producer_absence"]; unresolvedDatum[slot, "native_retarded_resolvent_distribution", "inverse native operator", kind, greenRow["status"], If[kind === "operator_domain_well_posedness_failure", "domain/BC completion", "missing_input_leaf"], greenRow["status"]]],
 StringStartsQ[base, "functional_"], unresolvedDatum[slot, base, "operator/test-space dependent", "authority_census_producer_absence", "native_IR_" <> base, "missing_input_leaf", SelectFirst[functional, #["cell"] === op <> "|" <> endpoint &]["status"]],
 MemberQ[{"trajectory_frequency_representation", "fourier_convention", "retained_local_kernel_definition", "zero_denominator_policy"}, base], derivedDatum[slot, "directive_frozen_definition", "definition-specific", <|"trajectory_frequency_representation" -> "trajectory_representation", "fourier_convention" -> "fourier_convention", "retained_local_kernel_definition" -> "validity_domain_construction.retained_local_kernel_definition", "zero_denominator_policy" -> "validity_domain_construction.zero_denominator_policy"|>[base]],
 base === "truncation_frequency_variable", derivedDatum[slot, "dimensionless_frequency_variable", "dimensionless", "validity_domain_construction.frequency_variable"],
 base === "complete_comoving_restriction_map", unresolvedDatum[slot, "simultaneous_base_state_restriction_map", "field/coefficient typed", "authority_census_producer_absence", "complete_moduli_fixed_base_field_map", "missing_selector", restriction["status"]],
 base === "ownership_current_improvement_relation", unresolvedDatum[slot, "antisymmetric_current_superpotential_relation", "current density", "authority_census_producer_absence", "typed_current_improvement_superpotential", "missing_selector", ownership["status"]],
 True, fail["B2_S0_DISPOSITION_FLOOR", slot]
]], datumSlots];
require[Lookup[datumRecords, "slot"] === datumSlots && And @@ (MemberQ[{"DERIVED", "UNRESOLVED"}, #["disposition_candidate"]] & /@ datumRecords), "B2_S0_DISPOSITION_FLOOR", "expected/reachable exactly-one disposition"];
producerMap = Map[<|"slot" -> #["slot"], "rule" -> #["producer_rule"], "producers" -> #["producer_ids"]|> &, datumRecords];
datumBank = <|"directive_version" -> 48, "expected_slots" -> datumSlots, "reachable_slots" -> Lookup[datumRecords, "slot"], "expected_reachable_exact_set_equal" -> True, "record_count" -> Length[datumRecords], "directive_generated_producer_map" -> producerMap, "directive_generated_producer_map_sha256" -> digestObject[producerMap], "committed_input_closure_inventory" -> closureInventory, "committed_input_closure_inventory_sha256" -> digestObject[closureInventory], "records" -> datumRecords|>;

(* Independently expand every v48 full-key and stage-0 datum product. *)
require[schema["schema_version"] === "U1_PHASE_B2_V48_OBLIGATION_SCHEMA_V3" && schema["directive_version"] === 48, "B2_S0_OBLIGATIONS", "frozen schema"];
axes = schema["axes"]; branches = Sort[operators[[All, "id"]]]; pairs = (#[[1]] <> "__PAIR__" <> #[[2]] &) /@ Subsets[branches, {2}]; axes = Join[axes, <|"operator_branch" -> branches, "unordered_operator_pair" -> pairs|>];
expanded = schema["fixed_products"]; categoryCounts = <||>;
Scan[Function[spec, tuples = Tuples[Lookup[axes, spec["axes"]]]; records = Map[Function[tuple, spec["name"] <> "|" <> StringRiffle[MapThread[#1 <> "=" <> ToString[#2] &, {spec["axes"], tuple}], "|"]], tuples]; expanded = Join[expanded, records]; AssociateTo[categoryCounts, spec["name"] -> Length[records]]], schema["expanded_products"]];
dispositionBySlot = Association@Table[row["slot"] -> row["disposition_candidate"], {row, datumRecords}];
require[Sort[Keys[dispositionBySlot]] === Sort[datumBank["expected_slots"]], "B2_S0_DISPOSITION_FLOOR", "datum record set"];
Scan[Function[slot, AppendTo[expanded, "stage0_datum|slot=" <> slot <> "|disposition=" <> dispositionBySlot[slot]]], datumBank["expected_slots"]];
AssociateTo[categoryCounts, "stage0_datum" -> Length[datumBank["expected_slots"]]];
expanded = Sort[DeleteDuplicates[expanded]];
Scan[Function[name, require[Lookup[categoryCounts, name, 0] >= Length[branches], "B2_S0_OBLIGATIONS", "per-branch:" <> name]], schema["required_category_coverage"]["per_branch"]];
Scan[Function[name, require[Lookup[categoryCounts, name, 0] >= Length[pairs], "B2_S0_OBLIGATIONS", "per-pair:" <> name]], schema["required_category_coverage"]["per_unordered_pair"]];
require[SubsetQ[schema["fixed_products"], schema["required_category_coverage"]["splitters"]], "B2_S0_OBLIGATIONS", "splitter floor"];
obligations = <|"generator" -> "Wolfram Tuples/Subsets expansion of independently frozen v48 full-key and stage0-datum schema", "schema_version" -> schema["schema_version"], "schema_sha256" -> sha[schemaPath], "fixed_products" -> Sort[schema["fixed_products"]], "expanded_records" -> expanded, "expanded_record_count" -> Length[expanded], "expanded_record_set_sha256" -> digestObject[expanded], "category_counts" -> categoryCounts, "grid_axes" -> axes, "p_slices" -> axes["p_slice"], "stage0_datum_slots" -> datumBank["expected_slots"], "stage0_datum_disposition_candidates" -> dispositionBySlot, "fixture_only_g9_tolerance" -> schema["fixture_only_g9_tolerance"]|>;

trajectory = <|"steady" -> "Phi_0(x-X_0-V*t,p;cell), finite V retained", "accelerating" -> "native source J_cell[Phi_0(x-X(t),p(t))] acted on by the dimensional endpoint Green operator", "frequency" -> "qhat_B(omega), d_t -> -I*omega", "collective_indices" -> {"X_x", "X_y", "X_z", "p_x", "p_y", "p_z"}|>;
validity = <|"inventory" -> {"a>0", "ambient-subtracted R/a->infinity", "co-moving-steady base", "UNRESOLVED(endpoint-compatible test space/topology)", "retarded/outgoing support"}, "maximality_rule" -> "intersection of committed conditions only", "committed_frequency_band_present" -> False, "functional_status" -> "UNRESOLVED(native_IR_test_space,native_IR_topology,native_IR_operator_norm,native_IR_contact_subtraction_set)", "frequency_variable" -> "what=omega*a/sqrt(5*K_EOS*rho_inf**4/m_GNLS)", "retained_local_kernel_definition" -> "polynomial-in-omega content of K_var+K_flux+K_constraint+K_Rayleigh after five-channel assembly", "zero_denominator_policy" -> "N=0,E_total=0 -> LOCAL_VALID(trivial); N=0,E_total!=0 -> memory kernel; isolated zeros use limsup", "bandless_truncation_rule" -> "E_total identically zero -> LOCAL_VALID(trivial/exact); otherwise retain memory kernel"|>;
checkNames = {"B2_S0_ACTION_PARSE", "B2_S0_ACTION_HESSIAN", "B2_S0_OPERATOR_INCIDENCE", "B2_S0_BRANE_NORMALIZATION", "B2_S0_NATIVE_NOETHER", "B2_S0_U1_CURRENT", "B2_S0_COMOVING", "B2_S0_BALANCE_HONEST_EXIT", "B2_S0_BALANCE_SLOTS", "B2_S0_G9_ROUTER", "B2_S0_RESOLVENT", "B2_S0_NATIVE_CONTROL", "B2_S0_RESTRICTION", "B2_S0_OWNERSHIP", "B2_S0_WHITELIST", "B2_S0_DISPOSITION_FLOOR", "B2_S0_UNAVAILABILITY_WITNESS", "B2_S0_OBLIGATIONS"}; checks = AssociationMap["PASS" &, checkNames];
routeSeparation = <|"source_parser_ir" -> "Wolfram ToExpression after an explicit external-symbol rewrite", "operator_ir" -> "action-root variation-target table then Graph ConnectedComponents", "balance_route_A_ir" -> "native tensor/current coordinate pullback followed by Reynolds transport and explicit missing-root exit", "balance_route_B_ir" -> "authenticated typed-root census and independent solvability attempt", "resolvent_ir" -> "fundamental-solution Wronskian construction followed by serialized jump algebra", "ownership_ir" -> "actual native candidate-current comparison with typed-superpotential census", "shared_derivation_helpers" -> {}|>;
artifact = <|"schema_version" -> "U1_PHASE_B2_STAGE0_ENGINE_V6", "status" -> "ENGINE_DERIVED", "engine" -> "Mathematica", "independent_representation" -> "Wolfram variation-target graph + epsilon coefficient second variation + direct tensor Reynolds attempt + serialized Wronskian jump algebra", "input_sha256" -> sha[inputPath], "source_digests" -> <|"phase_a_inputs" -> sha[phasePath], "phase_b1_inputs" -> sha[mechanicsPath], "b1_artifact" -> sha[b1Path], "directive" -> sha[directivePath], "v48_obligation_schema" -> sha[schemaPath]|>, "causal_definition" -> config["causal_definition"], "fourier_convention" -> config["fourier_convention"], "complete_action_second_variation" -> completeSecondVariation, "operator_inventory" -> operators, "operator_action_incidence" -> incidence, "operator_action_incidence_residual" -> {}, "native_noether_derivations" -> noether, "current_derivations" -> currents, "integrated_balance_identities" -> balances, "endpoint_resolvent_cells" -> resolventCells, "functional_analytic_test_data" -> functional, "green_sensitivity_matrix" -> sensitivity, "restriction_map" -> restriction, "ownership_convention" -> ownership, "stage0_datum_bank" -> datumBank, "shared_input_whitelist" -> shared, "minimum_obligation_floor" -> obligations, "route_separation" -> routeSeparation, "trajectory_representation" -> trajectory, "validity_domain_construction" -> validity, "checks" -> checks|>;
AssociateTo[artifact, "semantic_payload_sha256" -> digestObject[artifact]];
If[MemberQ[$ScriptCommandLine, "--mutation-projection"], floorProjection = KeyDrop[artifact["minimum_obligation_floor"], "expanded_records"]; artifact = Join[KeyTake[artifact, {"schema_version", "status", "engine", "operator_inventory", "native_noether_derivations", "current_derivations"}], <|"minimum_obligation_floor" -> floorProjection, "mutation_projection" -> "full production derivation/assertions executed; unchanged bulk evidence omitted only after computation"|>]];
If[! DirectoryQ[DirectoryName[outputPath]], CreateDirectory[DirectoryName[outputPath], CreateIntermediateDirectories -> True]];
Export[outputPath, artifact, "YAML"];
Print["B2_STAGE0_MATHEMATICA: PASS operators=" <> ToString[Length[operators]] <> " resolvent_cells=" <> ToString[Length[resolventCells]]];
Exit[0];
