(**
  4D -> preliminary 2PN support-minus-closure throat EFT
  ------------------------------------------------------
  Purpose:
    Convert the solved 2PN conservative cross sector into the first explicit
    low-frequency local throat-response module.

  Main structural result proved here:
    (1) the frozen 1PN wake is an odd dipole overlap;
    (2) its full added 2PN odd block is generated by kinetic + potential
        dressing of those odd dipole channels;
    (3) the genuinely new even P0⊕P2 sector factorizes exactly into
          - six positive support channels, and
          - one pure-U negative geometry/closure channel;
    (4) the whole added conservative 2PN cross block is therefore the on-shell
        result of a minimal signed auxiliary-channel EFT.

  Interpretation:
    The mouth/operator part can stay positive/passive.  The only indefinite
    direction is a pure potential closure channel, which is naturally assigned
    to the geometry-energy side of the throat story.
**)

ClearAll["Global`*"];
Print["--- 4D preliminary 2PN support-minus-closure throat EFT ---"];

passCount = 0;
failCount = 0;
section[name_String] := Print["\n=== ", name, " ==="];
pass[name_String] := (passCount++; Print["PASS: ", name]);
fail[name_String, res_] := (failCount++; Print["FAIL: ", name, "\n  residual -> ", res]);
info[msg_String] := Print["INFO: ", msg];

zeroScalarQ[expr_, assum_: True] := Module[{res},
  res = Quiet @ FullSimplify[expr, assum];
  TrueQ[res === 0] || TrueQ[Quiet @ FullSimplify[res == 0, assum]]
];
checkScalar[name_String, expr_, assum_: True] := Module[{res},
  res = Quiet @ FullSimplify[expr, assum];
  If[zeroScalarQ[expr, assum], pass[name], fail[name, res]]
];
checkEqScalar[name_String, lhs_, rhs_, assum_: True] := checkScalar[name, lhs - rhs, assum];
checkMatrix[name_String, lhs_, rhs_, assum_: True] := Module[{res},
  res = Quiet @ FullSimplify[lhs - rhs, assum];
  If[And @@ Flatten[Map[zeroScalarQ[#, assum] &, res, {2}]], pass[name], fail[name, res]]
];

positiveAssumptions = Gconst > 0 && cLight > 0 && mA > 0 && mB > 0 && rAB > 0;

(* ---------------------------------------------------------------------- *)
section["MASTER / component kinematics and solved targets"];
(* ---------------------------------------------------------------------- *)

vA2 = Expand[vAx^2 + vAy^2 + vAz^2];
vB2 = Expand[vBx^2 + vBy^2 + vBz^2];
vAB = Expand[vAx vBx + vAy vBy + vAz vBz];

dA = vAz;
dB = vBz;

UA = Expand[Gconst mB/rAB];
UB = Expand[Gconst mA/rAB];

L1WakeTarget = Expand[-(7/2) vAB - (1/2) dA dB];

QuarticTarget = Expand[
  -(7/4) vAB (vA2 + vB2)
  - (1/4) dA dB (vA2 + vB2)
  + (11/8) vA2 vB2
  + (1/4) vAB^2
  - (5/8) (vA2 dB^2 + vB2 dA^2)
  + (3/2) vAB dA dB
  + (3/8) dA^2 dB^2
];

QuadraticTarget = Expand[
  (11/8) (mA vA2 + mB vB2)
  - (15/4) (mA + mB) vAB
  + (15/8) (mA dA^2 + mB dB^2)
];

AddedCrossTarget = Expand[
  (Gconst mA mB)/(cLight^4 rAB) QuarticTarget
  + (Gconst^2 mA mB)/(cLight^4 rAB^2) QuadraticTarget
  + 5 Gconst^3 mA^2 mB^2/(4 cLight^4 rAB^3)
];

(* ---------------------------------------------------------------------- *)
section["1PN / frozen wake as odd dipole channels"];
(* ---------------------------------------------------------------------- *)

DipA = {
  Sqrt[7/2] vAx,
  Sqrt[7/2] vAy,
  2 dA
};
DipB = {
  Sqrt[7/2] vBx,
  Sqrt[7/2] vBy,
  2 dB
};

L1WakeDipole = Expand[-(DipA.DipB)];

checkEqScalar[
  "The frozen 1PN wake is exactly an odd dipole overlap",
  L1WakeDipole,
  L1WakeTarget,
  positiveAssumptions
];

LegDressedOdd = Expand[(1/2) (vA2 + vB2) L1WakeDipole];

(* ---------------------------------------------------------------------- *)
section["2PN / even P0⊕P2 block in mouth-port language"];
(* ---------------------------------------------------------------------- *)

Pi0A = Expand[Sqrt[5] vA2/2];
Pi0B = Expand[Sqrt[5] vB2/2];

Pi20A = Expand[(3 dA^2 - vA2)/2];
Pi20B = Expand[(3 dB^2 - vB2)/2];

Pi21A = {
  Sqrt[2] dA vAx,
  Sqrt[2] dA vAy
};
Pi21B = {
  Sqrt[2] dB vBx,
  Sqrt[2] dB vBy
};

Pi22A = {
  (vAx^2 - vAy^2)/(2 Sqrt[2]),
  (2 vAx vAy)/(2 Sqrt[2])
};
Pi22B = {
  (vBx^2 - vBy^2)/(2 Sqrt[2]),
  (2 vBx vBy)/(2 Sqrt[2])
};

QuarticResidual = Expand[QuarticTarget - LegDressedOdd];
PortQuartic = Expand[
  Pi0A Pi0B
  + Pi20A Pi20B
  + Pi21A.Pi21B
  + Pi22A.Pi22B
];

checkEqScalar[
  "The new quartic residual is exactly the positive P0⊕P2 port overlap",
  PortQuartic,
  QuarticResidual,
  positiveAssumptions
];

J0 = 4/Sqrt[5];
J20 = 5/4;
StaticCross = 5/4;

OddAddedTarget = Expand[LegDressedOdd - (15/4) (UA + UB) vAB];
EvenBlockTarget = Expand[
  PortQuartic
  + UA (J0 Pi0B + J20 Pi20B)
  + UB (J0 Pi0A + J20 Pi20A)
  + StaticCross UA UB
];

(* ---------------------------------------------------------------------- *)
section["ODD / kinetic and potential dressing of the dipole wake"];
(* ---------------------------------------------------------------------- *)

etaPerp = 15/14;
etaPara = 15/16;
lam = Unique["lam"];

DipAEffective = {
  (1 + lam ((1/2) vA2 + etaPerp UA)) Sqrt[7/2] vAx,
  (1 + lam ((1/2) vA2 + etaPerp UA)) Sqrt[7/2] vAy,
  (1 + lam ((1/2) vA2 + etaPara UA)) 2 dA
};
DipBEffective = {
  (1 + lam ((1/2) vB2 + etaPerp UB)) Sqrt[7/2] vBx,
  (1 + lam ((1/2) vB2 + etaPerp UB)) Sqrt[7/2] vBy,
  (1 + lam ((1/2) vB2 + etaPara UB)) 2 dB
};

OddCrossLam = Expand[-(DipAEffective.DipBEffective)];
OddAddedFromDressing = Expand[Coefficient[OddCrossLam, lam, 1]];

checkEqScalar[
  "Odd dipole kinetic+potential dressing reproduces the full added odd 2PN block",
  OddAddedFromDressing,
  OddAddedTarget,
  positiveAssumptions
];

(* ---------------------------------------------------------------------- *)
section["MATRIX / exact support-minus-closure decomposition"];
(* ---------------------------------------------------------------------- *)

Meven = {
  {1, 0, 0, 0, 0, 0, J0},
  {0, 1, 0, 0, 0, 0, J20},
  {0, 0, 1, 0, 0, 0, 0},
  {0, 0, 0, 1, 0, 0, 0},
  {0, 0, 0, 0, 1, 0, 0},
  {0, 0, 0, 0, 0, 1, 0},
  {J0, J20, 0, 0, 0, 0, StaticCross}
};

ClosureDeficit = FullSimplify[J0^2 + J20^2 - StaticCross, positiveAssumptions];
checkEqScalar[
  "Closure deficit is exactly 281/80",
  ClosureDeficit,
  281/80,
  positiveAssumptions
];

Rsupport = {
  {1, 0, 0, 0, 0, 0, J0},
  {0, 1, 0, 0, 0, 0, J20},
  {0, 0, 1, 0, 0, 0, 0},
  {0, 0, 0, 1, 0, 0, 0},
  {0, 0, 0, 0, 1, 0, 0},
  {0, 0, 0, 0, 0, 1, 0}
};
Rgeom = {{0, 0, 0, 0, 0, 0, Sqrt[ClosureDeficit]}};

SupportMatrix = FullSimplify[Transpose[Rsupport].Rsupport, positiveAssumptions];
GeometryMatrix = FullSimplify[Transpose[Rgeom].Rgeom, positiveAssumptions];

checkMatrix[
  "Exact even response matrix = support PSD block minus pure-U geometry block",
  SupportMatrix - GeometryMatrix,
  Meven,
  positiveAssumptions
];

ScalarBlock = Meven[[{1, 2, 7}, {1, 2, 7}]];
checkEqScalar[
  "The scalar {P0,P20,U} block has determinant -281/80",
  Det[ScalarBlock],
  -281/80,
  positiveAssumptions
];

checkMatrix[
  "The pure geometry closure block lives entirely in the U direction",
  GeometryMatrix,
  {{0, 0, 0, 0, 0, 0, 0},
   {0, 0, 0, 0, 0, 0, 0},
   {0, 0, 0, 0, 0, 0, 0},
   {0, 0, 0, 0, 0, 0, 0},
   {0, 0, 0, 0, 0, 0, 0},
   {0, 0, 0, 0, 0, 0, 0},
   {0, 0, 0, 0, 0, 0, ClosureDeficit}},
  positiveAssumptions
];

(* ---------------------------------------------------------------------- *)
section["CHANNELS / support and closure sources"];
(* ---------------------------------------------------------------------- *)

SupportA = {
  Expand[Pi0A + J0 UA],
  Expand[Pi20A + J20 UA],
  Pi21A[[1]],
  Pi21A[[2]],
  Pi22A[[1]],
  Pi22A[[2]]
};
SupportB = {
  Expand[Pi0B + J0 UB],
  Expand[Pi20B + J20 UB],
  Pi21B[[1]],
  Pi21B[[2]],
  Pi22B[[1]],
  Pi22B[[2]]
};

ClosureA = Expand[Sqrt[ClosureDeficit] UA];
ClosureB = Expand[Sqrt[ClosureDeficit] UB];

EvenSupportMinusClosure = Expand[SupportA.SupportB - ClosureA ClosureB];

checkEqScalar[
  "Even block = six positive support channels minus one pure-U closure channel",
  EvenSupportMinusClosure,
  EvenBlockTarget,
  positiveAssumptions
];

(* ---------------------------------------------------------------------- *)
section["AUXILIARY / generic low-frequency elimination identities"];
(* ---------------------------------------------------------------------- *)

Clear[q, SA, SB];
LsupportAux = -1/2 q^2 + q (SA + SB);
qStar = q /. First[Solve[D[LsupportAux, q] == 0, q]];
LsupportOnShell = Expand[LsupportAux /. q -> qStar];
checkEqScalar[
  "Positive support auxiliary produces +SA SB cross term",
  LsupportOnShell,
  Expand[(1/2) SA^2 + SA SB + (1/2) SB^2],
  positiveAssumptions
];

Clear[g, CA, CB];
LgeomAux = 1/2 g^2 + g (CA + CB);
gStar = g /. First[Solve[D[LgeomAux, g] == 0, g]];
LgeomOnShell = Expand[LgeomAux /. g -> gStar];
checkEqScalar[
  "Wrong-sign geometry auxiliary produces -CA CB cross term",
  LgeomOnShell,
  Expand[-(1/2) CA^2 - CA CB - (1/2) CB^2],
  positiveAssumptions
];

Clear[d, DA, DB];
LoddAux = -1/2 d^2 + d (DA - DB);
dStar = d /. First[Solve[D[LoddAux, d] == 0, d]];
LoddOnShell = Expand[LoddAux /. d -> dStar];
checkEqScalar[
  "Odd dipole auxiliary produces -DA DB cross term",
  LoddOnShell,
  Expand[(1/2) DA^2 - DA DB + (1/2) DB^2],
  positiveAssumptions
];

(* ---------------------------------------------------------------------- *)
section["ASSEMBLY / full added conservative 2PN cross block"];
(* ---------------------------------------------------------------------- *)

AddedCrossSupportClosure = Expand[
  (Gconst mA mB)/(cLight^4 rAB)
  (OddAddedFromDressing + EvenSupportMinusClosure)
];

checkEqScalar[
  "Full added conservative 2PN cross block equals dressed odd dipole wake plus support-minus-closure even sector",
  AddedCrossSupportClosure,
  AddedCrossTarget,
  positiveAssumptions
];

(* Export symbols for later integration into the full 2PN assembly. *)
Port2PNOddAddedFromDressing = OddAddedFromDressing;
Port2PNEvenSupportChannelsA = SupportA;
Port2PNEvenSupportChannelsB = SupportB;
Port2PNClosureChannelA = ClosureA;
Port2PNClosureChannelB = ClosureB;
Port2PNEvenSupportMinusClosure = EvenSupportMinusClosure;
Port2PNSupportMatrix = SupportMatrix;
Port2PNGeometryMatrix = GeometryMatrix;
Port2PNClosureDeficit = ClosureDeficit;
Port2PNAddedCrossSupportClosure = AddedCrossSupportClosure;

section["SUMMARY"];
Print["Pass count = ", passCount, ", Fail count = ", failCount];
If[failCount == 0,
  Print["All support-minus-closure throat EFT checks passed."],
  Print["Some support-minus-closure throat EFT checks failed."]
];

(*"
Output:

--- 4D preliminary 2PN support-minus-closure throat EFT ---

=== MASTER / component kinematics and solved targets ===

=== 1PN / frozen wake as odd dipole channels ===
PASS: The frozen 1PN wake is exactly an odd dipole overlap

=== 2PN / even P0⊕P2 block in mouth-port language ===
PASS: The new quartic residual is exactly the positive P0⊕P2 port overlap

=== ODD / kinetic and potential dressing of the dipole wake ===
PASS: Odd dipole kinetic+potential dressing reproduces the full added odd 2PN block

=== MATRIX / exact support-minus-closure decomposition ===
PASS: Closure deficit is exactly 281/80
PASS: Exact even response matrix = support PSD block minus pure-U geometry block
PASS: The scalar {P0,P20,U} block has determinant -281/80
PASS: The pure geometry closure block lives entirely in the U direction

=== CHANNELS / support and closure sources ===
PASS: Even block = six positive support channels minus one pure-U closure channel

=== AUXILIARY / generic low-frequency elimination identities ===
PASS: Positive support auxiliary produces +SA SB cross term
PASS: Wrong-sign geometry auxiliary produces -CA CB cross term
PASS: Odd dipole auxiliary produces -DA DB cross term

=== ASSEMBLY / full added conservative 2PN cross block ===
PASS: Full added conservative 2PN cross block equals dressed odd dipole wake plus support-minus-closure even sector

=== SUMMARY ===
Pass count = 12, Fail count = 0
All support-minus-closure throat EFT checks passed.
"*)
