import sympy as sp
W0, eta, sigma, L_W, mu_R = sp.symbols('W_0 eta_bg sigma_W L_W mu_R')
w1, w1d1, w1d11 = sp.symbols('w1_profile w1_profile_d1 w1_profile_d1d1')
m1d1 = sp.symbols('m1_profile_d1')
print('ZERO_JET_DEFINITION =', W0*(1+eta*w1))
print('DIRECTIVE_FIRST_JET =', W0*eta*w1d1)
print('ENGINE_FIRST_JET_PROFILE_GRADE =', sigma*w1d1)
print('FIRST_JET_RESIDUAL_directive_minus_engine =', sp.expand(W0*eta*w1d1 - sigma*w1d1))
print('DIRECTIVE_SECOND_JET =', W0*eta*w1d11)
print('ENGINE_SECOND_JET =', sigma*w1d11/L_W)
print('SECOND_JET_RESIDUAL_directive_minus_engine =', sp.expand(W0*eta*w1d11 - sigma*w1d11/L_W))
print('ENGINE_MU_FIRST_JET =', mu_R*sigma*m1d1/W0)
print('DIRECTIVE_NAMES_MU_R_BG_JETS =', False)
x = sp.symbols('x')
w1F = sp.Function('w1')
Wdef = W0*(1+eta*w1F(x))
print('CONTINUUM_CHAIN_dW_dx =', sp.diff(Wdef, x))
print('NOTE = eta_bg and sigma_W are independent bookkeepers; chain-through-eta is not PROFILE_GRADE_SUBS')
