#!/usr/bin/env python3
"""
moving_throat_pde_stage5_grouped_p2_sympy_audit.py

SymPy audit for the grouped real P2 lift of the Stage-4 Maxwell/mixed bridge.

Scope
-----
This script verifies the next reduced-sector step after the one-lane Maxwell/mixed
prototype:

  • exact conversion from Stage-3/4 conservative operator moments to the normalized
    grouped-response moments used by the 2.5PN package,
  • exact first-order outgoing-prefactor coefficients generated by the conservative
    wall operator and the mixed-sector transfer factor,
  • exact grouped real P2 inverse formulas and isotropy defects,
  • explicit low-frequency N0/N2/N4 formulas for the Stage-4 one-lane mixed-sector
    prototype,
  • the invariant quadrupole normalization product that must hit the 2.5PN target.

This is still a reduced-sector audit. It does not solve the full coupled moving-throat
PDE, but it is the first exact bridge from the Stage-4 internal transfer factor to the
2.5PN grouped-quadrupole normalization language.
"""

from __future__ import annotations

import sympy as sp

I = sp.I


def banner(title: str) -> None:
    line = "=" * 88
    print("\n" + line)
    print(title)
    print(line)


def subbanner(title: str) -> None:
    line = "-" * 88
    print("\n" + line)
    print(title)
    print(line)


def expect_zero(name: str, expr: sp.Expr | sp.Matrix) -> None:
    if isinstance(expr, sp.MatrixBase):
        simplified = expr.applyfunc(lambda z: sp.simplify(sp.expand(z)))
        print(f"{name} =")
        sp.pprint(simplified)
        if any(entry != 0 for entry in simplified):
            raise AssertionError(f"{name} is not zero")
    else:
        simplified = sp.simplify(sp.expand(expr))
        print(f"{name} = {simplified}")
        if simplified != 0:
            raise AssertionError(f"{name} is not zero")


# ---------------------------------------------------------------------------
# I. Operator-normalized -> response-normalized grouped moments
# ---------------------------------------------------------------------------

def operator_to_response_bridge() -> dict[str, sp.Expr]:
    banner("SECTION I — CONSERVATIVE OPERATOR MOMENTS TO GROUPED RESPONSE MOMENTS")

    omega = sp.symbols("omega", real=True)
    D0, D2, D4 = sp.symbols("D0 D2 D4", nonzero=True, real=True)

    Dcons = D0 + D2 * omega**2 + D4 * omega**4
    Yresp = sp.expand(sp.series(D0 / Dcons, omega, 0, 6).removeO())
    u2 = sp.simplify(Yresp.coeff(omega, 2))
    u4 = sp.simplify(Yresp.coeff(omega, 4))

    subbanner("I.1 — Exact normalized-response coefficients")
    print("Y_resp(ω) = D0 / D_cons(ω) =")
    sp.pprint(Yresp)

    expect_zero("u2 formula", u2 + D2 / D0)
    expect_zero("u4 formula", u4 - (D2**2 - D0 * D4) / D0**2)

    print("u2 =")
    sp.pprint(u2)
    print("u4 =")
    sp.pprint(u4)

    return {"u2": u2, "u4": u4}


# ---------------------------------------------------------------------------
# II. Outgoing prefactor and branch coefficients
# ---------------------------------------------------------------------------

def outgoing_prefactor_bridge() -> dict[str, sp.Expr]:
    banner("SECTION II — OUTGOING PREFACTOR AND BRANCH COEFFICIENTS")

    omega = sp.symbols("omega", real=True)
    D0, D2, D4 = sp.symbols("D0 D2 D4", nonzero=True, real=True)
    N0, N2, N4 = sp.symbols("N0 N2 N4", real=True)
    A, B, G5 = sp.symbols("A B G5", real=True)

    Dcons = D0 + D2 * omega**2 + D4 * omega**4
    Nfac = N0 + N2 * omega**2 + N4 * omega**4
    Pref = sp.expand(sp.series(D0 * Nfac / Dcons**2, omega, 0, 6).removeO())
    P0 = sp.simplify(Pref.coeff(omega, 0))
    P2 = sp.simplify(Pref.coeff(omega, 2))
    P4 = sp.simplify(Pref.coeff(omega, 4))

    Y2_out = 1 + A * omega**2 + B * omega**4 + I * G5 * omega**5
    Ybranch = sp.expand(Pref * Y2_out)
    K0 = sp.simplify(Ybranch.coeff(omega, 0))
    K2 = sp.simplify(Ybranch.coeff(omega, 2))
    K4 = sp.simplify(Ybranch.coeff(omega, 4))
    Gamma5 = sp.simplify(Ybranch.coeff(omega, 5) / I)

    subbanner("II.1 — Internal prefactor coefficients")
    expect_zero("P0 formula", P0 - N0 / D0)
    expect_zero("P2 formula", P2 - (D0 * N2 - 2 * D2 * N0) / D0**2)
    expect_zero(
        "P4 formula",
        P4 - (D0**2 * N4 - 2 * D0 * (D2 * N2 + D4 * N0) + 3 * D2**2 * N0) / D0**3,
    )

    print("P0 =")
    sp.pprint(P0)
    print("P2 =")
    sp.pprint(P2)
    print("P4 =")
    sp.pprint(P4)

    subbanner("II.2 — Full branch coefficients after multiplying by the outgoing l=2 fingerprint")
    expect_zero("K0 formula", K0 - P0)
    expect_zero("K2 formula", K2 - (P2 + A * P0))
    expect_zero("K4 formula", K4 - (P4 + A * P2 + B * P0))
    expect_zero("Gamma5 formula", Gamma5 - G5 * P0)

    print("K0 =")
    sp.pprint(K0)
    print("K2 =")
    sp.pprint(K2)
    print("K4 =")
    sp.pprint(K4)
    print("Gamma5 =")
    sp.pprint(Gamma5)

    return {
        "P0": P0,
        "P2": P2,
        "P4": P4,
        "K0": K0,
        "K2": K2,
        "K4": K4,
        "Gamma5": Gamma5,
    }


# ---------------------------------------------------------------------------
# III. Grouped real P2 inverse formulas and isotropy defects
# ---------------------------------------------------------------------------

def grouped_p2_inverse_map() -> None:
    banner("SECTION III — GROUPED REAL P2 INVERSE FORMULAS AND ISOTROPY DEFECTS")

    x20, x21, x22 = sp.symbols("x20 x21 x22", real=True)
    xbar, ax, bx = sp.symbols("xbar ax bx", real=True)

    xbar_expr = sp.simplify((x20 + 2 * x21 + 2 * x22) / 5)
    ax_expr = sp.simplify((2 * x20 - x21 - x22) / 10)
    bx_expr = sp.simplify((x21 - x22) / 2)

    x20_back = sp.simplify(xbar + 4 * ax)
    x21_back = sp.simplify(xbar - ax + bx)
    x22_back = sp.simplify(xbar - ax - bx)

    subbanner("III.1 — Exact inverse map")
    print("xbar =", xbar_expr)
    print("ax   =", ax_expr)
    print("bx   =", bx_expr)

    expect_zero("x20 recovered", x20_back.subs({xbar: xbar_expr, ax: ax_expr, bx: bx_expr}) - x20)
    expect_zero("x21 recovered", x21_back.subs({xbar: xbar_expr, ax: ax_expr, bx: bx_expr}) - x21)
    expect_zero("x22 recovered", x22_back.subs({xbar: xbar_expr, ax: ax_expr, bx: bx_expr}) - x22)

    A_sq = sp.simplify(4 * ax_expr**2 + sp.Rational(4, 5) * bx_expr**2)
    print("anisotropy norm A^2 =", A_sq)

    subbanner("III.2 — Isotropic branch")
    xQ = sp.symbols("xQ", real=True)
    xbar_iso = sp.simplify(xbar_expr.subs({x20: xQ, x21: xQ, x22: xQ}))
    ax_iso = sp.simplify(ax_expr.subs({x20: xQ, x21: xQ, x22: xQ}))
    bx_iso = sp.simplify(bx_expr.subs({x20: xQ, x21: xQ, x22: xQ}))
    expect_zero("xbar_iso - xQ", xbar_iso - xQ)
    expect_zero("ax_iso", ax_iso)
    expect_zero("bx_iso", bx_iso)

    print("So any grouped triplet with equal lane coefficients has vanishing anisotropy defects.")


# ---------------------------------------------------------------------------
# IV. Stage-4 prototype N0/N2/N4 formulas
# ---------------------------------------------------------------------------

def stage4_prototype_transfer_coefficients() -> dict[str, sp.Expr]:
    banner("SECTION IV — STAGE-4 MIXED-SECTOR PROTOTYPE: EXACT N0/N2/N4")

    omega = sp.symbols("omega", real=True)
    Delta0, S2, P0_proto, gW = sp.symbols("Delta0 S2 P0_proto gW", nonzero=True, real=True)

    Nproto = (P0_proto - gW * omega**2) ** 2 / (Delta0 - S2 * omega**2 + omega**4) ** 2
    Nseries = sp.expand(sp.series(Nproto, omega, 0, 6).removeO())
    N0 = sp.simplify(Nseries.coeff(omega, 0))
    N2 = sp.simplify(Nseries.coeff(omega, 2))
    N4 = sp.simplify(Nseries.coeff(omega, 4))

    subbanner("IV.1 — Abstract one-lane prototype coefficients")
    expect_zero("N0 prototype", N0 - P0_proto**2 / Delta0**2)
    expect_zero("N2 prototype", N2 - 2 * P0_proto * (P0_proto * S2 - Delta0 * gW) / Delta0**3)
    expect_zero(
        "N4 prototype",
        N4 - (Delta0**2 * gW**2 - 2 * Delta0 * P0_proto**2 - 4 * Delta0 * P0_proto * S2 * gW + 3 * P0_proto**2 * S2**2) / Delta0**4,
    )

    print("N0 =")
    sp.pprint(N0)
    print("N2 =")
    sp.pprint(N2)
    print("N4 =")
    sp.pprint(N4)

    subbanner("IV.2 — Dictionary back to the Stage-4 Maxwell/mixed symbols")
    OA, OW, R, gA = sp.symbols("Omega_A Omega_W R g_A", real=True)
    dict_back = {
        Delta0: OA**2 * OW**2 - R**2,
        S2: OA**2 + OW**2,
        P0_proto: OA**2 * gW + R * gA,
    }
    print("Delta0 =")
    sp.pprint(dict_back[Delta0])
    print("S2 =")
    sp.pprint(dict_back[S2])
    print("P0_proto =")
    sp.pprint(dict_back[P0_proto])

    return {"N0": N0, "N2": N2, "N4": N4}


# ---------------------------------------------------------------------------
# V. Quadrupole normalization product and targets
# ---------------------------------------------------------------------------

def quadrupole_normalization_target() -> None:
    banner("SECTION V — QUADRUPOLE NORMALIZATION PRODUCT")

    G, c, c_s, a = sp.symbols("G c c_s a", positive=True, real=True)
    mhat = sp.symbols("mhat", positive=True, real=True)
    P0 = sp.symbols("P0", positive=True, real=True)
    z = sp.symbols("z", positive=True, real=True)

    # Anchor the compact outgoing coefficients to the exact Stage-4 DtN branch
    # rather than retyping the 9/81/27 denominators in this stage.
    j2 = (sp.Rational(3, 1) / z**3 - sp.Rational(1, 1) / z) * sp.sin(z) - 3 * sp.cos(z) / z**2
    y2 = -((sp.Rational(3, 1) / z**3 - sp.Rational(1, 1) / z) * sp.cos(z) + 3 * sp.sin(z) / z**2)
    h2 = sp.simplify(j2 + I * y2)
    Lambda2 = sp.simplify((omega := sp.symbols("omega", real=True)) * sp.diff(h2, z) / h2).subs(z, omega * a / c_s)
    Lambda2_series = sp.series(Lambda2, omega, 0, 7).removeO()
    Y2 = sp.simplify(sp.series(1 / Lambda2_series, omega, 0, 6).removeO())
    Y2_static = sp.simplify(Y2.subs(omega, 0))
    Y2_hat = sp.expand(sp.simplify(Y2 / Y2_static))
    A_stage4 = sp.simplify(Y2_hat.coeff(omega, 2))
    B_stage4 = sp.simplify(Y2_hat.coeff(omega, 4))
    G5_stage4 = sp.simplify(Y2_hat.coeff(omega, 5) / I)

    subbanner("V.1 — Stage-4 outgoing l=2 fingerprint anchor")
    expect_zero("Stage-4 A coefficient", A_stage4 - a**2 / (9 * c_s**2))
    expect_zero("Stage-4 B coefficient", B_stage4 - 4 * a**4 / (81 * c_s**4))
    expect_zero("Stage-4 G5 coefficient", G5_stage4 - a**5 / (27 * c_s**5))
    print("A_stage4 =")
    sp.pprint(A_stage4)
    print("B_stage4 =")
    sp.pprint(B_stage4)
    print("G5_stage4 =")
    sp.pprint(G5_stage4)

    Gamma5_port = G5_stage4
    gamma_GR = sp.simplify(2 * G / (5 * c**5))
    NQ_target = sp.simplify(sp.solve(sp.Eq(mhat**2 * P0 * Gamma5_port, gamma_GR), P0)[0])

    subbanner("V.2 — Invariant product")
    print("Gamma5_port =")
    sp.pprint(Gamma5_port)
    print("gamma_GR =")
    sp.pprint(gamma_GR)
    print("Required invariant product mhat^2 * P0 =")
    sp.pprint(NQ_target)

    expect_zero(
        "mhat=1 target",
        sp.simplify(NQ_target.subs(mhat, 1) - 54 * G * c_s**5 / (5 * a**5 * c**5)),
    )

    subbanner("V.3 — Constant-prefactor branch coefficients")
    K2_target = sp.simplify(NQ_target * A_stage4)
    K4_target = sp.simplify(NQ_target * B_stage4)
    print("If the outgoing branch is carried by a constant isotropic prefactor, then")
    print("K0_target =")
    sp.pprint(NQ_target)
    print("K2_target =")
    sp.pprint(K2_target)
    print("K4_target =")
    sp.pprint(K4_target)

    expect_zero(
        "mhat=1 K2 target",
        sp.simplify(K2_target.subs(mhat, 1) - 6 * G * c_s**3 / (5 * a**3 * c**5)),
    )
    expect_zero(
        "mhat=1 K4 target",
        sp.simplify(K4_target.subs(mhat, 1) - 8 * G * c_s / (15 * a * c**5)),
    )

    print("So the remaining theorem gap is the moving-throat value of the invariant product mhat^2 * P0.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    operator_to_response_bridge()
    outgoing_prefactor_bridge()
    grouped_p2_inverse_map()
    stage4_prototype_transfer_coefficients()
    quadrupole_normalization_target()

    banner("FINAL STAGE-5 LEDGER")
    print("Verified with SymPy:")
    print("  • the Stage-3/4 conservative operator moments convert to the normalized grouped-response moments via")
    print("    u2 = -D2/D0 and u4 = (D2^2 - D0 D4)/D0^2;")
    print("  • the first-order outgoing bridge is controlled by the internal prefactor")
    print("    Pref(ω) = D0 N(ω) / D_cons(ω)^2,")
    print("    whose coefficients are")
    print("    P0 = N0/D0,")
    print("    P2 = (D0 N2 - 2 D2 N0)/D0^2,")
    print("    P4 = (D0^2 N4 - 2 D0(D2 N2 + D4 N0) + 3 D2^2 N0)/D0^3;")
    print("  • multiplying by the outgoing l=2 fingerprint gives the branch coefficients")
    print("    K0 = P0,")
    print("    K2 = P2 + A P0,")
    print("    K4 = P4 + A P2 + B P0,")
    print("    Gamma5 = G5 P0;")
    print("  • the grouped real inverse map and isotropy defects are exact and vanish whenever the three lane coefficients coincide;")
    print("  • for the Stage-4 one-lane Maxwell/mixed prototype, the transfer series coefficients N0, N2, N4 are explicit rational functions of Delta0, S2, P0_proto, and gW;")
    print("  • the 2.5PN target is now the invariant normalization product")
    print("    mhat^2 * P0 = 54 G c_s^5 / (5 a^5 c^5)")
    print("    (or P0 itself when mhat = 1 on the natural source-map branch).")


if __name__ == "__main__":
    main()
