import numpy as np

def vortex_thrust_estimator():
    """
    Estimates the thrust generated by a 'Digital Vortex Cannon' mechanism
    where protons shed vortex rings due to spin/circulation flips.
    """
    print("--- Digital Vortex Thrust Estimator ---")

    # 1. Physical Constants (SI Units)
    m_proton = 1.67e-27  # kg
    c = 3.0e8            # m/s
    a_proton = 0.84e-15  # m (approx charge radius)
    h_bar = 1.05e-34     # J*s

    # 2. Model Parameters (derived from papers)
    # Circulation Gamma:
    # From Free_Space_Lev.md/EM_Fields.tex, flow speed v <= c at the core.
    # v = Gamma / (2*pi*a) <= c  --> Gamma_max = 2*pi*a*c
    Gamma_quantum = 2 * np.pi * a_proton * c

    # Bulk Density rho_0:
    # This is the biggest unknown.
    # Option A: If "Mass" is displaced fluid, M ~ rho_0 * Volume.
    # Volume ~ 4/3 * pi * a^3.
    # rho_0 ~ m_proton / Volume
    Volume = (4.0/3.0) * np.pi * a_proton**3
    rho_nuclear = m_proton / Volume

    # Option B: Parameter from papers (e.g. 1000 kg/m^3 from free_space_lev.md example)
    # But for a proton to be a stable defect, the density must be nuclear-scale or
    # the "mass" parameter M_0 must be consistent.
    # Let's use the 'Nuclear Density' derived from the proton's own mass/size
    # as the most self-consistent 'vacuum density' at that scale.
    rho_0 = rho_nuclear

    print(f"Model Parameters:")
    print(f"  Proton Radius (a): {a_proton:.2e} m")
    print(f"  Vacuum Density (rho_0): {rho_0:.2e} kg/m^3 (Nuclear Scale)")
    print(f"  Circulation Quantum (Gamma): {Gamma_quantum:.2e} m^2/s")
    print("-" * 30)

    # 3. Momentum per Pulse (P_ring)
    # From free_space_lev.md: P_ring = C_P * rho * Gamma * pi * R^2
    # Assume C_P ~ 1, R ~ a (ring is shed from the throat)
    P_ring = 1.0 * rho_0 * Gamma_quantum * np.pi * a_proton**2

    print(f"Momentum per Vortex Ring (P_ring): {P_ring:.2e} kg m/s")

    # Check consistency: Is P_ring ~ m_proton * c?
    # P_ring ~ (m/a^3) * (a*c) * a^2 ~ m*c.
    # Yes. Shedding one ring is like firing the proton at the speed of light.
    # This is HUGE.
    print(f"  (Ratio to m_proton * c: {P_ring / (m_proton * c):.2f})")
    print("-" * 30)

    # 4. Thrust Calculation (F = P_ring * f)
    # We sweep over possible drive frequencies.

    frequencies = {
        "NMR (100 MHz)": 1e8,
        "EPR (100 GHz)": 1e11,
        "THz Gap (1 THz)": 1e12,
        "Optical (1 PHz)": 1e15,
        "Zitterbewegung": 2 * m_proton * c**2 / 6.626e-34 # ~ 2e23 Hz
    }

    print(f"{'Drive Frequency':<20} | {'Thrust (per proton)':<20} | {'Thrust-to-Weight (G)'}")
    print("-" * 75)

    # Weight of one proton
    W_proton = m_proton * 9.81

    results = []

    for name, f in frequencies.items():
        Thrust = P_ring * f
        G_force = Thrust / W_proton
        results.append((name, Thrust, G_force))
        print(f"{name:<20} | {Thrust:<20.2e} N | {G_force:.2e}")

    print("-" * 75)

    # 5. Macroscopic Scaling
    # If we have 1 kg of active material (Hydrogen), how much thrust?
    # N_protons = 1 kg / m_proton
    N_protons = 1.0 / m_proton

    print("\nMacroscopic Thrust (1 kg Hull Plate):")
    for name, Thrust, G in results:
        # Assume some efficiency factor eta (not every proton fires every cycle)
        # Let's be conservative: eta = 1%
        eta = 0.01
        Total_Thrust = Thrust * N_protons * eta
        print(f"  At {name} (1% efficiency): {Total_Thrust:.2e} N")

if __name__ == "__main__":
    vortex_thrust_estimator()
