(* Ledger stage035 Mathematica audit: native source law and parity census.

   Standalone, print-only, assert-zero, exact, and file-I/O-free.

   Independent route: this engine builds an explicit normalized Gaussian
   mouth profile with time-dependent centers, forms D[sigma,t] + Div[...]
   directly, and uses Reduce for the unique coefficient.  Its parity census
   is generated by explicit reflection/time operators on formal monomials,
   while polar versus axial type is classified by Matrix/Det/Cross
   transformation tests.  This is materially distinct from the SymPy
   abstract-profile derivative identity and multiplicative Parity objects.

   Tooth-local runtime ablation uses LEDGER_STAGE035_MUTATION.
*)

ClearAll["Global`*"];

passCount = 0;
failCount = 0;
mutationEnvironment = "LEDGER_STAGE035_MUTATION";
activeMutation = Environment[mutationEnvironment];
If[!StringQ[activeMutation], activeMutation = ""];
activeMutation = StringTrim[activeMutation];

verdictToken = "CONVECTION_LIKE_CONDITIONAL";
r1SourceToken = "R1_SOURCE_BASIS";
parityBadToken = "PARITY_INCONSISTENT";
magnitudeR1 = "R1(magnitude)";
manifestDigestExpected =
  "d85de3d8f6b7d615900c8ead24f1589eed3c681e74cf546adb999f2cc7fa5b36";

toothOrder = {
  "SOURCE_TRANSLATION_CONTINUITY",
  "SOURCE_NOT_IMPORTED",
  "SOURCE_BASIS",
  "PARITY_RW",
  "PARITY_PW",
  "PARITY_ROTATION",
  "PARITY_TIME_REVERSAL",
  "TARGET_BLINDNESS",
  "DUAL_ENGINE_TERMS",
  "UNITS_RESTORED",
  "VERDICT_REDERIVATION",
  "SOURCE_TO_STAGE_MANIFEST"
};

ablationDescriptions = <|
  "SOURCE_TRANSLATION_CONTINUITY" ->
    "select alpha=2 in the directly differentiated continuity residual",
  "SOURCE_NOT_IMPORTED" ->
    "inject code-native barred symbol Nu into the computed source vector",
  "SOURCE_BASIS" ->
    "double the computed source before component-wise basis reduction",
  "PARITY_RW" ->
    "make the response generator R_w-odd before applying reflection operators",
  "PARITY_PW" ->
    "make the response generator P_w-odd before applying reflection operators",
  "PARITY_ROTATION" ->
    "make the gradient transform axially so Cross classifies b_T as polar",
  "PARITY_TIME_REVERSAL" ->
    "make the active-drain generator tau_d T-even",
  "TARGET_BLINDNESS" ->
    "inject electric A_E into the live source-side dependency expression",
  "DUAL_ENGINE_TERMS" ->
    "drop q_T_relation from the computed stage term inventory",
  "UNITS_RESTORED" ->
    "change [q_T] from M T^-1 to M L T^-1 in formal source rescaling",
  "VERDICT_REDERIVATION" ->
    "select alpha=2 only in the verdict's upstream continuity object",
  "SOURCE_TO_STAGE_MANIFEST" ->
    "drop one scoped-out source tooth from the canonical 35-row partition"
|>;

raise[name_] := Throw[name, "ledgerStage035Failure"];

assertExact[name_, expression_] := Module[{reals},
  reals = Cases[Unevaluated[expression], _Real, Infinity];
  If[reals =!= {},
    failCount++;
    Print["FIRST_FAILURE=", name];
    Print["FAIL  ", name, ": machine-real atom(s): ", InputForm[reals]];
    raise[name]
  ]
];

cleanZero[expression_] :=
  FullSimplify[expression] /. ConditionalExpression[0, _] -> 0;

expectZero[name_, residual_, evidence_: None] := Module[{clean},
  assertExact[name, residual];
  clean = cleanZero[residual];
  assertExact[name, clean];
  If[TrueQ[clean === 0],
    passCount++;
    Print["PASS  ", name],
    failCount++;
    Print["FIRST_FAILURE=", name];
    If[activeMutation === name, Print["FIRED_AT_OWN_ASSERT=", name]];
    Print["FAIL  ", name, ": residual = ", InputForm[clean]];
    If[evidence =!= None, Print["      evidence = ", InputForm[evidence]]];
    raise[name]
  ]
];

expectBool[name_, condition_, evidence_: None] :=
  expectZero[name, If[TrueQ[condition], 0, 1], evidence];

section[text_] := (
  Print[""];
  Print[text];
  Print[StringRepeat["-", StringLength[text]]]
);

zq[expression_] := TrueQ[
  FullSimplify[
    expression == 0,
    a0 > 0 && Element[
      {x, y, z, vx, vy, vz, s, qT, lambdaT, tauD, alpha}, Reals]]
];

(* ---------------------------------------------------------------------- *)
(* Explicit Gaussian route: native D + Div followed by Reduce.             *)
(* ---------------------------------------------------------------------- *)

coordinates = {x, y, z};
centerFunctions = {xCenter[t], yCenter[t], zCenter[t]};
velocityVector = {vx, vy, vz};
centerVelocityRules = {
  Derivative[1][xCenter][t] -> vx,
  Derivative[1][yCenter][t] -> vy,
  Derivative[1][zCenter][t] -> vz
};

etaMoving =
  Exp[-Total[(coordinates - centerFunctions)^2]/a0^2]/
    (Pi^(3/2) a0^3);
sigmaMoving = s etaMoving;
dtSigma = Factor[D[sigmaMoving, t] /. centerVelocityRules];
fluxDivergence = Factor[
  Div[alpha sigmaMoving velocityVector, coordinates]];
continuityGeneral = Factor[dtSigma + fluxDivergence];
directionalGradient = Factor[
  velocityVector.Grad[sigmaMoving, coordinates]];
coefficientLaw = FullSimplify[
  Cancel[continuityGeneral/directionalGradient],
  a0 > 0];
uniqueCondition = Reduce[
  coefficientLaw == 0, alpha, Reals];
uniqueAlpha = If[SameQ[uniqueCondition, alpha == 1], 1, Indeterminate];

centerSnapshotRules = {
  xCenter[t] -> xC, yCenter[t] -> yC, zCenter[t] -> zC
};
etaSnapshot = etaMoving /. centerSnapshotRules;
signedSnapshot = s etaSnapshot;

(* Wolfram identifiers cannot contain raw underscores.  Keep those two exact
   source-code names as inert, code-native marker atoms rather than silently
   renaming them; the mutation uses the ordinary native symbol Nu. *)
qATMarker = barredCodeSymbol["q_A_T"];
qLMarker = barredCodeSymbol["q_L"];
barredDisplayToCode = {
  "N_u" -> Nu,
  "a_T" -> aT,
  "a'_T" -> aTp,
  "a_L" -> aL,
  "q_A^T" -> qATMarker,
  "q_L" -> qLMarker
};
barredSourceMarkers = Last /@ barredDisplayToCode;

sourceBuild[
    fluxCoefficient_: 1, injectBarred_: False,
    sourceScale_: 1] := Module[
  {nativeFlux, nativeSource, candidate},
  nativeFlux = uniqueAlpha signedSnapshot velocityVector;
  nativeSource = qT nativeFlux;
  candidate = sourceScale nativeSource;
  If[TrueQ[injectBarred],
    candidate = ReplacePart[
      candidate, 1 -> Expand[candidate[[1]] + Nu nativeSource[[1]]]]
  ];
  <|
    "SelectedFluxCoefficient" -> fluxCoefficient,
    "ContinuityResidual" ->
      Factor[continuityGeneral /. alpha -> fluxCoefficient],
    "UniqueFluxCoefficient" -> uniqueAlpha,
    "NativeFlux" -> nativeFlux,
    "NativeSource" -> nativeSource,
    "CandidateSource" -> candidate
  |>
];

freeGlobalSymbols[expression_] := DeleteDuplicates@Cases[
  expression,
  symbol_Symbol /; Context[Unevaluated[symbol]] === "Global`" :>
    Unevaluated[symbol],
  {0, Infinity},
  Heads -> True
];

freeSourceMarkers[expression_] := Union[
  freeGlobalSymbols[expression],
  DeleteDuplicates@Cases[
    expression, marker_barredCodeSymbol :> marker, {0, Infinity}]
];

(* ---------------------------------------------------------------------- *)
(* Operator-generated parity census and explicit polar/axial classifier.   *)
(* ---------------------------------------------------------------------- *)

paritySign[expression_, rules_] :=
  FullSimplify[(expression /. rules)/expression];

vectorZeroQ[vector_] :=
  And @@ (TrueQ[FullSimplify[# == 0]] & /@ vector);

classifyVector[
    original_, properImage_, reflectionImage_,
    properMatrix_, reflectionMatrix_] := Which[
  vectorZeroQ[properImage - properMatrix.original] &&
    vectorZeroQ[reflectionImage - reflectionMatrix.original],
    "polar_vector",
  vectorZeroQ[properImage - properMatrix.original] &&
    vectorZeroQ[
      reflectionImage -
        Det[reflectionMatrix] reflectionMatrix.original],
    "axial_vector",
  True,
    "unclassified"
];

parityBuild[mutation_: ""] := Module[
  {
    generators, qMonomial, jMonomial, uMonomial, bMonomial,
    monomials, rwRules, pwRules, timeRules, rwSigns, pwSigns,
    timeSigns, properMatrix, reflectionMatrix, vVector, gVector,
    jVector, uVector, bVector, gradientReflection, rotations,
    census
  },
  generators = {
    sGenerator, vGenerator, tauGenerator, lambdaGenerator,
    etaGenerator, responseGenerator, gradientGenerator
  };
  qMonomial = lambdaGenerator tauGenerator;
  jMonomial =
    qMonomial sGenerator etaGenerator vGenerator;
  uMonomial = responseGenerator jMonomial;
  bMonomial = gradientGenerator uMonomial;
  monomials = <|
    "s" -> sGenerator,
    "V" -> vGenerator,
    "tau_d/q_T" -> qMonomial,
    "J_T" -> jMonomial,
    "u_T" -> uMonomial,
    "b_T" -> bMonomial
  |>;

  rwRules = {
    sGenerator -> -sGenerator,
    vGenerator -> vGenerator,
    tauGenerator -> tauGenerator,
    lambdaGenerator -> lambdaGenerator,
    etaGenerator -> etaGenerator,
    responseGenerator ->
      If[mutation === "PARITY_RW", -responseGenerator, responseGenerator],
    gradientGenerator -> gradientGenerator
  };
  pwRules = {
    sGenerator -> -sGenerator,
    vGenerator -> vGenerator,
    tauGenerator -> tauGenerator,
    lambdaGenerator -> lambdaGenerator,
    etaGenerator -> etaGenerator,
    responseGenerator ->
      If[mutation === "PARITY_PW", -responseGenerator, responseGenerator],
    gradientGenerator -> gradientGenerator
  };
  timeRules = {
    sGenerator -> sGenerator,
    vGenerator -> -vGenerator,
    tauGenerator ->
      If[
        mutation === "PARITY_TIME_REVERSAL",
        tauGenerator, -tauGenerator],
    lambdaGenerator -> lambdaGenerator,
    etaGenerator -> etaGenerator,
    responseGenerator -> responseGenerator,
    gradientGenerator -> gradientGenerator
  };
  rwSigns = Association@KeyValueMap[
    Function[{name, expression},
      name -> paritySign[expression, rwRules]], monomials];
  pwSigns = Association@KeyValueMap[
    Function[{name, expression},
      name -> paritySign[expression, pwRules]], monomials];
  timeSigns = Association@KeyValueMap[
    Function[{name, expression},
      name -> paritySign[expression, timeRules]], monomials];

  properMatrix = {{0, -1, 0}, {1, 0, 0}, {0, 0, 1}};
  reflectionMatrix = DiagonalMatrix[{-1, 1, 1}];
  vVector = {vp1, vp2, vp3};
  gVector = {gp1, gp2, gp3};
  jVector = jScalar vVector;
  uVector = responseScalar jVector;
  bVector = Cross[gVector, uVector];
  gradientReflection = If[
    mutation === "PARITY_ROTATION",
    Det[reflectionMatrix] reflectionMatrix.gVector,
    reflectionMatrix.gVector
  ];
  rotations = <|
    "s" -> "scalar",
    "V" -> classifyVector[
      vVector,
      properMatrix.vVector,
      reflectionMatrix.vVector,
      properMatrix, reflectionMatrix],
    "tau_d/q_T" -> "scalar",
    "J_T" -> classifyVector[
      jVector,
      jScalar properMatrix.vVector,
      jScalar reflectionMatrix.vVector,
      properMatrix, reflectionMatrix],
    "u_T" -> classifyVector[
      uVector,
      responseScalar jScalar properMatrix.vVector,
      responseScalar jScalar reflectionMatrix.vVector,
      properMatrix, reflectionMatrix],
    "b_T" -> classifyVector[
      bVector,
      Cross[
        properMatrix.gVector,
        properMatrix.uVector],
      Cross[
        gradientReflection,
        reflectionMatrix.uVector],
      properMatrix, reflectionMatrix]
  |>;

  census = Association@Map[
    Function[name,
      name -> {
        rwSigns[name], pwSigns[name], rotations[name], timeSigns[name]}],
    Keys[monomials]];
  <|
    "Census" -> census,
    "Monomials" -> monomials,
    "TauTime" -> paritySign[tauGenerator, timeRules],
    "QTime" -> timeSigns["tau_d/q_T"]
  |>
];

expectedCensus = <|
  "s" -> {-1, -1, "scalar", 1},
  "V" -> {1, 1, "polar_vector", -1},
  "tau_d/q_T" -> {1, 1, "scalar", -1},
  "J_T" -> {-1, -1, "polar_vector", 1},
  "u_T" -> {-1, -1, "polar_vector", 1},
  "b_T" -> {-1, -1, "axial_vector", 1}
|>;

parityInvariants[build_] := Module[{census, order},
  census = build["Census"];
  order = Keys[expectedCensus];
  <|
    "PARITY_RW" -> (
      (census[#][[1]] & /@ order) ===
        (expectedCensus[#][[1]] & /@ order) &&
      census["J_T"][[1]] === -1 &&
      census["u_T"][[1]] === -1),
    "PARITY_PW" -> (
      (census[#][[2]] & /@ order) ===
        (expectedCensus[#][[2]] & /@ order) &&
      census["J_T"][[2]] === -1 &&
      census["u_T"][[2]] === -1),
    "PARITY_ROTATION" -> (
      (census[#][[3]] & /@ order) ===
        (expectedCensus[#][[3]] & /@ order) &&
      census["u_T"][[3]] === "polar_vector" &&
      census["b_T"][[3]] === "axial_vector"),
    "PARITY_TIME_REVERSAL" -> (
      (census[#][[4]] & /@ order) ===
        (expectedCensus[#][[4]] & /@ order) &&
      build["TauTime"] === -1 &&
      build["QTime"] === -1 &&
      census["V"][[4]] === -1 &&
      census["J_T"][[4]] === 1 &&
      census["u_T"][[4]] === 1 &&
      census["b_T"][[4]] === 1)
  |>
];

(* ---------------------------------------------------------------------- *)
(* Formal unit rescaling of the live explicit source expressions.          *)
(* ---------------------------------------------------------------------- *)

uField = {
  c11 x + c12 y + c13 z,
  c21 x + c22 y + c23 z,
  c31 x + c32 y + c33 z
};
bField = Curl[uField, coordinates];

scaledRatio[expression_, rules_] := FullSimplify[
  (expression /. rules)/expression,
  lengthScale > 0 && timeScale > 0 && massScale > 0 && a0 > 0
];

unitScalingObject[badQ_: False] := Module[
  {rules, source, snapshotGradient, continuityTerms},
  rules = {
    x -> lengthScale x,
    y -> lengthScale y,
    z -> lengthScale z,
    xC -> lengthScale xC,
    yC -> lengthScale yC,
    zC -> lengthScale zC,
    a0 -> lengthScale a0,
    vx -> lengthScale vx/timeScale,
    vy -> lengthScale vy/timeScale,
    vz -> lengthScale vz/timeScale,
    qT ->
      massScale If[TrueQ[badQ], lengthScale, 1] qT/timeScale
  };
  source = sourceBuild[];
  snapshotGradient =
    velocityVector.Grad[signedSnapshot, coordinates];
  continuityTerms = {-snapshotGradient, alpha snapshotGradient};
  <|
    "SigmaScale" -> scaledRatio[signedSnapshot, rules],
    "ContinuityScales" -> (scaledRatio[#, rules] & /@ continuityTerms),
    "IScales" -> (scaledRatio[#, rules] & /@ source["NativeFlux"]),
    "JScales" -> (scaledRatio[#, rules] & /@ source["NativeSource"]),
    "EtaScale" -> scaledRatio[etaSnapshot, rules],
    "VScales" -> (scaledRatio[#, rules] & /@ velocityVector),
    "UScales" -> (scaledRatio[#, rules] & /@ uField),
    "BScales" -> (scaledRatio[#, rules] & /@ bField),
    "QScale" ->
      massScale If[TrueQ[badQ], lengthScale, 1]/timeScale
  |>
];

(* ---------------------------------------------------------------------- *)
(* Target blindness, canonical term inventory, and verdict precedence.     *)
(* ---------------------------------------------------------------------- *)

forbiddenTargetSymbols = {
  aElectric, qElectric, gElectric, ratioBA,
  downstreamLanding, downstreamSign
};

expectedTermInventory = {
  "signed_density",
  "translation_time_derivative",
  "isotropic_flux_divergence",
  "continuity_residual",
  "unique_alpha",
  "native_flux_I",
  "native_source_J_T",
  "q_T_relation",
  "parity_census_24_cells",
  "P_w_w_reflection_caveat",
  "dimension_firewall",
  "verdict_precedence"
};

computedTermInventory[includeQRelation_: True] := Module[
  {source, parity, terms = {}},
  source = sourceBuild[];
  parity = parityBuild[];
  If[!FreeQ[signedSnapshot, s], AppendTo[terms, "signed_density"]];
  If[!zq[dtSigma], AppendTo[terms, "translation_time_derivative"]];
  If[!FreeQ[fluxDivergence, alpha],
    AppendTo[terms, "isotropic_flux_divergence"]];
  If[!FreeQ[continuityGeneral, alpha],
    AppendTo[terms, "continuity_residual"]];
  If[uniqueAlpha === 1, AppendTo[terms, "unique_alpha"]];
  If[Length[source["NativeFlux"]] === 3,
    AppendTo[terms, "native_flux_I"]];
  If[
    Length[source["NativeSource"]] === 3 &&
      !FreeQ[source["NativeSource"], qT],
    AppendTo[terms, "native_source_J_T"]];
  If[TrueQ[includeQRelation], AppendTo[terms, "q_T_relation"]];
  If[Length[parity["Census"]] 4 === 24,
    AppendTo[terms, "parity_census_24_cells"]];
  AppendTo[terms, "P_w_w_reflection_caveat"];
  If[Length[unitScalingObject[]] === 9,
    AppendTo[terms, "dimension_firewall"]];
  AppendTo[terms, "verdict_precedence"];
  terms
];

deriveVerdict[
    source_, parity_, uniqueOverride_: Automatic,
    magnitudeStatus_: "R1(magnitude)"] := Module[
  {
    unique, symbols, barredIntersection, basisResiduals,
    invariants, sourceValid
  },
  unique = If[
    uniqueOverride === Automatic,
    source["UniqueFluxCoefficient"], uniqueOverride];
  symbols = freeSourceMarkers[source["CandidateSource"]];
  barredIntersection = Intersection[symbols, barredSourceMarkers];
  basisResiduals =
    source["CandidateSource"] - source["NativeSource"];
  invariants = parityInvariants[parity];
  sourceValid =
    zq[source["ContinuityResidual"]] &&
    TrueQ[FullSimplify[unique == 1]] &&
    And @@ (zq /@ basisResiduals) &&
    barredIntersection === {};
  Which[
    !TrueQ[sourceValid], r1SourceToken,
    !And @@ (TrueQ /@ Values[invariants]), parityBadToken,
    True, verdictToken
  ]
];

(* Exact source-build order: all 35 source teeth, no wildcard families. *)
sourceToothIDs = {
  "SOURCE_TRANSLATION_CONTINUITY",
  "SOURCE_NOT_IMPORTED",
  "SOURCE_BASIS",
  "PARITY_RW",
  "PARITY_PW",
  "PARITY_ROTATION",
  "PARITY_TIME_REVERSAL",
  "FIELD_IDENTITY_UNITS",
  "ACTION_KINETIC",
  "ACTION_COUPLING",
  "ACTION_STABILITY",
  "G0_DAMAGE",
  "ROUTE_INDEPENDENCE",
  "BOOST_PROJECTOR",
  "BOOST_GENERAL_VELOCITIES",
  "BOOST_NEXT_ORDER",
  "BOOST_COMMON_VELOCITY",
  "DIRECT_SOURCE",
  "DIRECT_PROJECTOR",
  "DIRECT_EXCHANGE_SIGN",
  "DIRECT_FALLOFF",
  "DIRECT_VELOCITY_ORDER",
  "COMPARE_COMPUTED",
  "DELTA_RATIO",
  "CONE_RATIO",
  "QMAG_R1",
  "UNITS_RESTORED",
  "ACTIVE_FLUX_CAVEAT",
  "HOOK_LORENTZ",
  "LEDGER_READY_ROW",
  "TRUTH_TOTALITY",
  "TRUTH_PRECEDENCE",
  "LANDING_OWNERSHIP",
  "TARGET_BLINDNESS",
  "DUAL_ENGINE_TERMS"
};

sourceManifest = {
  {"SOURCE_TRANSLATION_CONTINUITY", "PRESERVED",
    "STAGE035_CONTINUITY_RESIDUAL"},
  {"SOURCE_NOT_IMPORTED", "PRESERVED",
    "STAGE035_FREE_SYMBOL_GUARD"},
  {"SOURCE_BASIS", "PRESERVED",
    "STAGE035_COMPONENT_BASIS"},
  {"PARITY_RW", "PRESERVED",
    "STAGE035_MULTIPLICATIVE_CENSUS"},
  {"PARITY_PW", "PRESERVED",
    "STAGE035_MULTIPLICATIVE_CENSUS"},
  {"PARITY_ROTATION", "PRESERVED",
    "STAGE035_MULTIPLICATIVE_CENSUS"},
  {"PARITY_TIME_REVERSAL", "PRESERVED",
    "STAGE035_MULTIPLICATIVE_CENSUS"},
  {"FIELD_IDENTITY_UNITS", "SCOPED_OUT", "STAGE034_V1_DONE"},
  {"ACTION_KINETIC", "SCOPED_OUT", "STAGE034_V1_DONE"},
  {"ACTION_COUPLING", "SCOPED_OUT", "STAGE034_V1_DONE"},
  {"ACTION_STABILITY", "SCOPED_OUT", "STAGE034_V1_DONE"},
  {"G0_DAMAGE", "SCOPED_OUT", "STAGE034_V1_DONE"},
  {"ROUTE_INDEPENDENCE", "SCOPED_OUT", "STAGE037_V4"},
  {"BOOST_PROJECTOR", "SCOPED_OUT", "STAGE036_V3"},
  {"BOOST_GENERAL_VELOCITIES", "SCOPED_OUT", "STAGE036_V3"},
  {"BOOST_NEXT_ORDER", "SCOPED_OUT", "STAGE036_V3"},
  {"BOOST_COMMON_VELOCITY", "SCOPED_OUT", "STAGE037_V4"},
  {"DIRECT_SOURCE", "SCOPED_OUT", "STAGE037_V4"},
  {"DIRECT_PROJECTOR", "SCOPED_OUT", "STAGE037_V4"},
  {"DIRECT_EXCHANGE_SIGN", "SCOPED_OUT", "STAGE037_V4"},
  {"DIRECT_FALLOFF", "SCOPED_OUT", "STAGE037_V4"},
  {"DIRECT_VELOCITY_ORDER", "SCOPED_OUT", "STAGE037_V4"},
  {"COMPARE_COMPUTED", "SCOPED_OUT", "STAGE037_V4"},
  {"DELTA_RATIO", "SCOPED_OUT", "STAGE037_V4"},
  {"CONE_RATIO", "SCOPED_OUT", "STAGE037_V4"},
  {"QMAG_R1", "SCOPED_OUT", "STAGE037_V4"},
  {"UNITS_RESTORED", "REPLACED_BY_STRONGER",
    "STAGE035_EXPRESSION_DIMENSION_FIREWALL"},
  {"ACTIVE_FLUX_CAVEAT", "SCOPED_OUT", "STAGE038_V5"},
  {"HOOK_LORENTZ", "SCOPED_OUT", "STAGE038_V5"},
  {"LEDGER_READY_ROW", "SCOPED_OUT", "STAGE034_V1_DONE"},
  {"TRUTH_TOTALITY", "SCOPED_OUT", "STAGE038_V5"},
  {"TRUTH_PRECEDENCE", "SCOPED_OUT", "STAGE038_V5"},
  {"LANDING_OWNERSHIP", "SCOPED_OUT", "STAGE038_V5"},
  {"TARGET_BLINDNESS", "PRESERVED",
    "STAGE035_SOURCE_SIDE_DEPENDENCIES"},
  {"DUAL_ENGINE_TERMS", "REPLACED_BY_STRONGER",
    "STAGE035_CANONICAL_TERM_INVENTORY"}
};

expectedManifestCounts = KeySort@<|
  "PRESERVED" -> 8,
  "REPLACED_BY_STRONGER" -> 2,
  "SCOPED_OUT" -> 25
|>;
expectedScopedOut = Cases[
  sourceManifest, {identifier_, "SCOPED_OUT", _} :> identifier];

lexicographicCodeLess[left_List, right_List] := Module[{limit, index},
  limit = Min[Length[left], Length[right]];
  index = SelectFirst[
    Range[limit], left[[#]] =!= right[[#]] &, Missing["NotFound"]];
  If[
    MissingQ[index],
    Length[left] < Length[right],
    left[[index]] < right[[index]]]
];

canonicalManifestText[manifest_] := Module[{rows},
  rows = StringRiffle[#, "|"] & /@ manifest;
  StringRiffle[
    Sort[
      rows,
      lexicographicCodeLess[
        ToCharacterCode[#1], ToCharacterCode[#2]] &],
    "\n"]
];

manifestSHA256[manifest_] :=
  IntegerString[Hash[canonicalManifestText[manifest], "SHA256"], 16, 64];

ok = Catch[
  If[activeMutation =!= "" && !MemberQ[toothOrder, activeMutation],
    Print["FIRST_FAILURE=UNKNOWN_MUTATION"];
    Print["FAIL  UNKNOWN_MUTATION: ", activeMutation];
    raise["UNKNOWN_MUTATION"]
  ];

  Print[
    "ledger_stage035_native_source_convection_conditional Mathematica audit"];
  Print[
    "ROUTE=explicit Gaussian D+Div+Reduce + operator-generated census + Det/Cross classification"];
  Print["FILE_IO=none; CROSS_ENGINE_COMPARE=none"];
  Print["PROGRESS MATHEMATICA STAGE035 START"];
  If[activeMutation =!= "",
    Print["ACTIVE_MUTATION=", activeMutation];
    Print["MUTATED_PRIMITIVE=", ablationDescriptions[activeMutation]]
  ];

  section[
    "Signed-dent Gaussian continuity and unique isotropic flux via Reduce"];
  selectedAlpha = If[
    activeMutation === "SOURCE_TRANSLATION_CONTINUITY", 2, 1];
  liveSource = sourceBuild[
    selectedAlpha,
    activeMutation === "SOURCE_NOT_IMPORTED",
    If[activeMutation === "SOURCE_BASIS", 2, 1]];
  wrongCoefficientResidual =
    Factor[continuityGeneral /. alpha -> 2];
  continuityOK =
    zq[liveSource["ContinuityResidual"]] &&
    SameQ[uniqueCondition, alpha == 1] &&
    uniqueAlpha === 1 &&
    zq[coefficientLaw - (alpha - 1)] &&
    zq[
      continuityGeneral -
        (alpha - 1) directionalGradient] &&
    !zq[wrongCoefficientResidual];
  expectBool[
    "SOURCE_TRANSLATION_CONTINUITY",
    continuityOK,
    <|
      "SelectedAlpha" -> selectedAlpha,
      "Residual" -> liveSource["ContinuityResidual"],
      "CoefficientLaw" -> coefficientLaw,
      "UniqueCondition" -> uniqueCondition,
      "Alpha2Control" -> wrongCoefficientResidual
    |>];
  Print[
    "      sigma_i=s_i*Gaussian(x-X_i(t)); residual=(alpha-1) V.Grad[sigma_i]"];
  Print[
    "      Reduce gives unique alpha=1; alpha=2 control is nonzero"];
  Print["PROGRESS MATHEMATICA CONTINUITY COMPLETE"];

  section["Surviving-solution free-symbol guard"];
  sourceSymbols = freeSourceMarkers[liveSource["CandidateSource"]];
  barredIntersection =
    Intersection[sourceSymbols, barredSourceMarkers];
  expectBool[
    "SOURCE_NOT_IMPORTED",
    barredIntersection === {},
    <|
      "BarredIntersection" -> barredIntersection,
      "Mapping" -> barredDisplayToCode
    |>];
  Print[
    "      BARRED_MAPPING=N_u->Nu,a_T->aT,a'_T->aTp,a_L->aL,q_A^T->q_A_T,q_L->q_L"];
  Print[
    "      native source REPLACES barred j~sV/pathA_39; no barred amplitude imported"];

  section["Continuity-derived tensor source basis"];
  basisResiduals =
    liveSource["CandidateSource"] - liveSource["NativeSource"];
  qRelationSource =
    liveSource["NativeSource"] /. qT -> lambdaT tauD;
  expectedQRelationSource =
    lambdaT tauD signedSnapshot velocityVector;
  expectBool[
    "SOURCE_BASIS",
    And @@ (zq /@ basisResiduals) &&
    liveSource["NativeFlux"] ===
      signedSnapshot velocityVector &&
    qRelationSource === expectedQRelationSource,
    <|
      "ComponentResiduals" -> basisResiduals,
      "I" -> liveSource["NativeFlux"],
      "J" -> liveSource["CandidateSource"],
      "QRelation" -> qT - lambdaT tauD
    |>];
  Print["      I_i=s_i*eta_a(x-X_i)*V_i"];
  Print[
    "      J_T,i=q_T*I_i=q_T*s_i*eta_a(x-X_i)*V_i; q_T=lambda_T*tau_d"];

  section["Operator-generated 24-cell parity census"];
  parityMutation = If[
    MemberQ[
      {"PARITY_RW", "PARITY_PW", "PARITY_ROTATION",
        "PARITY_TIME_REVERSAL"},
      activeMutation],
    activeMutation,
    ""];
  liveParity = parityBuild[parityMutation];
  liveInvariants = parityInvariants[liveParity];
  Scan[
    Function[tooth,
      expectBool[tooth, liveInvariants[tooth], liveParity["Census"]]],
    {
      "PARITY_RW", "PARITY_PW", "PARITY_ROTATION",
      "PARITY_TIME_REVERSAL"
    }];
  KeyValueMap[
    Function[{name, row},
      Print[
        "      ", name,
        ": R_w=", If[row[[1]] === 1, "+1", "-1"],
        ", P_w=", If[row[[2]] === 1, "+1", "-1"],
        ", rotation=", row[[3]],
        ", T=", If[row[[4]] === 1, "+1", "-1"]]],
    liveParity["Census"]];
  Print[
    "      P_w denotes a w-type reflection of the transverse coordinate, NOT ordinary x->-x parity"];
  Print[
    "      b_T axial and T-even are RAW census facts; departure interpretation is deferred to stage039"];
  Print["PROGRESS MATHEMATICA PARITY CENSUS COMPLETE"];

  section["Build-global target blindness and canonical term coverage"];
  blindnessExpression =
    Total[liveSource["NativeSource"]] +
    qT - lambdaT tauD + s + Total[velocityVector] +
    Total[Values[liveParity["Monomials"]]];
  If[
    activeMutation === "TARGET_BLINDNESS",
    blindnessExpression += aElectric signedSnapshot];
  forbiddenLive = Intersection[
    freeGlobalSymbols[blindnessExpression],
    forbiddenTargetSymbols];
  expectBool[
    "TARGET_BLINDNESS",
    forbiddenLive === {},
    <|"ForbiddenLive" -> forbiddenLive|>];
  Print[
    "      no electric A_E; no q/g knob; no downstream comparison/landing/sign token"];

  inventory = computedTermInventory[
    activeMutation =!= "DUAL_ENGINE_TERMS"];
  expectBool[
    "DUAL_ENGINE_TERMS",
    inventory === expectedTermInventory,
    <|"Computed" -> inventory, "Required" -> expectedTermInventory|>];
  Print["      TERM_INVENTORY=", StringRiffle[inventory, ","]];

  section["Whole-stage restored-unit firewall via formal rescaling"];
  restored = unitScalingObject[
    activeMutation === "UNITS_RESTORED"];
  expectedScaling = <|
    "SigmaScale" -> lengthScale^-3,
    "ContinuityScales" ->
      {lengthScale^-3 timeScale^-1,
        lengthScale^-3 timeScale^-1},
    "IScales" ->
      ConstantArray[lengthScale^-2 timeScale^-1, 3],
    "JScales" ->
      ConstantArray[
        massScale lengthScale^-2 timeScale^-2, 3],
    "EtaScale" -> lengthScale^-3,
    "VScales" ->
      ConstantArray[lengthScale timeScale^-1, 3],
    "UScales" -> ConstantArray[lengthScale, 3],
    "BScales" -> ConstantArray[1, 3],
    "QScale" -> massScale timeScale^-1
  |>;
  expectBool[
    "UNITS_RESTORED",
    restored === expectedScaling,
    <|"Computed" -> restored, "Required" -> expectedScaling|>];
  Print[
    "      [sigma]=[eta_a]=L^-3; [I]=L^-2 T^-1; [q_T]=M T^-1"];
  Print[
    "      [J_T]=M L^-2 T^-2; [V]=L T^-1; [u_T]=L; [b_T]=1"];

  section["Build-native verdict precedence from computed upstream objects"];
  verdictSource = sourceBuild[
    If[activeMutation === "VERDICT_REDERIVATION", 2, 1]];
  cleanParity = parityBuild[];
  liveVerdict =
    deriveVerdict[verdictSource, cleanParity, Automatic, magnitudeR1];
  magnitudeForcedVerdict =
    deriveVerdict[
      sourceBuild[], cleanParity, Automatic,
      "magnitude_forced_by_electric"];
  continuityNegative =
    deriveVerdict[sourceBuild[2], cleanParity];
  coefficientNegative =
    deriveVerdict[sourceBuild[], cleanParity, 2];
  basisNegative =
    deriveVerdict[sourceBuild[1, False, 2], cleanParity];
  barredNegative =
    deriveVerdict[sourceBuild[1, True], cleanParity];
  parityNegative =
    deriveVerdict[sourceBuild[], parityBuild["PARITY_RW"]];
  sourcePrecedence =
    deriveVerdict[sourceBuild[2], parityBuild["PARITY_RW"]];
  expectBool[
    "VERDICT_REDERIVATION",
    liveVerdict === verdictToken &&
    magnitudeForcedVerdict === verdictToken &&
    continuityNegative === r1SourceToken &&
    coefficientNegative === r1SourceToken &&
    basisNegative === r1SourceToken &&
    barredNegative === r1SourceToken &&
    parityNegative === parityBadToken &&
    sourcePrecedence === r1SourceToken,
    <|
      "Rederived" -> liveVerdict,
      "AlphaNegative" -> continuityNegative,
      "WrongUniqueCoefficient" -> coefficientNegative,
      "BasisNegative" -> basisNegative,
      "BarredNegative" -> barredNegative,
      "ParityNegative" -> parityNegative,
      "SourceOverParity" -> sourcePrecedence,
      "MagnitudeR1" -> magnitudeR1
    |>];
  Print["      SOURCE_FAILURE_TOKEN=", r1SourceToken];
  Print["      CENSUS_FAILURE_TOKEN=", parityBadToken];
  Print["      R1_MAGNITUDE_IDENTITY_TOKEN=", liveVerdict];

  section["Canonical source-to-stage predicate manifest"];
  manifestTest = If[
    activeMutation === "SOURCE_TO_STAGE_MANIFEST",
    Most[sourceManifest],
    sourceManifest];
  identifiers = manifestTest[[All, 1]];
  partitionCounts = KeySort@Counts[manifestTest[[All, 2]]];
  scopedOut = Cases[
    manifestTest, {identifier_, "SCOPED_OUT", _} :> identifier];
  manifestDigest = manifestSHA256[manifestTest];
  manifestOK =
    identifiers === sourceToothIDs &&
    Length[identifiers] === Length[DeleteDuplicates[identifiers]] === 35 &&
    partitionCounts === expectedManifestCounts &&
    scopedOut === expectedScopedOut &&
    Length[scopedOut] === 25 &&
    AllTrue[
      manifestTest[[All, 3]],
      StringStartsQ[
        #,
        Alternatives[
          "STAGE034_", "STAGE035_", "STAGE036_",
          "STAGE037_", "STAGE038_"]] &] &&
    manifestDigest === manifestDigestExpected;
  expectBool[
    "SOURCE_TO_STAGE_MANIFEST",
    manifestOK,
    <|
      "Entries" -> Length[manifestTest],
      "Partition" -> partitionCounts,
      "ScopedOut" -> scopedOut,
      "Digest" -> manifestDigest
    |>];
  Print[
    "      entries=", Length[manifestTest],
    "; partition=", partitionCounts,
    "; scoped_out=", Length[scopedOut],
    "; digest=", manifestDigest];
  Print["      SCOPED_OUT=", StringRiffle[scopedOut, ","]];

  Print[""];
  Print[
    "SOURCE_LAW=I_i=s_i*eta_a(x-X_i)*V_i; J_T,i=q_T*I_i"];
  Print["Q_T=lambda_T*tau_d; MAGNITUDE=R1(magnitude)"];
  Print[
    "PROVENANCE=q_T,tau_d,u_T,eta_a cited from stage034/stage003; not re-derived or re-counted"];
  Print[
    "SCOPE=source law + raw parity census only; action/routes/landing/departure deferred"];
  Print["VERDICT_TOKEN: ", liveVerdict];
  Print["PROGRESS MATHEMATICA STAGE035 COMPLETE"];

  If[activeMutation =!= "",
    Print["FIRST_FAILURE=MUTATION_DID_NOT_FIRE"];
    raise["MUTATION_DID_NOT_FIRE"]
  ];
  True,
  "ledgerStage035Failure",
  Function[{message, tag}, False]
];

Print[""];
Print["TOOTH_COUNT=", Length[toothOrder]];
Print["PASS tally: ", passCount, "; FAIL tally: ", failCount];
If[TrueQ[ok],
  Print[
    "OVERALL PASS: Mathematica independently reached ",
    verdictToken];
  Exit[0],
  Print[
    "OVERALL FAIL: Mathematica stage035 audit did not close"];
  Exit[1]
]
