-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 10ebaecb24b1ca92131566a37197f73cb9b93c8925299ec404838b50fdce75cf
import S10Audit.CAS.CoincidenceSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.PYCoincidenceArithmeticPerpendicular
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar (-1)
theorem n0_dim : Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar (-1)) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = (-1) := by
  rfl

def n1 : Expr Symbol := .atom .mu
theorem n1_dim : Expr.HasDim coordinateUnits n1 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .mu
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = mu := by
  rfl

def n2 : Expr Symbol := .mul n0 n1
theorem n2_dim : Expr.HasDim coordinateUnits n2 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n0_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = ((-1) * mu) := by
  simp only [n2, Expr.eval, n0_eval, n1_eval]

def n3 : Expr Symbol := .atom .rho
theorem n3_dim : Expr.HasDim coordinateUnits n3 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .rho
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = rho := by
  rfl

def n4 : Expr Symbol := .div n2 n3
theorem n4_dim : Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n2_dim n3_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = (((-1) * mu) / rho) := by
  simp only [n4, Expr.eval, n2_eval, n3_eval]

def n5 : Expr Symbol := .atom .sigma
theorem n5_dim : Expr.HasDim coordinateUnits n5 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .sigma
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = sigma := by
  rfl

def n6 : Expr Symbol := .mul n3 n5
theorem n6_dim : Expr.HasDim coordinateUnits n6 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n3_dim n5_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = (rho * sigma) := by
  simp only [n6, Expr.eval, n3_eval, n5_eval]

def n7 : Expr Symbol := .div n2 n6
theorem n7_dim : Expr.HasDim coordinateUnits n7 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n2_dim n6_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = (((-1) * mu) / (rho * sigma)) := by
  simp only [n7, Expr.eval, n2_eval, n6_eval]

def n8 : Expr Symbol := .scalar 1
theorem n8_dim : Expr.HasDim coordinateUnits n8 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 1) dimensions_zero.symm
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = 1 := by
  rfl

def n9 : Expr Symbol := .sub n5 n8
theorem n9_dim : Expr.HasDim coordinateUnits n9 (dimensions 0 0 0) := by
  exact Expr.HasDim.sub n5_dim n8_dim
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = (sigma - 1) := by
  simp only [n9, Expr.eval, n5_eval, n8_eval]

def n10 : Expr Symbol := .mul n1 n9
theorem n10_dim : Expr.HasDim coordinateUnits n10 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n1_dim n9_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = (mu * (sigma - 1)) := by
  simp only [n10, Expr.eval, n1_eval, n9_eval]

def n11 : Expr Symbol := .div n10 n6
theorem n11_dim : Expr.HasDim coordinateUnits n11 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n10_dim n6_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = ((mu * (sigma - 1)) / (rho * sigma)) := by
  simp only [n11, Expr.eval, n10_eval, n6_eval]

def n12 : Expr Symbol := .scalar 2
theorem n12_dim : Expr.HasDim coordinateUnits n12 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2) dimensions_zero.symm
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = 2 := by
  rfl

def n13 : Expr Symbol := .scalar 3
theorem n13_dim : Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 3) dimensions_zero.symm
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rfl

theorem q8_stratum2_q3_root_coincidence_equations_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma PYLoci.perpendicularPoint 0 - referenceRoot rho mu sigma PYLoci.perpendicularPoint 1 := by
  rerun_eval n4_eval

theorem q8_stratum2_q3_root_coincidence_equations_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n7 = referenceRoot rho mu sigma PYLoci.perpendicularPoint 0 - referenceRoot rho mu sigma PYLoci.perpendicularPoint 2 := by
  rerun_eval n7_eval

theorem q8_stratum2_q3_root_coincidence_equations_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n11 = referenceRoot rho mu sigma PYLoci.perpendicularPoint 1 - referenceRoot rho mu sigma PYLoci.perpendicularPoint 2 := by
  rerun_eval n11_eval

theorem q8_stratum2_q3_root_coincidence_equations_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma PYLoci.perpendicularPoint 0 - referenceRoot rho mu sigma PYLoci.perpendicularPoint 1 ∧
    Expr.eval (values rho mu sigma z k) n7 = referenceRoot rho mu sigma PYLoci.perpendicularPoint 0 - referenceRoot rho mu sigma PYLoci.perpendicularPoint 2 ∧
    Expr.eval (values rho mu sigma z k) n11 = referenceRoot rho mu sigma PYLoci.perpendicularPoint 1 - referenceRoot rho mu sigma PYLoci.perpendicularPoint 2 :=
  ⟨q8_stratum2_q3_root_coincidence_equations_cell0 rho mu sigma z k h0 h1, q8_stratum2_q3_root_coincidence_equations_cell1 rho mu sigma z k h0 h1, q8_stratum2_q3_root_coincidence_equations_cell2 rho mu sigma z k h0 h1⟩

theorem q8_stratum2_q3_root_coincidence_equations_dimensions :
    Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n7 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n11 (dimensions 2 (-2) 0) :=
  ⟨n4_dim, n7_dim, n11_dim⟩

theorem q8_stratum2_q3_root_coincidence_pair_indices_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n8 = 1 := by
  rerun_eval n8_eval

theorem q8_stratum2_q3_root_coincidence_pair_indices_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n12 = 2 := by
  rerun_eval n12_eval

theorem q8_stratum2_q3_root_coincidence_pair_indices_cell2 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n8 = 1 := by
  rerun_eval n8_eval

theorem q8_stratum2_q3_root_coincidence_pair_indices_cell3 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rerun_eval n13_eval

theorem q8_stratum2_q3_root_coincidence_pair_indices_cell4 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n12 = 2 := by
  rerun_eval n12_eval

theorem q8_stratum2_q3_root_coincidence_pair_indices_cell5 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rerun_eval n13_eval

theorem q8_stratum2_q3_root_coincidence_pair_indices_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n8 = 1 ∧
    Expr.eval (values rho mu sigma z k) n12 = 2 ∧
    Expr.eval (values rho mu sigma z k) n8 = 1 ∧
    Expr.eval (values rho mu sigma z k) n13 = 3 ∧
    Expr.eval (values rho mu sigma z k) n12 = 2 ∧
    Expr.eval (values rho mu sigma z k) n13 = 3 :=
  ⟨q8_stratum2_q3_root_coincidence_pair_indices_cell0 rho mu sigma z k, q8_stratum2_q3_root_coincidence_pair_indices_cell1 rho mu sigma z k, q8_stratum2_q3_root_coincidence_pair_indices_cell2 rho mu sigma z k, q8_stratum2_q3_root_coincidence_pair_indices_cell3 rho mu sigma z k, q8_stratum2_q3_root_coincidence_pair_indices_cell4 rho mu sigma z k, q8_stratum2_q3_root_coincidence_pair_indices_cell5 rho mu sigma z k⟩

theorem q8_stratum2_q3_root_coincidence_pair_indices_dimensions :
    Expr.HasDim coordinateUnits n8 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n12 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n8 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n12 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) :=
  ⟨n8_dim, n12_dim, n8_dim, n13_dim, n12_dim, n13_dim⟩

end
end S10Audit.CAS.PYCoincidenceArithmeticPerpendicular
