-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 10ebaecb24b1ca92131566a37197f73cb9b93c8925299ec404838b50fdce75cf
import S10Audit.CAS.CoincidenceSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.PYCoincidenceArithmeticGeneric
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar (-1)
theorem n0_dim : Expr.HasDim units n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar (-1)) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = (-1) := by
  rfl

def n1 : Expr Symbol := .atom .mu
theorem n1_dim : Expr.HasDim units n1 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := units) .mu
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = mu := by
  rfl

def n2 : Expr Symbol := .mul n0 n1
theorem n2_dim : Expr.HasDim units n2 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n0_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = ((-1) * mu) := by
  simp only [n2, Expr.eval, n0_eval, n1_eval]

def n3 : Expr Symbol := .atom (.k 0)
theorem n3_dim : Expr.HasDim units n3 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 0)
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = (k 0) := by
  rfl

def n4 : Expr Symbol := .pow n3 2
theorem n4_dim : Expr.HasDim units n4 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n3_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = ((k 0) ^ 2) := by
  simp only [n4, Expr.eval, n3_eval]

def n5 : Expr Symbol := .atom (.k 1)
theorem n5_dim : Expr.HasDim units n5 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 1)
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = (k 1) := by
  rfl

def n6 : Expr Symbol := .pow n5 2
theorem n6_dim : Expr.HasDim units n6 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n5_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = ((k 1) ^ 2) := by
  simp only [n6, Expr.eval, n5_eval]

def n7 : Expr Symbol := .add n4 n6
theorem n7_dim : Expr.HasDim units n7 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n4_dim n6_dim
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = (((k 0) ^ 2) + ((k 1) ^ 2)) := by
  simp only [n7, Expr.eval, n4_eval, n6_eval]

def n8 : Expr Symbol := .atom (.k 2)
theorem n8_dim : Expr.HasDim units n8 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 2)
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = (k 2) := by
  rfl

def n9 : Expr Symbol := .pow n8 2
theorem n9_dim : Expr.HasDim units n9 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n8_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = ((k 2) ^ 2) := by
  simp only [n9, Expr.eval, n8_eval]

def n10 : Expr Symbol := .add n7 n9
theorem n10_dim : Expr.HasDim units n10 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n7_dim n9_dim
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) := by
  simp only [n10, Expr.eval, n7_eval, n9_eval]

def n11 : Expr Symbol := .mul n2 n10
theorem n11_dim : Expr.HasDim units n11 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n2_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = (((-1) * mu) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n11, Expr.eval, n2_eval, n10_eval]

def n12 : Expr Symbol := .atom .rho
theorem n12_dim : Expr.HasDim units n12 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := units) .rho
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = rho := by
  rfl

def n13 : Expr Symbol := .div n11 n12
theorem n13_dim : Expr.HasDim units n13 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.div n11_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = ((((-1) * mu) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / rho) := by
  simp only [n13, Expr.eval, n11_eval, n12_eval]

def n14 : Expr Symbol := .atom .sigma
theorem n14_dim : Expr.HasDim units n14 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := units) .sigma
theorem n14_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n14 = sigma := by
  rfl

def n15 : Expr Symbol := .mul n4 n14
theorem n15_dim : Expr.HasDim units n15 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n4_dim n14_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n15_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n15 = (((k 0) ^ 2) * sigma) := by
  simp only [n15, Expr.eval, n4_eval, n14_eval]

def n16 : Expr Symbol := .add n15 n6
theorem n16_dim : Expr.HasDim units n16 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n15_dim n6_dim
theorem n16_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n16 = ((((k 0) ^ 2) * sigma) + ((k 1) ^ 2)) := by
  simp only [n16, Expr.eval, n15_eval, n6_eval]

def n17 : Expr Symbol := .add n16 n9
theorem n17_dim : Expr.HasDim units n17 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n16_dim n9_dim
theorem n17_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n17 = (((((k 0) ^ 2) * sigma) + ((k 1) ^ 2)) + ((k 2) ^ 2)) := by
  simp only [n17, Expr.eval, n16_eval, n9_eval]

def n18 : Expr Symbol := .mul n2 n17
theorem n18_dim : Expr.HasDim units n18 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n2_dim n17_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n18_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n18 = (((-1) * mu) * (((((k 0) ^ 2) * sigma) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n18, Expr.eval, n2_eval, n17_eval]

def n19 : Expr Symbol := .mul n12 n14
theorem n19_dim : Expr.HasDim units n19 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n12_dim n14_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n19_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n19 = (rho * sigma) := by
  simp only [n19, Expr.eval, n12_eval, n14_eval]

def n20 : Expr Symbol := .div n18 n19
theorem n20_dim : Expr.HasDim units n20 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.div n18_dim n19_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n20_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n20 = ((((-1) * mu) * (((((k 0) ^ 2) * sigma) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / (rho * sigma)) := by
  simp only [n20, Expr.eval, n18_eval, n19_eval]

def n21 : Expr Symbol := .mul n6 n14
theorem n21_dim : Expr.HasDim units n21 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n6_dim n14_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n21_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n21 = (((k 1) ^ 2) * sigma) := by
  simp only [n21, Expr.eval, n6_eval, n14_eval]

def n22 : Expr Symbol := .sub n21 n6
theorem n22_dim : Expr.HasDim units n22 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.sub n21_dim n6_dim
theorem n22_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n22 = ((((k 1) ^ 2) * sigma) - ((k 1) ^ 2)) := by
  simp only [n22, Expr.eval, n21_eval, n6_eval]

def n23 : Expr Symbol := .mul n9 n14
theorem n23_dim : Expr.HasDim units n23 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n9_dim n14_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n23_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n23 = (((k 2) ^ 2) * sigma) := by
  simp only [n23, Expr.eval, n9_eval, n14_eval]

def n24 : Expr Symbol := .add n22 n23
theorem n24_dim : Expr.HasDim units n24 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n22_dim n23_dim
theorem n24_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n24 = (((((k 1) ^ 2) * sigma) - ((k 1) ^ 2)) + (((k 2) ^ 2) * sigma)) := by
  simp only [n24, Expr.eval, n22_eval, n23_eval]

def n25 : Expr Symbol := .sub n24 n9
theorem n25_dim : Expr.HasDim units n25 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.sub n24_dim n9_dim
theorem n25_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n25 = ((((((k 1) ^ 2) * sigma) - ((k 1) ^ 2)) + (((k 2) ^ 2) * sigma)) - ((k 2) ^ 2)) := by
  simp only [n25, Expr.eval, n24_eval, n9_eval]

def n26 : Expr Symbol := .mul n1 n25
theorem n26_dim : Expr.HasDim units n26 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n1_dim n25_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n26_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n26 = (mu * ((((((k 1) ^ 2) * sigma) - ((k 1) ^ 2)) + (((k 2) ^ 2) * sigma)) - ((k 2) ^ 2))) := by
  simp only [n26, Expr.eval, n1_eval, n25_eval]

def n27 : Expr Symbol := .div n26 n19
theorem n27_dim : Expr.HasDim units n27 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.div n26_dim n19_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n27_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n27 = ((mu * ((((((k 1) ^ 2) * sigma) - ((k 1) ^ 2)) + (((k 2) ^ 2) * sigma)) - ((k 2) ^ 2))) / (rho * sigma)) := by
  simp only [n27, Expr.eval, n26_eval, n19_eval]

def n28 : Expr Symbol := .scalar 1
theorem n28_dim : Expr.HasDim units n28 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 1) dimensions_zero.symm
theorem n28_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n28 = 1 := by
  rfl

def n29 : Expr Symbol := .scalar 2
theorem n29_dim : Expr.HasDim units n29 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2) dimensions_zero.symm
theorem n29_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n29 = 2 := by
  rfl

def n30 : Expr Symbol := .scalar 3
theorem n30_dim : Expr.HasDim units n30 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 3) dimensions_zero.symm
theorem n30_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n30 = 3 := by
  rfl

theorem q3_root_coincidence_equations_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n13 = referenceRoot rho mu sigma k 0 - referenceRoot rho mu sigma k 1 := by
  cas_eval n13_eval

theorem q3_root_coincidence_equations_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n20 = referenceRoot rho mu sigma k 0 - referenceRoot rho mu sigma k 2 := by
  cas_eval n20_eval

theorem q3_root_coincidence_equations_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n27 = referenceRoot rho mu sigma k 1 - referenceRoot rho mu sigma k 2 := by
  cas_eval n27_eval

theorem q3_root_coincidence_equations_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n13 = referenceRoot rho mu sigma k 0 - referenceRoot rho mu sigma k 1 ∧
    Expr.eval (values rho mu sigma z k) n20 = referenceRoot rho mu sigma k 0 - referenceRoot rho mu sigma k 2 ∧
    Expr.eval (values rho mu sigma z k) n27 = referenceRoot rho mu sigma k 1 - referenceRoot rho mu sigma k 2 :=
  ⟨q3_root_coincidence_equations_cell0 rho mu sigma z k h0 h1, q3_root_coincidence_equations_cell1 rho mu sigma z k h0 h1, q3_root_coincidence_equations_cell2 rho mu sigma z k h0 h1⟩

theorem q3_root_coincidence_equations_dimensions :
    Expr.HasDim units n13 (dimensions 0 (-2) 0) ∧
    Expr.HasDim units n20 (dimensions 0 (-2) 0) ∧
    Expr.HasDim units n27 (dimensions 0 (-2) 0) :=
  ⟨n13_dim, n20_dim, n27_dim⟩

theorem q3_root_coincidence_pair_indices_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n28 = 1 := by
  cas_eval n28_eval

theorem q3_root_coincidence_pair_indices_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n29 = 2 := by
  cas_eval n29_eval

theorem q3_root_coincidence_pair_indices_cell2 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n28 = 1 := by
  cas_eval n28_eval

theorem q3_root_coincidence_pair_indices_cell3 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n30 = 3 := by
  cas_eval n30_eval

theorem q3_root_coincidence_pair_indices_cell4 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n29 = 2 := by
  cas_eval n29_eval

theorem q3_root_coincidence_pair_indices_cell5 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n30 = 3 := by
  cas_eval n30_eval

theorem q3_root_coincidence_pair_indices_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n28 = 1 ∧
    Expr.eval (values rho mu sigma z k) n29 = 2 ∧
    Expr.eval (values rho mu sigma z k) n28 = 1 ∧
    Expr.eval (values rho mu sigma z k) n30 = 3 ∧
    Expr.eval (values rho mu sigma z k) n29 = 2 ∧
    Expr.eval (values rho mu sigma z k) n30 = 3 :=
  ⟨q3_root_coincidence_pair_indices_cell0 rho mu sigma z k, q3_root_coincidence_pair_indices_cell1 rho mu sigma z k, q3_root_coincidence_pair_indices_cell2 rho mu sigma z k, q3_root_coincidence_pair_indices_cell3 rho mu sigma z k, q3_root_coincidence_pair_indices_cell4 rho mu sigma z k, q3_root_coincidence_pair_indices_cell5 rho mu sigma z k⟩

theorem q3_root_coincidence_pair_indices_dimensions :
    Expr.HasDim units n28 (dimensions 0 0 0) ∧
    Expr.HasDim units n29 (dimensions 0 0 0) ∧
    Expr.HasDim units n28 (dimensions 0 0 0) ∧
    Expr.HasDim units n30 (dimensions 0 0 0) ∧
    Expr.HasDim units n29 (dimensions 0 0 0) ∧
    Expr.HasDim units n30 (dimensions 0 0 0) :=
  ⟨n28_dim, n29_dim, n28_dim, n30_dim, n29_dim, n30_dim⟩

end
end S10Audit.CAS.PYCoincidenceArithmeticGeneric
