-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 10ebaecb24b1ca92131566a37197f73cb9b93c8925299ec404838b50fdce75cf
import S10Audit.CAS.GenericCountReference

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.PYGenericCounts
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar 2
theorem n0_dim : Expr.HasDim units n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = 2 := by
  rfl

def n1 : Expr Symbol := .scalar 1
theorem n1_dim : Expr.HasDim units n1 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 1) dimensions_zero.symm
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  rfl

def n2 : Expr Symbol := .scalar 3
theorem n2_dim : Expr.HasDim units n2 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 3) dimensions_zero.symm
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = 3 := by
  rfl

def n3 : Expr Symbol := .scalar 0
theorem n3_dim : Expr.HasDim units n3 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 0) dimensions_zero.symm
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = 0 := by
  rfl

theorem root1_n2_rank_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 2 := by
  count_eval n0_eval

theorem root1_n2_rank_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 2 :=
  root1_n2_rank_cell0 rho mu sigma z k

theorem root1_n2_rank_dimensions :
    Expr.HasDim units n0 (dimensions 0 0 0) :=
  n0_dim

theorem root1_n2_nullity_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root1_n2_nullity_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root1_n2_nullity_cell0 rho mu sigma z k

theorem root1_n2_nullity_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root1_n3_stacked_rank_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n2 = 3 := by
  count_eval n2_eval

theorem root1_n3_stacked_rank_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n2 = 3 :=
  root1_n3_stacked_rank_cell0 rho mu sigma z k

theorem root1_n3_stacked_rank_dimensions :
    Expr.HasDim units n2 (dimensions 0 0 0) :=
  n2_dim

theorem root1_n3_transverse_nullity_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 := by
  count_eval n3_eval

theorem root1_n3_transverse_nullity_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 :=
  root1_n3_transverse_nullity_cell0 rho mu sigma z k

theorem root1_n3_transverse_nullity_dimensions :
    Expr.HasDim units n3 (dimensions 0 0 0) :=
  n3_dim

theorem root1_n4_nullity_difference_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root1_n4_nullity_difference_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root1_n4_nullity_difference_cell0 rho mu sigma z k

theorem root1_n4_nullity_difference_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root1_n7_basis_count_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root1_n7_basis_count_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root1_n7_basis_count_cell0 rho mu sigma z k

theorem root1_n7_basis_count_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root1_n7_basis_count_residual_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 := by
  count_eval n3_eval

theorem root1_n7_basis_count_residual_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 :=
  root1_n7_basis_count_residual_cell0 rho mu sigma z k

theorem root1_n7_basis_count_residual_dimensions :
    Expr.HasDim units n3 (dimensions 0 0 0) :=
  n3_dim

theorem root2_n2_rank_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 2 := by
  count_eval n0_eval

theorem root2_n2_rank_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 2 :=
  root2_n2_rank_cell0 rho mu sigma z k

theorem root2_n2_rank_dimensions :
    Expr.HasDim units n0 (dimensions 0 0 0) :=
  n0_dim

theorem root2_n2_nullity_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root2_n2_nullity_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root2_n2_nullity_cell0 rho mu sigma z k

theorem root2_n2_nullity_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root2_n3_stacked_rank_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 2 := by
  count_eval n0_eval

theorem root2_n3_stacked_rank_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 2 :=
  root2_n3_stacked_rank_cell0 rho mu sigma z k

theorem root2_n3_stacked_rank_dimensions :
    Expr.HasDim units n0 (dimensions 0 0 0) :=
  n0_dim

theorem root2_n3_transverse_nullity_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root2_n3_transverse_nullity_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root2_n3_transverse_nullity_cell0 rho mu sigma z k

theorem root2_n3_transverse_nullity_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root2_n4_nullity_difference_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 := by
  count_eval n3_eval

theorem root2_n4_nullity_difference_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 :=
  root2_n4_nullity_difference_cell0 rho mu sigma z k

theorem root2_n4_nullity_difference_dimensions :
    Expr.HasDim units n3 (dimensions 0 0 0) :=
  n3_dim

theorem root2_n7_basis_count_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root2_n7_basis_count_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root2_n7_basis_count_cell0 rho mu sigma z k

theorem root2_n7_basis_count_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root2_n7_basis_count_residual_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 := by
  count_eval n3_eval

theorem root2_n7_basis_count_residual_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 :=
  root2_n7_basis_count_residual_cell0 rho mu sigma z k

theorem root2_n7_basis_count_residual_dimensions :
    Expr.HasDim units n3 (dimensions 0 0 0) :=
  n3_dim

theorem root3_n2_rank_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 2 := by
  count_eval n0_eval

theorem root3_n2_rank_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 2 :=
  root3_n2_rank_cell0 rho mu sigma z k

theorem root3_n2_rank_dimensions :
    Expr.HasDim units n0 (dimensions 0 0 0) :=
  n0_dim

theorem root3_n2_nullity_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root3_n2_nullity_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root3_n2_nullity_cell0 rho mu sigma z k

theorem root3_n2_nullity_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root3_n3_stacked_rank_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n2 = 3 := by
  count_eval n2_eval

theorem root3_n3_stacked_rank_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n2 = 3 :=
  root3_n3_stacked_rank_cell0 rho mu sigma z k

theorem root3_n3_stacked_rank_dimensions :
    Expr.HasDim units n2 (dimensions 0 0 0) :=
  n2_dim

theorem root3_n3_transverse_nullity_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 := by
  count_eval n3_eval

theorem root3_n3_transverse_nullity_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 :=
  root3_n3_transverse_nullity_cell0 rho mu sigma z k

theorem root3_n3_transverse_nullity_dimensions :
    Expr.HasDim units n3 (dimensions 0 0 0) :=
  n3_dim

theorem root3_n4_nullity_difference_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root3_n4_nullity_difference_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root3_n4_nullity_difference_cell0 rho mu sigma z k

theorem root3_n4_nullity_difference_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root3_n7_basis_count_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  count_eval n1_eval

theorem root3_n7_basis_count_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 1 :=
  root3_n7_basis_count_cell0 rho mu sigma z k

theorem root3_n7_basis_count_dimensions :
    Expr.HasDim units n1 (dimensions 0 0 0) :=
  n1_dim

theorem root3_n7_basis_count_residual_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 := by
  count_eval n3_eval

theorem root3_n7_basis_count_residual_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n3 = 0 :=
  root3_n7_basis_count_residual_cell0 rho mu sigma z k

theorem root3_n7_basis_count_residual_dimensions :
    Expr.HasDim units n3 (dimensions 0 0 0) :=
  n3_dim

end
end S10Audit.CAS.PYGenericCounts
