-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 10ebaecb24b1ca92131566a37197f73cb9b93c8925299ec404838b50fdce75cf
import S10Audit.CAS.MinorSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.PYMinors
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .atom (.k 2)
theorem n0_dim : Expr.HasDim units n0 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 2)
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = (k 2) := by
  rfl

def n1 : Expr Symbol := .pow n0 2
theorem n1_dim : Expr.HasDim units n1 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n0_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = ((k 2) ^ 2) := by
  simp only [n1, Expr.eval, n0_eval]

def n2 : Expr Symbol := .atom .mu
theorem n2_dim : Expr.HasDim units n2 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := units) .mu
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = mu := by
  rfl

def n3 : Expr Symbol := .pow n2 2
theorem n3_dim : Expr.HasDim units n3 (dimensions (-2) (-4) 2) := by
  apply castDim (Expr.HasDim.pow 2 n2_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = (mu ^ 2) := by
  simp only [n3, Expr.eval, n2_eval]

def n4 : Expr Symbol := .mul n1 n3
theorem n4_dim : Expr.HasDim units n4 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n1_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = (((k 2) ^ 2) * (mu ^ 2)) := by
  simp only [n4, Expr.eval, n1_eval, n3_eval]

def n5 : Expr Symbol := .atom (.k 0)
theorem n5_dim : Expr.HasDim units n5 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 0)
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = (k 0) := by
  rfl

def n6 : Expr Symbol := .pow n5 2
theorem n6_dim : Expr.HasDim units n6 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n5_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = ((k 0) ^ 2) := by
  simp only [n6, Expr.eval, n5_eval]

def n7 : Expr Symbol := .atom (.k 1)
theorem n7_dim : Expr.HasDim units n7 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 1)
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = (k 1) := by
  rfl

def n8 : Expr Symbol := .pow n7 2
theorem n8_dim : Expr.HasDim units n8 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n7_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = ((k 1) ^ 2) := by
  simp only [n8, Expr.eval, n7_eval]

def n9 : Expr Symbol := .add n6 n8
theorem n9_dim : Expr.HasDim units n9 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n6_dim n8_dim
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = (((k 0) ^ 2) + ((k 1) ^ 2)) := by
  simp only [n9, Expr.eval, n6_eval, n8_eval]

def n10 : Expr Symbol := .add n9 n1
theorem n10_dim : Expr.HasDim units n10 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n9_dim n1_dim
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) := by
  simp only [n10, Expr.eval, n9_eval, n1_eval]

def n11 : Expr Symbol := .mul n4 n10
theorem n11_dim : Expr.HasDim units n11 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n4_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = ((((k 2) ^ 2) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n11, Expr.eval, n4_eval, n10_eval]

def n12 : Expr Symbol := .scalar 4
theorem n12_dim : Expr.HasDim units n12 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 4) dimensions_zero.symm
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = 4 := by
  rfl

def n13 : Expr Symbol := .div n11 n12
theorem n13_dim : Expr.HasDim units n13 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n11_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = (((((k 2) ^ 2) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n13, Expr.eval, n11_eval, n12_eval]

def n14 : Expr Symbol := .scalar (-1)
theorem n14_dim : Expr.HasDim units n14 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar (-1)) dimensions_zero.symm
theorem n14_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n14 = (-1) := by
  rfl

def n15 : Expr Symbol := .mul n14 n7
theorem n15_dim : Expr.HasDim units n15 (dimensions (-1) 0 0) := by
  apply castDim (Expr.HasDim.mul n14_dim n7_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n15_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n15 = ((-1) * (k 1)) := by
  simp only [n15, Expr.eval, n14_eval, n7_eval]

def n16 : Expr Symbol := .mul n15 n0
theorem n16_dim : Expr.HasDim units n16 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n15_dim n0_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n16_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n16 = (((-1) * (k 1)) * (k 2)) := by
  simp only [n16, Expr.eval, n15_eval, n0_eval]

def n17 : Expr Symbol := .mul n16 n3
theorem n17_dim : Expr.HasDim units n17 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n16_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n17_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n17 = ((((-1) * (k 1)) * (k 2)) * (mu ^ 2)) := by
  simp only [n17, Expr.eval, n16_eval, n3_eval]

def n18 : Expr Symbol := .mul n17 n10
theorem n18_dim : Expr.HasDim units n18 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n17_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n18_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n18 = (((((-1) * (k 1)) * (k 2)) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n18, Expr.eval, n17_eval, n10_eval]

def n19 : Expr Symbol := .div n18 n12
theorem n19_dim : Expr.HasDim units n19 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n18_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n19_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n19 = ((((((-1) * (k 1)) * (k 2)) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n19, Expr.eval, n18_eval, n12_eval]

def n20 : Expr Symbol := .mul n5 n0
theorem n20_dim : Expr.HasDim units n20 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n5_dim n0_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n20_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n20 = ((k 0) * (k 2)) := by
  simp only [n20, Expr.eval, n5_eval, n0_eval]

def n21 : Expr Symbol := .mul n20 n3
theorem n21_dim : Expr.HasDim units n21 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n20_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n21_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n21 = (((k 0) * (k 2)) * (mu ^ 2)) := by
  simp only [n21, Expr.eval, n20_eval, n3_eval]

def n22 : Expr Symbol := .mul n21 n10
theorem n22_dim : Expr.HasDim units n22 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n21_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n22_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n22 = ((((k 0) * (k 2)) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n22, Expr.eval, n21_eval, n10_eval]

def n23 : Expr Symbol := .div n22 n12
theorem n23_dim : Expr.HasDim units n23 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n22_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n23_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n23 = (((((k 0) * (k 2)) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n23, Expr.eval, n22_eval, n12_eval]

def n24 : Expr Symbol := .mul n8 n3
theorem n24_dim : Expr.HasDim units n24 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n8_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n24_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n24 = (((k 1) ^ 2) * (mu ^ 2)) := by
  simp only [n24, Expr.eval, n8_eval, n3_eval]

def n25 : Expr Symbol := .mul n24 n10
theorem n25_dim : Expr.HasDim units n25 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n24_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n25_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n25 = ((((k 1) ^ 2) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n25, Expr.eval, n24_eval, n10_eval]

def n26 : Expr Symbol := .div n25 n12
theorem n26_dim : Expr.HasDim units n26 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n25_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n26_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n26 = (((((k 1) ^ 2) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n26, Expr.eval, n25_eval, n12_eval]

def n27 : Expr Symbol := .mul n14 n5
theorem n27_dim : Expr.HasDim units n27 (dimensions (-1) 0 0) := by
  apply castDim (Expr.HasDim.mul n14_dim n5_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n27_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n27 = ((-1) * (k 0)) := by
  simp only [n27, Expr.eval, n14_eval, n5_eval]

def n28 : Expr Symbol := .mul n27 n7
theorem n28_dim : Expr.HasDim units n28 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n27_dim n7_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n28_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n28 = (((-1) * (k 0)) * (k 1)) := by
  simp only [n28, Expr.eval, n27_eval, n7_eval]

def n29 : Expr Symbol := .mul n28 n3
theorem n29_dim : Expr.HasDim units n29 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n28_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n29_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n29 = ((((-1) * (k 0)) * (k 1)) * (mu ^ 2)) := by
  simp only [n29, Expr.eval, n28_eval, n3_eval]

def n30 : Expr Symbol := .mul n29 n10
theorem n30_dim : Expr.HasDim units n30 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n29_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n30_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n30 = (((((-1) * (k 0)) * (k 1)) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n30, Expr.eval, n29_eval, n10_eval]

def n31 : Expr Symbol := .div n30 n12
theorem n31_dim : Expr.HasDim units n31 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n30_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n31_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n31 = ((((((-1) * (k 0)) * (k 1)) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n31, Expr.eval, n30_eval, n12_eval]

def n32 : Expr Symbol := .mul n6 n3
theorem n32_dim : Expr.HasDim units n32 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n6_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n32_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n32 = (((k 0) ^ 2) * (mu ^ 2)) := by
  simp only [n32, Expr.eval, n6_eval, n3_eval]

def n33 : Expr Symbol := .mul n32 n10
theorem n33_dim : Expr.HasDim units n33 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n32_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n33_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n33 = ((((k 0) ^ 2) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n33, Expr.eval, n32_eval, n10_eval]

def n34 : Expr Symbol := .div n33 n12
theorem n34_dim : Expr.HasDim units n34 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n33_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n34_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n34 = (((((k 0) ^ 2) * (mu ^ 2)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n34, Expr.eval, n33_eval, n12_eval]

def n35 : Expr Symbol := .scalar 0
theorem n35_dim : Expr.HasDim units n35 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 0) dimensions_zero.symm
theorem n35_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n35 = 0 := by
  rfl

def n36 : Expr Symbol := .scalar 1
theorem n36_dim : Expr.HasDim units n36 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 1) dimensions_zero.symm
theorem n36_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n36 = 1 := by
  rfl

def n37 : Expr Symbol := .atom .rho
theorem n37_dim : Expr.HasDim units n37 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := units) .rho
theorem n37_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n37 = rho := by
  rfl

def n38 : Expr Symbol := .pow n37 3
theorem n38_dim : Expr.HasDim units n38 (dimensions (-9) 0 3) := by
  apply castDim (Expr.HasDim.pow 3 n37_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n38_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n38 = (rho ^ 3) := by
  simp only [n38, Expr.eval, n37_eval]

def n39 : Expr Symbol := .mul n36 n38
theorem n39_dim : Expr.HasDim units n39 (dimensions (-9) 0 3) := by
  apply castDim (Expr.HasDim.mul n36_dim n38_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n39_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n39 = (1 * (rho ^ 3)) := by
  simp only [n39, Expr.eval, n36_eval, n38_eval]

def n40 : Expr Symbol := .atom .z
theorem n40_dim : Expr.HasDim units n40 (dimensions 0 (-2) 0) := by
  exact Expr.HasDim.atom (u := units) .z
theorem n40_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n40 = z := by
  rfl

def n41 : Expr Symbol := .pow n40 3
theorem n41_dim : Expr.HasDim units n41 (dimensions 0 (-6) 0) := by
  apply castDim (Expr.HasDim.pow 3 n40_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n41_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n41 = (z ^ 3) := by
  simp only [n41, Expr.eval, n40_eval]

def n42 : Expr Symbol := .mul n39 n41
theorem n42_dim : Expr.HasDim units n42 (dimensions (-9) (-6) 3) := by
  apply castDim (Expr.HasDim.mul n39_dim n41_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n42_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n42 = ((1 * (rho ^ 3)) * (z ^ 3)) := by
  simp only [n42, Expr.eval, n39_eval, n41_eval]

def n43 : Expr Symbol := .mul n35 n42
theorem n43_dim : Expr.HasDim units n43 (dimensions (-9) (-6) 3) := by
  apply castDim (Expr.HasDim.mul n35_dim n42_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n43_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n43 = (0 * ((1 * (rho ^ 3)) * (z ^ 3))) := by
  simp only [n43, Expr.eval, n35_eval, n42_eval]

def n44 : Expr Symbol := .mul n0 n3
theorem n44_dim : Expr.HasDim units n44 (dimensions (-3) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n0_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n44_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n44 = ((k 2) * (mu ^ 2)) := by
  simp only [n44, Expr.eval, n0_eval, n3_eval]

def n45 : Expr Symbol := .pow n10 2
theorem n45_dim : Expr.HasDim units n45 (dimensions (-4) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n10_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n45_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n45 = (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) ^ 2) := by
  simp only [n45, Expr.eval, n10_eval]

def n46 : Expr Symbol := .mul n44 n45
theorem n46_dim : Expr.HasDim units n46 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n44_dim n45_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n46_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n46 = (((k 2) * (mu ^ 2)) * (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) ^ 2)) := by
  simp only [n46, Expr.eval, n44_eval, n45_eval]

def n47 : Expr Symbol := .div n46 n12
theorem n47_dim : Expr.HasDim units n47 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.div n46_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n47_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n47 = ((((k 2) * (mu ^ 2)) * (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) ^ 2)) / 4) := by
  simp only [n47, Expr.eval, n46_eval, n12_eval]

def n48 : Expr Symbol := .mul n15 n3
theorem n48_dim : Expr.HasDim units n48 (dimensions (-3) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n15_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n48_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n48 = (((-1) * (k 1)) * (mu ^ 2)) := by
  simp only [n48, Expr.eval, n15_eval, n3_eval]

def n49 : Expr Symbol := .mul n48 n45
theorem n49_dim : Expr.HasDim units n49 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n48_dim n45_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n49_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n49 = ((((-1) * (k 1)) * (mu ^ 2)) * (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) ^ 2)) := by
  simp only [n49, Expr.eval, n48_eval, n45_eval]

def n50 : Expr Symbol := .div n49 n12
theorem n50_dim : Expr.HasDim units n50 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.div n49_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n50_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n50 = (((((-1) * (k 1)) * (mu ^ 2)) * (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) ^ 2)) / 4) := by
  simp only [n50, Expr.eval, n49_eval, n12_eval]

def n51 : Expr Symbol := .mul n5 n3
theorem n51_dim : Expr.HasDim units n51 (dimensions (-3) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n5_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n51_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n51 = ((k 0) * (mu ^ 2)) := by
  simp only [n51, Expr.eval, n5_eval, n3_eval]

def n52 : Expr Symbol := .mul n51 n45
theorem n52_dim : Expr.HasDim units n52 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n51_dim n45_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n52_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n52 = (((k 0) * (mu ^ 2)) * (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) ^ 2)) := by
  simp only [n52, Expr.eval, n51_eval, n45_eval]

def n53 : Expr Symbol := .div n52 n12
theorem n53_dim : Expr.HasDim units n53 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.div n52_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n53_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n53 = ((((k 0) * (mu ^ 2)) * (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) ^ 2)) / 4) := by
  simp only [n53, Expr.eval, n52_eval, n12_eval]

def n54 : Expr Symbol := .atom .sigma
theorem n54_dim : Expr.HasDim units n54 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := units) .sigma
theorem n54_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n54 = sigma := by
  rfl

def n55 : Expr Symbol := .sub n54 n36
theorem n55_dim : Expr.HasDim units n55 (dimensions 0 0 0) := by
  exact Expr.HasDim.sub n54_dim n36_dim
theorem n55_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n55 = (sigma - 1) := by
  simp only [n55, Expr.eval, n54_eval, n36_eval]

def n56 : Expr Symbol := .mul n24 n55
theorem n56_dim : Expr.HasDim units n56 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n24_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n56_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n56 = ((((k 1) ^ 2) * (mu ^ 2)) * (sigma - 1)) := by
  simp only [n56, Expr.eval, n24_eval, n55_eval]

def n57 : Expr Symbol := .mul n56 n10
theorem n57_dim : Expr.HasDim units n57 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n56_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n57_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n57 = (((((k 1) ^ 2) * (mu ^ 2)) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n57, Expr.eval, n56_eval, n10_eval]

def n58 : Expr Symbol := .div n57 n12
theorem n58_dim : Expr.HasDim units n58 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n57_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n58_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n58 = ((((((k 1) ^ 2) * (mu ^ 2)) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n58, Expr.eval, n57_eval, n12_eval]

def n59 : Expr Symbol := .mul n7 n0
theorem n59_dim : Expr.HasDim units n59 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n7_dim n0_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n59_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n59 = ((k 1) * (k 2)) := by
  simp only [n59, Expr.eval, n7_eval, n0_eval]

def n60 : Expr Symbol := .mul n59 n3
theorem n60_dim : Expr.HasDim units n60 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n59_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n60_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n60 = (((k 1) * (k 2)) * (mu ^ 2)) := by
  simp only [n60, Expr.eval, n59_eval, n3_eval]

def n61 : Expr Symbol := .mul n60 n55
theorem n61_dim : Expr.HasDim units n61 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n60_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n61_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n61 = ((((k 1) * (k 2)) * (mu ^ 2)) * (sigma - 1)) := by
  simp only [n61, Expr.eval, n60_eval, n55_eval]

def n62 : Expr Symbol := .mul n61 n10
theorem n62_dim : Expr.HasDim units n62 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n61_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n62_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n62 = (((((k 1) * (k 2)) * (mu ^ 2)) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n62, Expr.eval, n61_eval, n10_eval]

def n63 : Expr Symbol := .div n62 n12
theorem n63_dim : Expr.HasDim units n63 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n62_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n63_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n63 = ((((((k 1) * (k 2)) * (mu ^ 2)) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n63, Expr.eval, n62_eval, n12_eval]

def n64 : Expr Symbol := .pow n37 2
theorem n64_dim : Expr.HasDim units n64 (dimensions (-6) 0 2) := by
  apply castDim (Expr.HasDim.pow 2 n37_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n64_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n64 = (rho ^ 2) := by
  simp only [n64, Expr.eval, n37_eval]

def n65 : Expr Symbol := .mul n36 n64
theorem n65_dim : Expr.HasDim units n65 (dimensions (-6) 0 2) := by
  apply castDim (Expr.HasDim.mul n36_dim n64_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n65_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n65 = (1 * (rho ^ 2)) := by
  simp only [n65, Expr.eval, n36_eval, n64_eval]

def n66 : Expr Symbol := .pow n40 2
theorem n66_dim : Expr.HasDim units n66 (dimensions 0 (-4) 0) := by
  apply castDim (Expr.HasDim.pow 2 n40_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n66_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n66 = (z ^ 2) := by
  simp only [n66, Expr.eval, n40_eval]

def n67 : Expr Symbol := .mul n65 n66
theorem n67_dim : Expr.HasDim units n67 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n65_dim n66_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n67_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n67 = ((1 * (rho ^ 2)) * (z ^ 2)) := by
  simp only [n67, Expr.eval, n65_eval, n66_eval]

def n68 : Expr Symbol := .mul n35 n67
theorem n68_dim : Expr.HasDim units n68 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n35_dim n67_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n68_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n68 = (0 * ((1 * (rho ^ 2)) * (z ^ 2))) := by
  simp only [n68, Expr.eval, n35_eval, n67_eval]

def n69 : Expr Symbol := .mul n4 n55
theorem n69_dim : Expr.HasDim units n69 (dimensions (-4) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n4_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n69_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n69 = ((((k 2) ^ 2) * (mu ^ 2)) * (sigma - 1)) := by
  simp only [n69, Expr.eval, n4_eval, n55_eval]

def n70 : Expr Symbol := .mul n69 n10
theorem n70_dim : Expr.HasDim units n70 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n69_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n70_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n70 = (((((k 2) ^ 2) * (mu ^ 2)) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n70, Expr.eval, n69_eval, n10_eval]

def n71 : Expr Symbol := .div n70 n12
theorem n71_dim : Expr.HasDim units n71 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n70_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n71_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n71 = ((((((k 2) ^ 2) * (mu ^ 2)) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 4) := by
  simp only [n71, Expr.eval, n70_eval, n12_eval]

def n72 : Expr Symbol := .mul n7 n2
theorem n72_dim : Expr.HasDim units n72 (dimensions (-2) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n7_dim n2_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n72_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n72 = ((k 1) * mu) := by
  simp only [n72, Expr.eval, n7_eval, n2_eval]

def n73 : Expr Symbol := .mul n72 n55
theorem n73_dim : Expr.HasDim units n73 (dimensions (-2) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n72_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n73_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n73 = (((k 1) * mu) * (sigma - 1)) := by
  simp only [n73, Expr.eval, n72_eval, n55_eval]

def n74 : Expr Symbol := .mul n73 n10
theorem n74_dim : Expr.HasDim units n74 (dimensions (-4) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n73_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n74_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n74 = ((((k 1) * mu) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n74, Expr.eval, n73_eval, n10_eval]

def n75 : Expr Symbol := .scalar 2
theorem n75_dim : Expr.HasDim units n75 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2) dimensions_zero.symm
theorem n75_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n75 = 2 := by
  rfl

def n76 : Expr Symbol := .div n74 n75
theorem n76_dim : Expr.HasDim units n76 (dimensions (-4) (-2) 1) := by
  apply castDim (Expr.HasDim.div n74_dim n75_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n76_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n76 = (((((k 1) * mu) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 2) := by
  simp only [n76, Expr.eval, n74_eval, n75_eval]

def n77 : Expr Symbol := .mul n0 n2
theorem n77_dim : Expr.HasDim units n77 (dimensions (-2) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n0_dim n2_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n77_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n77 = ((k 2) * mu) := by
  simp only [n77, Expr.eval, n0_eval, n2_eval]

def n78 : Expr Symbol := .mul n77 n55
theorem n78_dim : Expr.HasDim units n78 (dimensions (-2) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n77_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n78_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n78 = (((k 2) * mu) * (sigma - 1)) := by
  simp only [n78, Expr.eval, n77_eval, n55_eval]

def n79 : Expr Symbol := .mul n78 n10
theorem n79_dim : Expr.HasDim units n79 (dimensions (-4) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n78_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n79_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n79 = ((((k 2) * mu) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) := by
  simp only [n79, Expr.eval, n78_eval, n10_eval]

def n80 : Expr Symbol := .div n79 n75
theorem n80_dim : Expr.HasDim units n80 (dimensions (-4) (-2) 1) := by
  apply castDim (Expr.HasDim.div n79_dim n75_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n80_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n80 = (((((k 2) * mu) * (sigma - 1)) * ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2))) / 2) := by
  simp only [n80, Expr.eval, n79_eval, n75_eval]

def n81 : Expr Symbol := .mul n14 n6
theorem n81_dim : Expr.HasDim units n81 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n14_dim n6_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n81_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n81 = ((-1) * ((k 0) ^ 2)) := by
  simp only [n81, Expr.eval, n14_eval, n6_eval]

def n82 : Expr Symbol := .mul n81 n1
theorem n82_dim : Expr.HasDim units n82 (dimensions (-4) 0 0) := by
  apply castDim (Expr.HasDim.mul n81_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n82_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n82 = (((-1) * ((k 0) ^ 2)) * ((k 2) ^ 2)) := by
  simp only [n82, Expr.eval, n81_eval, n1_eval]

def n83 : Expr Symbol := .mul n82 n3
theorem n83_dim : Expr.HasDim units n83 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n82_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n83_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n83 = ((((-1) * ((k 0) ^ 2)) * ((k 2) ^ 2)) * (mu ^ 2)) := by
  simp only [n83, Expr.eval, n82_eval, n3_eval]

def n84 : Expr Symbol := .mul n83 n55
theorem n84_dim : Expr.HasDim units n84 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n83_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n84_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n84 = (((((-1) * ((k 0) ^ 2)) * ((k 2) ^ 2)) * (mu ^ 2)) * (sigma - 1)) := by
  simp only [n84, Expr.eval, n83_eval, n55_eval]

def n85 : Expr Symbol := .div n84 n12
theorem n85_dim : Expr.HasDim units n85 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n84_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n85_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n85 = ((((((-1) * ((k 0) ^ 2)) * ((k 2) ^ 2)) * (mu ^ 2)) * (sigma - 1)) / 4) := by
  simp only [n85, Expr.eval, n84_eval, n12_eval]

def n86 : Expr Symbol := .mul n6 n7
theorem n86_dim : Expr.HasDim units n86 (dimensions (-3) 0 0) := by
  apply castDim (Expr.HasDim.mul n6_dim n7_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n86_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n86 = (((k 0) ^ 2) * (k 1)) := by
  simp only [n86, Expr.eval, n6_eval, n7_eval]

def n87 : Expr Symbol := .mul n86 n0
theorem n87_dim : Expr.HasDim units n87 (dimensions (-4) 0 0) := by
  apply castDim (Expr.HasDim.mul n86_dim n0_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n87_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n87 = ((((k 0) ^ 2) * (k 1)) * (k 2)) := by
  simp only [n87, Expr.eval, n86_eval, n0_eval]

def n88 : Expr Symbol := .mul n87 n3
theorem n88_dim : Expr.HasDim units n88 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n87_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n88_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n88 = (((((k 0) ^ 2) * (k 1)) * (k 2)) * (mu ^ 2)) := by
  simp only [n88, Expr.eval, n87_eval, n3_eval]

def n89 : Expr Symbol := .mul n88 n55
theorem n89_dim : Expr.HasDim units n89 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n88_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n89_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n89 = ((((((k 0) ^ 2) * (k 1)) * (k 2)) * (mu ^ 2)) * (sigma - 1)) := by
  simp only [n89, Expr.eval, n88_eval, n55_eval]

def n90 : Expr Symbol := .div n89 n12
theorem n90_dim : Expr.HasDim units n90 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n89_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n90_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n90 = (((((((k 0) ^ 2) * (k 1)) * (k 2)) * (mu ^ 2)) * (sigma - 1)) / 4) := by
  simp only [n90, Expr.eval, n89_eval, n12_eval]

def n91 : Expr Symbol := .add n8 n1
theorem n91_dim : Expr.HasDim units n91 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n8_dim n1_dim
theorem n91_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n91 = (((k 1) ^ 2) + ((k 2) ^ 2)) := by
  simp only [n91, Expr.eval, n8_eval, n1_eval]

def n92 : Expr Symbol := .mul n21 n91
theorem n92_dim : Expr.HasDim units n92 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n21_dim n91_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n92_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n92 = ((((k 0) * (k 2)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) := by
  simp only [n92, Expr.eval, n21_eval, n91_eval]

def n93 : Expr Symbol := .mul n92 n55
theorem n93_dim : Expr.HasDim units n93 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n92_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n93_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n93 = (((((k 0) * (k 2)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) * (sigma - 1)) := by
  simp only [n93, Expr.eval, n92_eval, n55_eval]

def n94 : Expr Symbol := .mul n12 n54
theorem n94_dim : Expr.HasDim units n94 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.mul n12_dim n54_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n94_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n94 = (4 * sigma) := by
  simp only [n94, Expr.eval, n12_eval, n54_eval]

def n95 : Expr Symbol := .div n93 n94
theorem n95_dim : Expr.HasDim units n95 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n93_dim n94_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n95_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n95 = ((((((k 0) * (k 2)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) * (sigma - 1)) / (4 * sigma)) := by
  simp only [n95, Expr.eval, n93_eval, n94_eval]

def n96 : Expr Symbol := .mul n81 n8
theorem n96_dim : Expr.HasDim units n96 (dimensions (-4) 0 0) := by
  apply castDim (Expr.HasDim.mul n81_dim n8_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n96_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n96 = (((-1) * ((k 0) ^ 2)) * ((k 1) ^ 2)) := by
  simp only [n96, Expr.eval, n81_eval, n8_eval]

def n97 : Expr Symbol := .mul n96 n3
theorem n97_dim : Expr.HasDim units n97 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n96_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n97_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n97 = ((((-1) * ((k 0) ^ 2)) * ((k 1) ^ 2)) * (mu ^ 2)) := by
  simp only [n97, Expr.eval, n96_eval, n3_eval]

def n98 : Expr Symbol := .mul n97 n55
theorem n98_dim : Expr.HasDim units n98 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n97_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n98_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n98 = (((((-1) * ((k 0) ^ 2)) * ((k 1) ^ 2)) * (mu ^ 2)) * (sigma - 1)) := by
  simp only [n98, Expr.eval, n97_eval, n55_eval]

def n99 : Expr Symbol := .div n98 n12
theorem n99_dim : Expr.HasDim units n99 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n98_dim n12_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n99_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n99 = ((((((-1) * ((k 0) ^ 2)) * ((k 1) ^ 2)) * (mu ^ 2)) * (sigma - 1)) / 4) := by
  simp only [n99, Expr.eval, n98_eval, n12_eval]

def n100 : Expr Symbol := .mul n29 n91
theorem n100_dim : Expr.HasDim units n100 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n29_dim n91_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n100_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n100 = (((((-1) * (k 0)) * (k 1)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) := by
  simp only [n100, Expr.eval, n29_eval, n91_eval]

def n101 : Expr Symbol := .mul n100 n55
theorem n101_dim : Expr.HasDim units n101 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n100_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n101_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n101 = ((((((-1) * (k 0)) * (k 1)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) * (sigma - 1)) := by
  simp only [n101, Expr.eval, n100_eval, n55_eval]

def n102 : Expr Symbol := .div n101 n94
theorem n102_dim : Expr.HasDim units n102 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n101_dim n94_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n102_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n102 = (((((((-1) * (k 0)) * (k 1)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) * (sigma - 1)) / (4 * sigma)) := by
  simp only [n102, Expr.eval, n101_eval, n94_eval]

def n103 : Expr Symbol := .mul n14 n3
theorem n103_dim : Expr.HasDim units n103 (dimensions (-2) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n14_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n103_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n103 = ((-1) * (mu ^ 2)) := by
  simp only [n103, Expr.eval, n14_eval, n3_eval]

def n104 : Expr Symbol := .pow n91 2
theorem n104_dim : Expr.HasDim units n104 (dimensions (-4) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n91_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n104_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n104 = ((((k 1) ^ 2) + ((k 2) ^ 2)) ^ 2) := by
  simp only [n104, Expr.eval, n91_eval]

def n105 : Expr Symbol := .mul n103 n104
theorem n105_dim : Expr.HasDim units n105 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n103_dim n104_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n105_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n105 = (((-1) * (mu ^ 2)) * ((((k 1) ^ 2) + ((k 2) ^ 2)) ^ 2)) := by
  simp only [n105, Expr.eval, n103_eval, n104_eval]

def n106 : Expr Symbol := .mul n105 n55
theorem n106_dim : Expr.HasDim units n106 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n105_dim n55_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n106_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n106 = ((((-1) * (mu ^ 2)) * ((((k 1) ^ 2) + ((k 2) ^ 2)) ^ 2)) * (sigma - 1)) := by
  simp only [n106, Expr.eval, n105_eval, n55_eval]

def n107 : Expr Symbol := .pow n54 2
theorem n107_dim : Expr.HasDim units n107 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n54_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n107_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n107 = (sigma ^ 2) := by
  simp only [n107, Expr.eval, n54_eval]

def n108 : Expr Symbol := .mul n12 n107
theorem n108_dim : Expr.HasDim units n108 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.mul n12_dim n107_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n108_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n108 = (4 * (sigma ^ 2)) := by
  simp only [n108, Expr.eval, n12_eval, n107_eval]

def n109 : Expr Symbol := .div n106 n108
theorem n109_dim : Expr.HasDim units n109 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.div n106_dim n108_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n109_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n109 = (((((-1) * (mu ^ 2)) * ((((k 1) ^ 2) + ((k 2) ^ 2)) ^ 2)) * (sigma - 1)) / (4 * (sigma ^ 2))) := by
  simp only [n109, Expr.eval, n106_eval, n108_eval]

def n110 : Expr Symbol := .mul n81 n0
theorem n110_dim : Expr.HasDim units n110 (dimensions (-3) 0 0) := by
  apply castDim (Expr.HasDim.mul n81_dim n0_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n110_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n110 = (((-1) * ((k 0) ^ 2)) * (k 2)) := by
  simp only [n110, Expr.eval, n81_eval, n0_eval]

def n111 : Expr Symbol := .mul n110 n3
theorem n111_dim : Expr.HasDim units n111 (dimensions (-5) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n110_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n111_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n111 = ((((-1) * ((k 0) ^ 2)) * (k 2)) * (mu ^ 2)) := by
  simp only [n111, Expr.eval, n110_eval, n3_eval]

def n112 : Expr Symbol := .mul n111 n91
theorem n112_dim : Expr.HasDim units n112 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n111_dim n91_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n112_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n112 = (((((-1) * ((k 0) ^ 2)) * (k 2)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) := by
  simp only [n112, Expr.eval, n111_eval, n91_eval]

def n113 : Expr Symbol := .pow n55 2
theorem n113_dim : Expr.HasDim units n113 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n55_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n113_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n113 = ((sigma - 1) ^ 2) := by
  simp only [n113, Expr.eval, n55_eval]

def n114 : Expr Symbol := .mul n112 n113
theorem n114_dim : Expr.HasDim units n114 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n112_dim n113_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n114_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n114 = ((((((-1) * ((k 0) ^ 2)) * (k 2)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) * ((sigma - 1) ^ 2)) := by
  simp only [n114, Expr.eval, n112_eval, n113_eval]

def n115 : Expr Symbol := .div n114 n94
theorem n115_dim : Expr.HasDim units n115 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.div n114_dim n94_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n115_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n115 = (((((((-1) * ((k 0) ^ 2)) * (k 2)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) * ((sigma - 1) ^ 2)) / (4 * sigma)) := by
  simp only [n115, Expr.eval, n114_eval, n94_eval]

def n116 : Expr Symbol := .mul n86 n3
theorem n116_dim : Expr.HasDim units n116 (dimensions (-5) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n86_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n116_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n116 = ((((k 0) ^ 2) * (k 1)) * (mu ^ 2)) := by
  simp only [n116, Expr.eval, n86_eval, n3_eval]

def n117 : Expr Symbol := .mul n116 n91
theorem n117_dim : Expr.HasDim units n117 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n116_dim n91_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n117_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n117 = (((((k 0) ^ 2) * (k 1)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) := by
  simp only [n117, Expr.eval, n116_eval, n91_eval]

def n118 : Expr Symbol := .mul n117 n113
theorem n118_dim : Expr.HasDim units n118 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n117_dim n113_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n118_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n118 = ((((((k 0) ^ 2) * (k 1)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) * ((sigma - 1) ^ 2)) := by
  simp only [n118, Expr.eval, n117_eval, n113_eval]

def n119 : Expr Symbol := .div n118 n94
theorem n119_dim : Expr.HasDim units n119 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.div n118_dim n94_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n119_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n119 = (((((((k 0) ^ 2) * (k 1)) * (mu ^ 2)) * (((k 1) ^ 2) + ((k 2) ^ 2))) * ((sigma - 1) ^ 2)) / (4 * sigma)) := by
  simp only [n119, Expr.eval, n118_eval, n94_eval]

def n120 : Expr Symbol := .mul n51 n104
theorem n120_dim : Expr.HasDim units n120 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n51_dim n104_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n120_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n120 = (((k 0) * (mu ^ 2)) * ((((k 1) ^ 2) + ((k 2) ^ 2)) ^ 2)) := by
  simp only [n120, Expr.eval, n51_eval, n104_eval]

def n121 : Expr Symbol := .mul n120 n113
theorem n121_dim : Expr.HasDim units n121 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n120_dim n113_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n121_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n121 = ((((k 0) * (mu ^ 2)) * ((((k 1) ^ 2) + ((k 2) ^ 2)) ^ 2)) * ((sigma - 1) ^ 2)) := by
  simp only [n121, Expr.eval, n120_eval, n113_eval]

def n122 : Expr Symbol := .div n121 n108
theorem n122_dim : Expr.HasDim units n122 (dimensions (-7) (-4) 2) := by
  apply castDim (Expr.HasDim.div n121_dim n108_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n122_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n122 = (((((k 0) * (mu ^ 2)) * ((((k 1) ^ 2) + ((k 2) ^ 2)) ^ 2)) * ((sigma - 1) ^ 2)) / (4 * (sigma ^ 2))) := by
  simp only [n122, Expr.eval, n121_eval, n108_eval]

theorem root1_q8_rank_drop_minors_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = staticRankMinors mu k 0 := by
  minor_eval n13_eval

theorem root1_q8_rank_drop_minors_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n19 = staticRankMinors mu k 1 := by
  minor_eval n19_eval

theorem root1_q8_rank_drop_minors_cell2 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n23 = staticRankMinors mu k 2 := by
  minor_eval n23_eval

theorem root1_q8_rank_drop_minors_cell3 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n26 = staticRankMinors mu k 3 := by
  minor_eval n26_eval

theorem root1_q8_rank_drop_minors_cell4 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n31 = staticRankMinors mu k 4 := by
  minor_eval n31_eval

theorem root1_q8_rank_drop_minors_cell5 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n34 = staticRankMinors mu k 5 := by
  minor_eval n34_eval

theorem root1_q8_rank_drop_minors_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = staticRankMinors mu k 0 ∧
    Expr.eval (values rho mu sigma z k) n19 = staticRankMinors mu k 1 ∧
    Expr.eval (values rho mu sigma z k) n23 = staticRankMinors mu k 2 ∧
    Expr.eval (values rho mu sigma z k) n26 = staticRankMinors mu k 3 ∧
    Expr.eval (values rho mu sigma z k) n31 = staticRankMinors mu k 4 ∧
    Expr.eval (values rho mu sigma z k) n34 = staticRankMinors mu k 5 :=
  ⟨root1_q8_rank_drop_minors_cell0 rho mu sigma z k, root1_q8_rank_drop_minors_cell1 rho mu sigma z k, root1_q8_rank_drop_minors_cell2 rho mu sigma z k, root1_q8_rank_drop_minors_cell3 rho mu sigma z k, root1_q8_rank_drop_minors_cell4 rho mu sigma z k, root1_q8_rank_drop_minors_cell5 rho mu sigma z k⟩

theorem root1_q8_rank_drop_minors_dimensions :
    Expr.HasDim units n13 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n19 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n23 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n26 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n31 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n34 (dimensions (-6) (-4) 2) :=
  ⟨n13_dim, n19_dim, n23_dim, n26_dim, n31_dim, n34_dim⟩

theorem root1_q8_transverse_rank_drop_minors_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n43 = staticTransverseMinors mu k 0 := by
  minor_eval n43_eval

theorem root1_q8_transverse_rank_drop_minors_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n47 = staticTransverseMinors mu k 1 := by
  minor_eval n47_eval

theorem root1_q8_transverse_rank_drop_minors_cell2 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n50 = staticTransverseMinors mu k 2 := by
  minor_eval n50_eval

theorem root1_q8_transverse_rank_drop_minors_cell3 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n53 = staticTransverseMinors mu k 3 := by
  minor_eval n53_eval

theorem root1_q8_transverse_rank_drop_minors_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n43 = staticTransverseMinors mu k 0 ∧
    Expr.eval (values rho mu sigma z k) n47 = staticTransverseMinors mu k 1 ∧
    Expr.eval (values rho mu sigma z k) n50 = staticTransverseMinors mu k 2 ∧
    Expr.eval (values rho mu sigma z k) n53 = staticTransverseMinors mu k 3 :=
  ⟨root1_q8_transverse_rank_drop_minors_cell0 rho mu sigma z k, root1_q8_transverse_rank_drop_minors_cell1 rho mu sigma z k, root1_q8_transverse_rank_drop_minors_cell2 rho mu sigma z k, root1_q8_transverse_rank_drop_minors_cell3 rho mu sigma z k⟩

theorem root1_q8_transverse_rank_drop_minors_dimensions :
    Expr.HasDim units n43 (dimensions (-9) (-6) 3) ∧
    Expr.HasDim units n47 (dimensions (-7) (-4) 2) ∧
    Expr.HasDim units n50 (dimensions (-7) (-4) 2) ∧
    Expr.HasDim units n53 (dimensions (-7) (-4) 2) :=
  ⟨n43_dim, n47_dim, n50_dim, n53_dim⟩

theorem root2_q8_rank_drop_minors_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n58 = ordinaryRankMinors mu sigma k 0 := by
  minor_eval n58_eval

theorem root2_q8_rank_drop_minors_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n63 = ordinaryRankMinors mu sigma k 1 := by
  minor_eval n63_eval

theorem root2_q8_rank_drop_minors_cell2 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n68 = ordinaryRankMinors mu sigma k 2 := by
  minor_eval n68_eval

theorem root2_q8_rank_drop_minors_cell3 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n71 = ordinaryRankMinors mu sigma k 3 := by
  minor_eval n71_eval

theorem root2_q8_rank_drop_minors_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n58 = ordinaryRankMinors mu sigma k 0 ∧
    Expr.eval (values rho mu sigma z k) n63 = ordinaryRankMinors mu sigma k 1 ∧
    Expr.eval (values rho mu sigma z k) n68 = ordinaryRankMinors mu sigma k 2 ∧
    Expr.eval (values rho mu sigma z k) n71 = ordinaryRankMinors mu sigma k 3 :=
  ⟨root2_q8_rank_drop_minors_cell0 rho mu sigma z k, root2_q8_rank_drop_minors_cell1 rho mu sigma z k, root2_q8_rank_drop_minors_cell2 rho mu sigma z k, root2_q8_rank_drop_minors_cell3 rho mu sigma z k⟩

theorem root2_q8_rank_drop_minors_dimensions :
    Expr.HasDim units n58 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n63 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n68 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n71 (dimensions (-6) (-4) 2) :=
  ⟨n58_dim, n63_dim, n68_dim, n71_dim⟩

theorem root2_q8_transverse_rank_drop_minors_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n58 = ordinaryTransverseMinors mu sigma k 0 := by
  minor_eval n58_eval

theorem root2_q8_transverse_rank_drop_minors_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n63 = ordinaryTransverseMinors mu sigma k 1 := by
  minor_eval n63_eval

theorem root2_q8_transverse_rank_drop_minors_cell2 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n68 = ordinaryTransverseMinors mu sigma k 2 := by
  minor_eval n68_eval

theorem root2_q8_transverse_rank_drop_minors_cell3 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n71 = ordinaryTransverseMinors mu sigma k 3 := by
  minor_eval n71_eval

theorem root2_q8_transverse_rank_drop_minors_cell4 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n76 = ordinaryTransverseMinors mu sigma k 4 := by
  minor_eval n76_eval

theorem root2_q8_transverse_rank_drop_minors_cell5 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n80 = ordinaryTransverseMinors mu sigma k 5 := by
  minor_eval n80_eval

theorem root2_q8_transverse_rank_drop_minors_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n58 = ordinaryTransverseMinors mu sigma k 0 ∧
    Expr.eval (values rho mu sigma z k) n63 = ordinaryTransverseMinors mu sigma k 1 ∧
    Expr.eval (values rho mu sigma z k) n68 = ordinaryTransverseMinors mu sigma k 2 ∧
    Expr.eval (values rho mu sigma z k) n71 = ordinaryTransverseMinors mu sigma k 3 ∧
    Expr.eval (values rho mu sigma z k) n76 = ordinaryTransverseMinors mu sigma k 4 ∧
    Expr.eval (values rho mu sigma z k) n80 = ordinaryTransverseMinors mu sigma k 5 :=
  ⟨root2_q8_transverse_rank_drop_minors_cell0 rho mu sigma z k, root2_q8_transverse_rank_drop_minors_cell1 rho mu sigma z k, root2_q8_transverse_rank_drop_minors_cell2 rho mu sigma z k, root2_q8_transverse_rank_drop_minors_cell3 rho mu sigma z k, root2_q8_transverse_rank_drop_minors_cell4 rho mu sigma z k, root2_q8_transverse_rank_drop_minors_cell5 rho mu sigma z k⟩

theorem root2_q8_transverse_rank_drop_minors_dimensions :
    Expr.HasDim units n58 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n63 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n68 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n71 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n76 (dimensions (-4) (-2) 1) ∧
    Expr.HasDim units n80 (dimensions (-4) (-2) 1) :=
  ⟨n58_dim, n63_dim, n68_dim, n71_dim, n76_dim, n80_dim⟩

theorem root3_q8_rank_drop_minors_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n85 = extraRankMinors mu sigma k 0 := by
  minor_eval n85_eval

theorem root3_q8_rank_drop_minors_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n90 = extraRankMinors mu sigma k 1 := by
  minor_eval n90_eval

theorem root3_q8_rank_drop_minors_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n95 = extraRankMinors mu sigma k 2 := by
  minor_eval n95_eval

theorem root3_q8_rank_drop_minors_cell3 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n99 = extraRankMinors mu sigma k 3 := by
  minor_eval n99_eval

theorem root3_q8_rank_drop_minors_cell4 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n102 = extraRankMinors mu sigma k 4 := by
  minor_eval n102_eval

theorem root3_q8_rank_drop_minors_cell5 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n109 = extraRankMinors mu sigma k 5 := by
  minor_eval n109_eval

theorem root3_q8_rank_drop_minors_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n85 = extraRankMinors mu sigma k 0 ∧
    Expr.eval (values rho mu sigma z k) n90 = extraRankMinors mu sigma k 1 ∧
    Expr.eval (values rho mu sigma z k) n95 = extraRankMinors mu sigma k 2 ∧
    Expr.eval (values rho mu sigma z k) n99 = extraRankMinors mu sigma k 3 ∧
    Expr.eval (values rho mu sigma z k) n102 = extraRankMinors mu sigma k 4 ∧
    Expr.eval (values rho mu sigma z k) n109 = extraRankMinors mu sigma k 5 :=
  ⟨root3_q8_rank_drop_minors_cell0 rho mu sigma z k, root3_q8_rank_drop_minors_cell1 rho mu sigma z k, root3_q8_rank_drop_minors_cell2 rho mu sigma z k h0, root3_q8_rank_drop_minors_cell3 rho mu sigma z k, root3_q8_rank_drop_minors_cell4 rho mu sigma z k h0, root3_q8_rank_drop_minors_cell5 rho mu sigma z k h0⟩

theorem root3_q8_rank_drop_minors_dimensions :
    Expr.HasDim units n85 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n90 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n95 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n99 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n102 (dimensions (-6) (-4) 2) ∧
    Expr.HasDim units n109 (dimensions (-6) (-4) 2) :=
  ⟨n85_dim, n90_dim, n95_dim, n99_dim, n102_dim, n109_dim⟩

theorem root3_q8_transverse_rank_drop_minors_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n43 = extraTransverseMinors mu sigma k 0 := by
  minor_eval n43_eval

theorem root3_q8_transverse_rank_drop_minors_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n115 = extraTransverseMinors mu sigma k 1 := by
  minor_eval n115_eval

theorem root3_q8_transverse_rank_drop_minors_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n119 = extraTransverseMinors mu sigma k 2 := by
  minor_eval n119_eval

theorem root3_q8_transverse_rank_drop_minors_cell3 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n122 = extraTransverseMinors mu sigma k 3 := by
  minor_eval n122_eval

theorem root3_q8_transverse_rank_drop_minors_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n43 = extraTransverseMinors mu sigma k 0 ∧
    Expr.eval (values rho mu sigma z k) n115 = extraTransverseMinors mu sigma k 1 ∧
    Expr.eval (values rho mu sigma z k) n119 = extraTransverseMinors mu sigma k 2 ∧
    Expr.eval (values rho mu sigma z k) n122 = extraTransverseMinors mu sigma k 3 :=
  ⟨root3_q8_transverse_rank_drop_minors_cell0 rho mu sigma z k, root3_q8_transverse_rank_drop_minors_cell1 rho mu sigma z k h0, root3_q8_transverse_rank_drop_minors_cell2 rho mu sigma z k h0, root3_q8_transverse_rank_drop_minors_cell3 rho mu sigma z k h0⟩

theorem root3_q8_transverse_rank_drop_minors_dimensions :
    Expr.HasDim units n43 (dimensions (-9) (-6) 3) ∧
    Expr.HasDim units n115 (dimensions (-7) (-4) 2) ∧
    Expr.HasDim units n119 (dimensions (-7) (-4) 2) ∧
    Expr.HasDim units n122 (dimensions (-7) (-4) 2) :=
  ⟨n43_dim, n115_dim, n119_dim, n122_dim⟩

end
end S10Audit.CAS.PYMinors
