-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 10ebaecb24b1ca92131566a37197f73cb9b93c8925299ec404838b50fdce75cf
import S10Audit.CAS.RecordSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.PYRecordsParallel
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .atom .z
theorem n0_dim : Expr.HasDim coordinateUnits n0 (dimensions 2 (-2) 0) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .z
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = z := by
  rfl

def n1 : Expr Symbol := .atom .rho
theorem n1_dim : Expr.HasDim coordinateUnits n1 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .rho
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = rho := by
  rfl

def n2 : Expr Symbol := .mul n0 n1
theorem n2_dim : Expr.HasDim coordinateUnits n2 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n0_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = (z * rho) := by
  simp only [n2, Expr.eval, n0_eval, n1_eval]

def n3 : Expr Symbol := .atom .sigma
theorem n3_dim : Expr.HasDim coordinateUnits n3 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .sigma
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = sigma := by
  rfl

def n4 : Expr Symbol := .mul n2 n3
theorem n4_dim : Expr.HasDim coordinateUnits n4 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n2_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = ((z * rho) * sigma) := by
  simp only [n4, Expr.eval, n2_eval, n3_eval]

def n5 : Expr Symbol := .atom .mu
theorem n5_dim : Expr.HasDim coordinateUnits n5 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .mu
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = mu := by
  rfl

def n6 : Expr Symbol := .sub n5 n2
theorem n6_dim : Expr.HasDim coordinateUnits n6 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.sub n5_dim n2_dim
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = (mu - (z * rho)) := by
  simp only [n6, Expr.eval, n5_eval, n2_eval]

def n7 : Expr Symbol := .pow n6 2
theorem n7_dim : Expr.HasDim coordinateUnits n7 (dimensions (-2) (-4) 2) := by
  apply castDim (Expr.HasDim.pow 2 n6_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = ((mu - (z * rho)) ^ 2) := by
  simp only [n7, Expr.eval, n6_eval]

def n8 : Expr Symbol := .mul n4 n7
theorem n8_dim : Expr.HasDim coordinateUnits n8 (dimensions (-3) (-6) 3) := by
  apply castDim (Expr.HasDim.mul n4_dim n7_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = (((z * rho) * sigma) * ((mu - (z * rho)) ^ 2)) := by
  simp only [n8, Expr.eval, n4_eval, n7_eval]

def n9 : Expr Symbol := .scalar 8
theorem n9_dim : Expr.HasDim coordinateUnits n9 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 8) dimensions_zero.symm
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = 8 := by
  rfl

def n10 : Expr Symbol := .div n8 n9
theorem n10_dim : Expr.HasDim coordinateUnits n10 (dimensions (-3) (-6) 3) := by
  apply castDim (Expr.HasDim.div n8_dim n9_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = ((((z * rho) * sigma) * ((mu - (z * rho)) ^ 2)) / 8) := by
  simp only [n10, Expr.eval, n8_eval, n9_eval]

theorem q8_stratum1_q3_spectrum_solve_condition_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n10 = Matrix.det ((1/2 : ℝ) • referenceMatrix rho mu sigma z PYLoci.parallelPoint) := by
  rerun_eval n10_eval

theorem q8_stratum1_q3_spectrum_solve_condition_operands_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = z := by
  rerun_eval n0_eval

theorem q8_stratum1_q3_spectrum_solve_condition_operands_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n10 = Matrix.det ((1/2 : ℝ) • referenceMatrix rho mu sigma z PYLoci.parallelPoint) ∧
    Expr.eval (values rho mu sigma z k) n0 = z :=
  ⟨q8_stratum1_q3_spectrum_solve_condition_operands_cell0 rho mu sigma z k, q8_stratum1_q3_spectrum_solve_condition_operands_cell1 rho mu sigma z k⟩

theorem q8_stratum1_q3_spectrum_solve_condition_operands_dimensions :
    Expr.HasDim coordinateUnits n10 (dimensions (-3) (-6) 3) ∧
    Expr.HasDim coordinateUnits n0 (dimensions 2 (-2) 0) :=
  ⟨n10_dim, n0_dim⟩

end
end S10Audit.CAS.PYRecordsParallel
