-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 10ebaecb24b1ca92131566a37197f73cb9b93c8925299ec404838b50fdce75cf
import S10Audit.CAS.RecordSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.PYRecordsGeneric
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .atom .z
theorem n0_dim : Expr.HasDim units n0 (dimensions 0 (-2) 0) := by
  exact Expr.HasDim.atom (u := units) .z
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = z := by
  rfl

def n1 : Expr Symbol := .atom .rho
theorem n1_dim : Expr.HasDim units n1 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := units) .rho
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = rho := by
  rfl

def n2 : Expr Symbol := .mul n0 n1
theorem n2_dim : Expr.HasDim units n2 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n0_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = (z * rho) := by
  simp only [n2, Expr.eval, n0_eval, n1_eval]

def n3 : Expr Symbol := .atom (.k 0)
theorem n3_dim : Expr.HasDim units n3 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 0)
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = (k 0) := by
  rfl

def n4 : Expr Symbol := .pow n3 2
theorem n4_dim : Expr.HasDim units n4 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n3_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = ((k 0) ^ 2) := by
  simp only [n4, Expr.eval, n3_eval]

def n5 : Expr Symbol := .atom .mu
theorem n5_dim : Expr.HasDim units n5 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := units) .mu
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = mu := by
  rfl

def n6 : Expr Symbol := .mul n4 n5
theorem n6_dim : Expr.HasDim units n6 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n4_dim n5_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = (((k 0) ^ 2) * mu) := by
  simp only [n6, Expr.eval, n4_eval, n5_eval]

def n7 : Expr Symbol := .atom (.k 1)
theorem n7_dim : Expr.HasDim units n7 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 1)
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = (k 1) := by
  rfl

def n8 : Expr Symbol := .pow n7 2
theorem n8_dim : Expr.HasDim units n8 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n7_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = ((k 1) ^ 2) := by
  simp only [n8, Expr.eval, n7_eval]

def n9 : Expr Symbol := .mul n8 n5
theorem n9_dim : Expr.HasDim units n9 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n8_dim n5_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = (((k 1) ^ 2) * mu) := by
  simp only [n9, Expr.eval, n8_eval, n5_eval]

def n10 : Expr Symbol := .add n6 n9
theorem n10_dim : Expr.HasDim units n10 (dimensions (-3) (-2) 1) := by
  exact Expr.HasDim.add n6_dim n9_dim
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = ((((k 0) ^ 2) * mu) + (((k 1) ^ 2) * mu)) := by
  simp only [n10, Expr.eval, n6_eval, n9_eval]

def n11 : Expr Symbol := .atom (.k 2)
theorem n11_dim : Expr.HasDim units n11 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 2)
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = (k 2) := by
  rfl

def n12 : Expr Symbol := .pow n11 2
theorem n12_dim : Expr.HasDim units n12 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n11_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = ((k 2) ^ 2) := by
  simp only [n12, Expr.eval, n11_eval]

def n13 : Expr Symbol := .mul n12 n5
theorem n13_dim : Expr.HasDim units n13 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n12_dim n5_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = (((k 2) ^ 2) * mu) := by
  simp only [n13, Expr.eval, n12_eval, n5_eval]

def n14 : Expr Symbol := .add n10 n13
theorem n14_dim : Expr.HasDim units n14 (dimensions (-3) (-2) 1) := by
  exact Expr.HasDim.add n10_dim n13_dim
theorem n14_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n14 = (((((k 0) ^ 2) * mu) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) := by
  simp only [n14, Expr.eval, n10_eval, n13_eval]

def n15 : Expr Symbol := .sub n14 n2
theorem n15_dim : Expr.HasDim units n15 (dimensions (-3) (-2) 1) := by
  exact Expr.HasDim.sub n14_dim n2_dim
theorem n15_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n15 = ((((((k 0) ^ 2) * mu) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) - (z * rho)) := by
  simp only [n15, Expr.eval, n14_eval, n2_eval]

def n16 : Expr Symbol := .mul n2 n15
theorem n16_dim : Expr.HasDim units n16 (dimensions (-6) (-4) 2) := by
  apply castDim (Expr.HasDim.mul n2_dim n15_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n16_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n16 = ((z * rho) * ((((((k 0) ^ 2) * mu) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) - (z * rho))) := by
  simp only [n16, Expr.eval, n2_eval, n15_eval]

def n17 : Expr Symbol := .atom .sigma
theorem n17_dim : Expr.HasDim units n17 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := units) .sigma
theorem n17_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n17 = sigma := by
  rfl

def n18 : Expr Symbol := .mul n6 n17
theorem n18_dim : Expr.HasDim units n18 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n6_dim n17_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n18_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n18 = ((((k 0) ^ 2) * mu) * sigma) := by
  simp only [n18, Expr.eval, n6_eval, n17_eval]

def n19 : Expr Symbol := .add n18 n9
theorem n19_dim : Expr.HasDim units n19 (dimensions (-3) (-2) 1) := by
  exact Expr.HasDim.add n18_dim n9_dim
theorem n19_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n19 = (((((k 0) ^ 2) * mu) * sigma) + (((k 1) ^ 2) * mu)) := by
  simp only [n19, Expr.eval, n18_eval, n9_eval]

def n20 : Expr Symbol := .add n19 n13
theorem n20_dim : Expr.HasDim units n20 (dimensions (-3) (-2) 1) := by
  exact Expr.HasDim.add n19_dim n13_dim
theorem n20_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n20 = ((((((k 0) ^ 2) * mu) * sigma) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) := by
  simp only [n20, Expr.eval, n19_eval, n13_eval]

def n21 : Expr Symbol := .mul n2 n17
theorem n21_dim : Expr.HasDim units n21 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n2_dim n17_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n21_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n21 = ((z * rho) * sigma) := by
  simp only [n21, Expr.eval, n2_eval, n17_eval]

def n22 : Expr Symbol := .sub n20 n21
theorem n22_dim : Expr.HasDim units n22 (dimensions (-3) (-2) 1) := by
  exact Expr.HasDim.sub n20_dim n21_dim
theorem n22_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n22 = (((((((k 0) ^ 2) * mu) * sigma) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) - ((z * rho) * sigma)) := by
  simp only [n22, Expr.eval, n20_eval, n21_eval]

def n23 : Expr Symbol := .mul n16 n22
theorem n23_dim : Expr.HasDim units n23 (dimensions (-9) (-6) 3) := by
  apply castDim (Expr.HasDim.mul n16_dim n22_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n23_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n23 = (((z * rho) * ((((((k 0) ^ 2) * mu) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) - (z * rho))) * (((((((k 0) ^ 2) * mu) * sigma) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) - ((z * rho) * sigma))) := by
  simp only [n23, Expr.eval, n16_eval, n22_eval]

def n24 : Expr Symbol := .scalar 8
theorem n24_dim : Expr.HasDim units n24 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 8) dimensions_zero.symm
theorem n24_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n24 = 8 := by
  rfl

def n25 : Expr Symbol := .div n23 n24
theorem n25_dim : Expr.HasDim units n25 (dimensions (-9) (-6) 3) := by
  apply castDim (Expr.HasDim.div n23_dim n24_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n25_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n25 = ((((z * rho) * ((((((k 0) ^ 2) * mu) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) - (z * rho))) * (((((((k 0) ^ 2) * mu) * sigma) + (((k 1) ^ 2) * mu)) + (((k 2) ^ 2) * mu)) - ((z * rho) * sigma))) / 8) := by
  simp only [n25, Expr.eval, n23_eval, n24_eval]

theorem q3_spectrum_solve_condition_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = Matrix.det ((1/2 : ℝ) • referenceMatrix rho mu sigma z k) := by
  cas_eval n25_eval

theorem q3_spectrum_solve_condition_operands_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = z := by
  cas_eval n0_eval

theorem q3_spectrum_solve_condition_operands_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = Matrix.det ((1/2 : ℝ) • referenceMatrix rho mu sigma z k) ∧
    Expr.eval (values rho mu sigma z k) n0 = z :=
  ⟨q3_spectrum_solve_condition_operands_cell0 rho mu sigma z k, q3_spectrum_solve_condition_operands_cell1 rho mu sigma z k⟩

theorem q3_spectrum_solve_condition_operands_dimensions :
    Expr.HasDim units n25 (dimensions (-9) (-6) 3) ∧
    Expr.HasDim units n0 (dimensions 0 (-2) 0) :=
  ⟨n25_dim, n0_dim⟩

end
end S10Audit.CAS.PYRecordsGeneric
