-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 10ebaecb24b1ca92131566a37197f73cb9b93c8925299ec404838b50fdce75cf
import S10Audit.CAS.RerunReference

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.PYRootsParallel
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar 0
theorem n0_dim : Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 0) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = 0 := by
  rfl

def n1 : Expr Symbol := .atom .mu
theorem n1_dim : Expr.HasDim coordinateUnits n1 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .mu
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = mu := by
  rfl

def n2 : Expr Symbol := .atom .rho
theorem n2_dim : Expr.HasDim coordinateUnits n2 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .rho
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = rho := by
  rfl

def n3 : Expr Symbol := .div n1 n2
theorem n3_dim : Expr.HasDim coordinateUnits n3 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n1_dim n2_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = (mu / rho) := by
  simp only [n3, Expr.eval, n1_eval, n2_eval]

def n4 : Expr Symbol := .mul n0 n3
theorem n4_dim : Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = (0 * (mu / rho)) := by
  simp only [n4, Expr.eval, n0_eval, n3_eval]

def n5 : Expr Symbol := .scalar 2
theorem n5_dim : Expr.HasDim coordinateUnits n5 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2) dimensions_zero.symm
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = 2 := by
  rfl

theorem q8_stratum1_q3_root_solutions_raw_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma PYLoci.parallelPoint 0 := by
  rerun_eval n4_eval

theorem q8_stratum1_q3_root_solutions_raw_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n3 = referenceRoot rho mu sigma PYLoci.parallelPoint 1 := by
  rerun_eval n3_eval

theorem q8_stratum1_q3_root_solutions_raw_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma PYLoci.parallelPoint 0 ∧
    Expr.eval (values rho mu sigma z k) n3 = referenceRoot rho mu sigma PYLoci.parallelPoint 1 :=
  ⟨q8_stratum1_q3_root_solutions_raw_cell0 rho mu sigma z k, q8_stratum1_q3_root_solutions_raw_cell1 rho mu sigma z k h0⟩

theorem q8_stratum1_q3_root_solutions_raw_dimensions :
    Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n3 (dimensions 2 (-2) 0) :=
  ⟨n4_dim, n3_dim⟩

theorem q8_stratum1_q3_roots_distinct_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma PYLoci.parallelPoint 0 := by
  rerun_eval n4_eval

theorem q8_stratum1_q3_roots_distinct_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n3 = referenceRoot rho mu sigma PYLoci.parallelPoint 1 := by
  rerun_eval n3_eval

theorem q8_stratum1_q3_roots_distinct_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma PYLoci.parallelPoint 0 ∧
    Expr.eval (values rho mu sigma z k) n3 = referenceRoot rho mu sigma PYLoci.parallelPoint 1 :=
  ⟨q8_stratum1_q3_roots_distinct_cell0 rho mu sigma z k, q8_stratum1_q3_roots_distinct_cell1 rho mu sigma z k h0⟩

theorem q8_stratum1_q3_roots_distinct_dimensions :
    Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n3 (dimensions 2 (-2) 0) :=
  ⟨n4_dim, n3_dim⟩

theorem q8_stratum1_q3_root_count_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n5 = 2 := by
  rerun_eval n5_eval

theorem q8_stratum1_q3_root_count_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n5 = 2 :=
  q8_stratum1_q3_root_count_cell0 rho mu sigma z k

theorem q8_stratum1_q3_root_count_dimensions :
    Expr.HasDim coordinateUnits n5 (dimensions 0 0 0) :=
  n5_dim

end
end S10Audit.CAS.PYRootsParallel
