-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 0718871c408ea2839668d40f68c7ff143e9520e3be4dbb5dcd1e4cdad9f57ccd
import S10Audit.CAS.CoincidenceSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.WLCoincidenceArithmeticPerpendicular
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar (-1)
theorem n0_dim : Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar (-1)) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = (-1) := by
  rfl

def n1 : Expr Symbol := .scalar 2917
theorem n1_dim : Expr.HasDim coordinateUnits n1 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2917) dimensions_zero.symm
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = 2917 := by
  rfl

def n2 : Expr Symbol := .mul n0 n1
theorem n2_dim : Expr.HasDim coordinateUnits n2 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = ((-1) * 2917) := by
  simp only [n2, Expr.eval, n0_eval, n1_eval]

def n3 : Expr Symbol := .atom .mu
theorem n3_dim : Expr.HasDim coordinateUnits n3 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .mu
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = mu := by
  rfl

def n4 : Expr Symbol := .mul n2 n3
theorem n4_dim : Expr.HasDim coordinateUnits n4 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n2_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = (((-1) * 2917) * mu) := by
  simp only [n4, Expr.eval, n2_eval, n3_eval]

def n5 : Expr Symbol := .scalar 4
theorem n5_dim : Expr.HasDim coordinateUnits n5 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 4) dimensions_zero.symm
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = 4 := by
  rfl

def n6 : Expr Symbol := .atom .rho
theorem n6_dim : Expr.HasDim coordinateUnits n6 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .rho
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = rho := by
  rfl

def n7 : Expr Symbol := .mul n5 n6
theorem n7_dim : Expr.HasDim coordinateUnits n7 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n5_dim n6_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = (4 * rho) := by
  simp only [n7, Expr.eval, n5_eval, n6_eval]

def n8 : Expr Symbol := .div n4 n7
theorem n8_dim : Expr.HasDim coordinateUnits n8 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n4_dim n7_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = ((((-1) * 2917) * mu) / (4 * rho)) := by
  simp only [n8, Expr.eval, n4_eval, n7_eval]

def n9 : Expr Symbol := .atom .sigma
theorem n9_dim : Expr.HasDim coordinateUnits n9 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .sigma
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = sigma := by
  rfl

def n10 : Expr Symbol := .mul n7 n9
theorem n10_dim : Expr.HasDim coordinateUnits n10 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n7_dim n9_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = ((4 * rho) * sigma) := by
  simp only [n10, Expr.eval, n7_eval, n9_eval]

def n11 : Expr Symbol := .div n4 n10
theorem n11_dim : Expr.HasDim coordinateUnits n11 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n4_dim n10_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = ((((-1) * 2917) * mu) / ((4 * rho) * sigma)) := by
  simp only [n11, Expr.eval, n4_eval, n10_eval]

def n12 : Expr Symbol := .mul n1 n3
theorem n12_dim : Expr.HasDim coordinateUnits n12 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n1_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = (2917 * mu) := by
  simp only [n12, Expr.eval, n1_eval, n3_eval]

def n13 : Expr Symbol := .scalar 1
theorem n13_dim : Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 1) dimensions_zero.symm
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = 1 := by
  rfl

def n14 : Expr Symbol := .mul n0 n13
theorem n14_dim : Expr.HasDim coordinateUnits n14 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n13_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n14_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n14 = ((-1) * 1) := by
  simp only [n14, Expr.eval, n0_eval, n13_eval]

def n15 : Expr Symbol := .add n14 n9
theorem n15_dim : Expr.HasDim coordinateUnits n15 (dimensions 0 0 0) := by
  exact Expr.HasDim.add n14_dim n9_dim
theorem n15_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n15 = (((-1) * 1) + sigma) := by
  simp only [n15, Expr.eval, n14_eval, n9_eval]

def n16 : Expr Symbol := .mul n12 n15
theorem n16_dim : Expr.HasDim coordinateUnits n16 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n12_dim n15_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n16_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n16 = ((2917 * mu) * (((-1) * 1) + sigma)) := by
  simp only [n16, Expr.eval, n12_eval, n15_eval]

def n17 : Expr Symbol := .div n16 n10
theorem n17_dim : Expr.HasDim coordinateUnits n17 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n16_dim n10_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n17_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n17 = (((2917 * mu) * (((-1) * 1) + sigma)) / ((4 * rho) * sigma)) := by
  simp only [n17, Expr.eval, n16_eval, n10_eval]

theorem stratum2_root1_root2_q3_coincidence_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n8 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 := by
  rerun_eval n8_eval

theorem stratum2_root1_root2_q3_coincidence_operands_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n8 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 :=
  stratum2_root1_root2_q3_coincidence_operands_cell0 rho mu sigma z k h0 h1

theorem stratum2_root1_root2_q3_coincidence_operands_dimensions :
    Expr.HasDim coordinateUnits n8 (dimensions 2 (-2) 0) :=
  n8_dim

theorem stratum2_root1_root3_q3_coincidence_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n11 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 := by
  rerun_eval n11_eval

theorem stratum2_root1_root3_q3_coincidence_operands_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n11 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 :=
  stratum2_root1_root3_q3_coincidence_operands_cell0 rho mu sigma z k h0 h1

theorem stratum2_root1_root3_q3_coincidence_operands_dimensions :
    Expr.HasDim coordinateUnits n11 (dimensions 2 (-2) 0) :=
  n11_dim

theorem stratum2_root2_root3_q3_coincidence_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n17 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 := by
  rerun_eval n17_eval

theorem stratum2_root2_root3_q3_coincidence_operands_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n17 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 :=
  stratum2_root2_root3_q3_coincidence_operands_cell0 rho mu sigma z k h0 h1

theorem stratum2_root2_root3_q3_coincidence_operands_dimensions :
    Expr.HasDim coordinateUnits n17 (dimensions 2 (-2) 0) :=
  n17_dim

end
end S10Audit.CAS.WLCoincidenceArithmeticPerpendicular
