-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 0718871c408ea2839668d40f68c7ff143e9520e3be4dbb5dcd1e4cdad9f57ccd
import S10Audit.CAS.CoincidenceSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.WLCoincidenceArithmeticGeneric
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar (-1)
theorem n0_dim : Expr.HasDim units n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar (-1)) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = (-1) := by
  rfl

def n1 : Expr Symbol := .atom (.k 0)
theorem n1_dim : Expr.HasDim units n1 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 0)
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = (k 0) := by
  rfl

def n2 : Expr Symbol := .pow n1 2
theorem n2_dim : Expr.HasDim units n2 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n1_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = ((k 0) ^ 2) := by
  simp only [n2, Expr.eval, n1_eval]

def n3 : Expr Symbol := .atom (.k 1)
theorem n3_dim : Expr.HasDim units n3 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 1)
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = (k 1) := by
  rfl

def n4 : Expr Symbol := .pow n3 2
theorem n4_dim : Expr.HasDim units n4 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n3_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = ((k 1) ^ 2) := by
  simp only [n4, Expr.eval, n3_eval]

def n5 : Expr Symbol := .add n2 n4
theorem n5_dim : Expr.HasDim units n5 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n2_dim n4_dim
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = (((k 0) ^ 2) + ((k 1) ^ 2)) := by
  simp only [n5, Expr.eval, n2_eval, n4_eval]

def n6 : Expr Symbol := .atom (.k 2)
theorem n6_dim : Expr.HasDim units n6 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 2)
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = (k 2) := by
  rfl

def n7 : Expr Symbol := .pow n6 2
theorem n7_dim : Expr.HasDim units n7 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n6_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = ((k 2) ^ 2) := by
  simp only [n7, Expr.eval, n6_eval]

def n8 : Expr Symbol := .add n5 n7
theorem n8_dim : Expr.HasDim units n8 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n5_dim n7_dim
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) := by
  simp only [n8, Expr.eval, n5_eval, n7_eval]

def n9 : Expr Symbol := .atom .mu
theorem n9_dim : Expr.HasDim units n9 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := units) .mu
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = mu := by
  rfl

def n10 : Expr Symbol := .mul n8 n9
theorem n10_dim : Expr.HasDim units n10 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n8_dim n9_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) * mu) := by
  simp only [n10, Expr.eval, n8_eval, n9_eval]

def n11 : Expr Symbol := .atom .rho
theorem n11_dim : Expr.HasDim units n11 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := units) .rho
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = rho := by
  rfl

def n12 : Expr Symbol := .div n10 n11
theorem n12_dim : Expr.HasDim units n12 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.div n10_dim n11_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = ((((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) * mu) / rho) := by
  simp only [n12, Expr.eval, n10_eval, n11_eval]

def n13 : Expr Symbol := .mul n0 n12
theorem n13_dim : Expr.HasDim units n13 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n12_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = ((-1) * ((((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) * mu) / rho)) := by
  simp only [n13, Expr.eval, n0_eval, n12_eval]

def n14 : Expr Symbol := .add n4 n7
theorem n14_dim : Expr.HasDim units n14 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n4_dim n7_dim
theorem n14_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n14 = (((k 1) ^ 2) + ((k 2) ^ 2)) := by
  simp only [n14, Expr.eval, n4_eval, n7_eval]

def n15 : Expr Symbol := .atom .sigma
theorem n15_dim : Expr.HasDim units n15 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := units) .sigma
theorem n15_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n15 = sigma := by
  rfl

def n16 : Expr Symbol := .mul n2 n15
theorem n16_dim : Expr.HasDim units n16 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n2_dim n15_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n16_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n16 = (((k 0) ^ 2) * sigma) := by
  simp only [n16, Expr.eval, n2_eval, n15_eval]

def n17 : Expr Symbol := .add n14 n16
theorem n17_dim : Expr.HasDim units n17 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n14_dim n16_dim
theorem n17_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n17 = ((((k 1) ^ 2) + ((k 2) ^ 2)) + (((k 0) ^ 2) * sigma)) := by
  simp only [n17, Expr.eval, n14_eval, n16_eval]

def n18 : Expr Symbol := .mul n9 n17
theorem n18_dim : Expr.HasDim units n18 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n9_dim n17_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n18_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n18 = (mu * ((((k 1) ^ 2) + ((k 2) ^ 2)) + (((k 0) ^ 2) * sigma))) := by
  simp only [n18, Expr.eval, n9_eval, n17_eval]

def n19 : Expr Symbol := .mul n11 n15
theorem n19_dim : Expr.HasDim units n19 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n11_dim n15_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n19_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n19 = (rho * sigma) := by
  simp only [n19, Expr.eval, n11_eval, n15_eval]

def n20 : Expr Symbol := .div n18 n19
theorem n20_dim : Expr.HasDim units n20 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.div n18_dim n19_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n20_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n20 = ((mu * ((((k 1) ^ 2) + ((k 2) ^ 2)) + (((k 0) ^ 2) * sigma))) / (rho * sigma)) := by
  simp only [n20, Expr.eval, n18_eval, n19_eval]

def n21 : Expr Symbol := .mul n0 n20
theorem n21_dim : Expr.HasDim units n21 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n20_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n21_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n21 = ((-1) * ((mu * ((((k 1) ^ 2) + ((k 2) ^ 2)) + (((k 0) ^ 2) * sigma))) / (rho * sigma))) := by
  simp only [n21, Expr.eval, n0_eval, n20_eval]

def n22 : Expr Symbol := .mul n0 n4
theorem n22_dim : Expr.HasDim units n22 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n4_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n22_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n22 = ((-1) * ((k 1) ^ 2)) := by
  simp only [n22, Expr.eval, n0_eval, n4_eval]

def n23 : Expr Symbol := .sub n22 n7
theorem n23_dim : Expr.HasDim units n23 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.sub n22_dim n7_dim
theorem n23_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n23 = (((-1) * ((k 1) ^ 2)) - ((k 2) ^ 2)) := by
  simp only [n23, Expr.eval, n22_eval, n7_eval]

def n24 : Expr Symbol := .mul n4 n15
theorem n24_dim : Expr.HasDim units n24 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n4_dim n15_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n24_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n24 = (((k 1) ^ 2) * sigma) := by
  simp only [n24, Expr.eval, n4_eval, n15_eval]

def n25 : Expr Symbol := .add n23 n24
theorem n25_dim : Expr.HasDim units n25 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n23_dim n24_dim
theorem n25_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n25 = ((((-1) * ((k 1) ^ 2)) - ((k 2) ^ 2)) + (((k 1) ^ 2) * sigma)) := by
  simp only [n25, Expr.eval, n23_eval, n24_eval]

def n26 : Expr Symbol := .mul n7 n15
theorem n26_dim : Expr.HasDim units n26 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n7_dim n15_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n26_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n26 = (((k 2) ^ 2) * sigma) := by
  simp only [n26, Expr.eval, n7_eval, n15_eval]

def n27 : Expr Symbol := .add n25 n26
theorem n27_dim : Expr.HasDim units n27 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n25_dim n26_dim
theorem n27_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n27 = (((((-1) * ((k 1) ^ 2)) - ((k 2) ^ 2)) + (((k 1) ^ 2) * sigma)) + (((k 2) ^ 2) * sigma)) := by
  simp only [n27, Expr.eval, n25_eval, n26_eval]

def n28 : Expr Symbol := .mul n9 n27
theorem n28_dim : Expr.HasDim units n28 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n9_dim n27_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n28_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n28 = (mu * (((((-1) * ((k 1) ^ 2)) - ((k 2) ^ 2)) + (((k 1) ^ 2) * sigma)) + (((k 2) ^ 2) * sigma))) := by
  simp only [n28, Expr.eval, n9_eval, n27_eval]

def n29 : Expr Symbol := .div n28 n19
theorem n29_dim : Expr.HasDim units n29 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.div n28_dim n19_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n29_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n29 = ((mu * (((((-1) * ((k 1) ^ 2)) - ((k 2) ^ 2)) + (((k 1) ^ 2) * sigma)) + (((k 2) ^ 2) * sigma))) / (rho * sigma)) := by
  simp only [n29, Expr.eval, n28_eval, n19_eval]

theorem root1_root2_q3_coincidence_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n13 = referenceRoot rho mu sigma k 0 - referenceRoot rho mu sigma k 1 := by
  cas_eval n13_eval

theorem root1_root2_q3_coincidence_operands_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n13 = referenceRoot rho mu sigma k 0 - referenceRoot rho mu sigma k 1 :=
  root1_root2_q3_coincidence_operands_cell0 rho mu sigma z k h0 h1

theorem root1_root2_q3_coincidence_operands_dimensions :
    Expr.HasDim units n13 (dimensions 0 (-2) 0) :=
  n13_dim

theorem root1_root3_q3_coincidence_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n21 = referenceRoot rho mu sigma k 0 - referenceRoot rho mu sigma k 2 := by
  cas_eval n21_eval

theorem root1_root3_q3_coincidence_operands_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n21 = referenceRoot rho mu sigma k 0 - referenceRoot rho mu sigma k 2 :=
  root1_root3_q3_coincidence_operands_cell0 rho mu sigma z k h0 h1

theorem root1_root3_q3_coincidence_operands_dimensions :
    Expr.HasDim units n21 (dimensions 0 (-2) 0) :=
  n21_dim

theorem root2_root3_q3_coincidence_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n29 = referenceRoot rho mu sigma k 1 - referenceRoot rho mu sigma k 2 := by
  cas_eval n29_eval

theorem root2_root3_q3_coincidence_operands_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n29 = referenceRoot rho mu sigma k 1 - referenceRoot rho mu sigma k 2 :=
  root2_root3_q3_coincidence_operands_cell0 rho mu sigma z k h0 h1

theorem root2_root3_q3_coincidence_operands_dimensions :
    Expr.HasDim units n29 (dimensions 0 (-2) 0) :=
  n29_dim

end
end S10Audit.CAS.WLCoincidenceArithmeticGeneric
