-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 0718871c408ea2839668d40f68c7ff143e9520e3be4dbb5dcd1e4cdad9f57ccd
import S10Audit.CAS.CoincidenceSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.WLCoincidenceArithmeticParallel
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar (-1)
theorem n0_dim : Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar (-1)) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = (-1) := by
  rfl

def n1 : Expr Symbol := .scalar 729
theorem n1_dim : Expr.HasDim coordinateUnits n1 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 729) dimensions_zero.symm
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = 729 := by
  rfl

def n2 : Expr Symbol := .mul n0 n1
theorem n2_dim : Expr.HasDim coordinateUnits n2 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = ((-1) * 729) := by
  simp only [n2, Expr.eval, n0_eval, n1_eval]

def n3 : Expr Symbol := .atom .mu
theorem n3_dim : Expr.HasDim coordinateUnits n3 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .mu
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = mu := by
  rfl

def n4 : Expr Symbol := .mul n2 n3
theorem n4_dim : Expr.HasDim coordinateUnits n4 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n2_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = (((-1) * 729) * mu) := by
  simp only [n4, Expr.eval, n2_eval, n3_eval]

def n5 : Expr Symbol := .atom .rho
theorem n5_dim : Expr.HasDim coordinateUnits n5 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .rho
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = rho := by
  rfl

def n6 : Expr Symbol := .div n4 n5
theorem n6_dim : Expr.HasDim coordinateUnits n6 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n4_dim n5_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = ((((-1) * 729) * mu) / rho) := by
  simp only [n6, Expr.eval, n4_eval, n5_eval]

theorem stratum1_root1_root2_q3_coincidence_operands_cell0 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n6 = referenceRoot rho mu sigma WLLoci.parallelPoint 0 - referenceRoot rho mu sigma WLLoci.parallelPoint 1 := by
  rerun_eval n6_eval

theorem stratum1_root1_root2_q3_coincidence_operands_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n6 = referenceRoot rho mu sigma WLLoci.parallelPoint 0 - referenceRoot rho mu sigma WLLoci.parallelPoint 1 :=
  stratum1_root1_root2_q3_coincidence_operands_cell0 rho mu sigma z k h0 h1

theorem stratum1_root1_root2_q3_coincidence_operands_dimensions :
    Expr.HasDim coordinateUnits n6 (dimensions 2 (-2) 0) :=
  n6_dim

end
end S10Audit.CAS.WLCoincidenceArithmeticParallel
