-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 0718871c408ea2839668d40f68c7ff143e9520e3be4dbb5dcd1e4cdad9f57ccd
import S10Audit.CAS.RecordSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.WLRecordsPerpendicular
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar 1
theorem n0_dim : Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 1) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = 1 := by
  rfl

def n1 : Expr Symbol := .scalar 2
theorem n1_dim : Expr.HasDim coordinateUnits n1 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2) dimensions_zero.symm
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = 2 := by
  rfl

def n2 : Expr Symbol := .scalar (-1)
theorem n2_dim : Expr.HasDim coordinateUnits n2 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar (-1)) dimensions_zero.symm
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = (-1) := by
  rfl

def n3 : Expr Symbol := .scalar 2917
theorem n3_dim : Expr.HasDim coordinateUnits n3 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2917) dimensions_zero.symm
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = 2917 := by
  rfl

def n4 : Expr Symbol := .mul n2 n3
theorem n4_dim : Expr.HasDim coordinateUnits n4 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.mul n2_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = ((-1) * 2917) := by
  simp only [n4, Expr.eval, n2_eval, n3_eval]

def n5 : Expr Symbol := .atom .mu
theorem n5_dim : Expr.HasDim coordinateUnits n5 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .mu
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = mu := by
  rfl

def n6 : Expr Symbol := .mul n4 n5
theorem n6_dim : Expr.HasDim coordinateUnits n6 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n4_dim n5_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = (((-1) * 2917) * mu) := by
  simp only [n6, Expr.eval, n4_eval, n5_eval]

def n7 : Expr Symbol := .scalar 4
theorem n7_dim : Expr.HasDim coordinateUnits n7 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 4) dimensions_zero.symm
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = 4 := by
  rfl

def n8 : Expr Symbol := .atom .rho
theorem n8_dim : Expr.HasDim coordinateUnits n8 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .rho
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = rho := by
  rfl

def n9 : Expr Symbol := .mul n7 n8
theorem n9_dim : Expr.HasDim coordinateUnits n9 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n7_dim n8_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = (4 * rho) := by
  simp only [n9, Expr.eval, n7_eval, n8_eval]

def n10 : Expr Symbol := .div n6 n9
theorem n10_dim : Expr.HasDim coordinateUnits n10 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n6_dim n9_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = ((((-1) * 2917) * mu) / (4 * rho)) := by
  simp only [n10, Expr.eval, n6_eval, n9_eval]

def n11 : Expr Symbol := .scalar 3
theorem n11_dim : Expr.HasDim coordinateUnits n11 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 3) dimensions_zero.symm
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = 3 := by
  rfl

def n12 : Expr Symbol := .atom .sigma
theorem n12_dim : Expr.HasDim coordinateUnits n12 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .sigma
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = sigma := by
  rfl

def n13 : Expr Symbol := .mul n9 n12
theorem n13_dim : Expr.HasDim coordinateUnits n13 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n9_dim n12_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = ((4 * rho) * sigma) := by
  simp only [n13, Expr.eval, n9_eval, n12_eval]

def n14 : Expr Symbol := .div n6 n13
theorem n14_dim : Expr.HasDim coordinateUnits n14 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n6_dim n13_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n14_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n14 = ((((-1) * 2917) * mu) / ((4 * rho) * sigma)) := by
  simp only [n14, Expr.eval, n6_eval, n13_eval]

def n15 : Expr Symbol := .mul n3 n5
theorem n15_dim : Expr.HasDim coordinateUnits n15 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n3_dim n5_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n15_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n15 = (2917 * mu) := by
  simp only [n15, Expr.eval, n3_eval, n5_eval]

def n16 : Expr Symbol := .mul n2 n0
theorem n16_dim : Expr.HasDim coordinateUnits n16 (dimensions 0 0 0) := by
  apply castDim (Expr.HasDim.mul n2_dim n0_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n16_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n16 = ((-1) * 1) := by
  simp only [n16, Expr.eval, n2_eval, n0_eval]

def n17 : Expr Symbol := .add n16 n12
theorem n17_dim : Expr.HasDim coordinateUnits n17 (dimensions 0 0 0) := by
  exact Expr.HasDim.add n16_dim n12_dim
theorem n17_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n17 = (((-1) * 1) + sigma) := by
  simp only [n17, Expr.eval, n16_eval, n12_eval]

def n18 : Expr Symbol := .mul n15 n17
theorem n18_dim : Expr.HasDim coordinateUnits n18 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n15_dim n17_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n18_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n18 = ((2917 * mu) * (((-1) * 1) + sigma)) := by
  simp only [n18, Expr.eval, n15_eval, n17_eval]

def n19 : Expr Symbol := .div n18 n13
theorem n19_dim : Expr.HasDim coordinateUnits n19 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n18_dim n13_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n19_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n19 = (((2917 * mu) * (((-1) * 1) + sigma)) / ((4 * rho) * sigma)) := by
  simp only [n19, Expr.eval, n18_eval, n13_eval]

theorem stratum2_q3_stratum_root_coincidence_records_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 1 := by
  rerun_eval n0_eval

theorem stratum2_q3_stratum_root_coincidence_records_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 2 := by
  rerun_eval n1_eval

theorem stratum2_q3_stratum_root_coincidence_records_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n10 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 := by
  rerun_eval n10_eval

theorem stratum2_q3_stratum_root_coincidence_records_cell3 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n0 = 1 := by
  rerun_eval n0_eval

theorem stratum2_q3_stratum_root_coincidence_records_cell4 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n11 = 3 := by
  rerun_eval n11_eval

theorem stratum2_q3_stratum_root_coincidence_records_cell5 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n14 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 := by
  rerun_eval n14_eval

theorem stratum2_q3_stratum_root_coincidence_records_cell6 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n1 = 2 := by
  rerun_eval n1_eval

theorem stratum2_q3_stratum_root_coincidence_records_cell7 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n11 = 3 := by
  rerun_eval n11_eval

theorem stratum2_q3_stratum_root_coincidence_records_cell8 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n19 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 := by
  rerun_eval n19_eval

theorem stratum2_q3_stratum_root_coincidence_records_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n0 = 1 ∧
    Expr.eval (values rho mu sigma z k) n1 = 2 ∧
    Expr.eval (values rho mu sigma z k) n10 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 ∧
    Expr.eval (values rho mu sigma z k) n0 = 1 ∧
    Expr.eval (values rho mu sigma z k) n11 = 3 ∧
    Expr.eval (values rho mu sigma z k) n14 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 ∧
    Expr.eval (values rho mu sigma z k) n1 = 2 ∧
    Expr.eval (values rho mu sigma z k) n11 = 3 ∧
    Expr.eval (values rho mu sigma z k) n19 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 - referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 :=
  ⟨stratum2_q3_stratum_root_coincidence_records_cell0 rho mu sigma z k, stratum2_q3_stratum_root_coincidence_records_cell1 rho mu sigma z k, stratum2_q3_stratum_root_coincidence_records_cell2 rho mu sigma z k h0 h1, stratum2_q3_stratum_root_coincidence_records_cell3 rho mu sigma z k, stratum2_q3_stratum_root_coincidence_records_cell4 rho mu sigma z k, stratum2_q3_stratum_root_coincidence_records_cell5 rho mu sigma z k h0 h1, stratum2_q3_stratum_root_coincidence_records_cell6 rho mu sigma z k, stratum2_q3_stratum_root_coincidence_records_cell7 rho mu sigma z k, stratum2_q3_stratum_root_coincidence_records_cell8 rho mu sigma z k h0 h1⟩

theorem stratum2_q3_stratum_root_coincidence_records_dimensions :
    Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n1 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n10 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n11 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n14 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n1 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n11 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n19 (dimensions 2 (-2) 0) :=
  ⟨n0_dim, n1_dim, n10_dim, n0_dim, n11_dim, n14_dim, n1_dim, n11_dim, n19_dim⟩

end
end S10Audit.CAS.WLRecordsPerpendicular
