-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 0718871c408ea2839668d40f68c7ff143e9520e3be4dbb5dcd1e4cdad9f57ccd
import S10Audit.CAS.RootSupport

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.WLRootsGeneric
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar 0
theorem n0_dim : Expr.HasDim units n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 0) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = 0 := by
  rfl

def n1 : Expr Symbol := .scalar 1
theorem n1_dim : Expr.HasDim units n1 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 1) dimensions_zero.symm
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = 1 := by
  rfl

def n2 : Expr Symbol := .atom .z
theorem n2_dim : Expr.HasDim units n2 (dimensions 0 (-2) 0) := by
  exact Expr.HasDim.atom (u := units) .z
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = z := by
  rfl

def n3 : Expr Symbol := .pow n2 1
theorem n3_dim : Expr.HasDim units n3 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.pow 1 n2_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = (z ^ 1) := by
  simp only [n3, Expr.eval, n2_eval]

def n4 : Expr Symbol := .mul n1 n3
theorem n4_dim : Expr.HasDim units n4 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.mul n1_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = (1 * (z ^ 1)) := by
  simp only [n4, Expr.eval, n1_eval, n3_eval]

def n5 : Expr Symbol := .mul n0 n4
theorem n5_dim : Expr.HasDim units n5 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n4_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = (0 * (1 * (z ^ 1))) := by
  simp only [n5, Expr.eval, n0_eval, n4_eval]

def n6 : Expr Symbol := .atom (.k 0)
theorem n6_dim : Expr.HasDim units n6 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 0)
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = (k 0) := by
  rfl

def n7 : Expr Symbol := .pow n6 2
theorem n7_dim : Expr.HasDim units n7 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n6_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = ((k 0) ^ 2) := by
  simp only [n7, Expr.eval, n6_eval]

def n8 : Expr Symbol := .atom (.k 1)
theorem n8_dim : Expr.HasDim units n8 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 1)
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = (k 1) := by
  rfl

def n9 : Expr Symbol := .pow n8 2
theorem n9_dim : Expr.HasDim units n9 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n8_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = ((k 1) ^ 2) := by
  simp only [n9, Expr.eval, n8_eval]

def n10 : Expr Symbol := .add n7 n9
theorem n10_dim : Expr.HasDim units n10 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n7_dim n9_dim
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = (((k 0) ^ 2) + ((k 1) ^ 2)) := by
  simp only [n10, Expr.eval, n7_eval, n9_eval]

def n11 : Expr Symbol := .atom (.k 2)
theorem n11_dim : Expr.HasDim units n11 (dimensions (-1) 0 0) := by
  exact Expr.HasDim.atom (u := units) (.k 2)
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = (k 2) := by
  rfl

def n12 : Expr Symbol := .pow n11 2
theorem n12_dim : Expr.HasDim units n12 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.pow 2 n11_dim)
  norm_num [dimensions_pow, dimensions_zero]
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = ((k 2) ^ 2) := by
  simp only [n12, Expr.eval, n11_eval]

def n13 : Expr Symbol := .add n10 n12
theorem n13_dim : Expr.HasDim units n13 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n10_dim n12_dim
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = ((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) := by
  simp only [n13, Expr.eval, n10_eval, n12_eval]

def n14 : Expr Symbol := .atom .mu
theorem n14_dim : Expr.HasDim units n14 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := units) .mu
theorem n14_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n14 = mu := by
  rfl

def n15 : Expr Symbol := .mul n13 n14
theorem n15_dim : Expr.HasDim units n15 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n13_dim n14_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n15_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n15 = (((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) * mu) := by
  simp only [n15, Expr.eval, n13_eval, n14_eval]

def n16 : Expr Symbol := .atom .rho
theorem n16_dim : Expr.HasDim units n16 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := units) .rho
theorem n16_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n16 = rho := by
  rfl

def n17 : Expr Symbol := .div n15 n16
theorem n17_dim : Expr.HasDim units n17 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.div n15_dim n16_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n17_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n17 = ((((((k 0) ^ 2) + ((k 1) ^ 2)) + ((k 2) ^ 2)) * mu) / rho) := by
  simp only [n17, Expr.eval, n15_eval, n16_eval]

def n18 : Expr Symbol := .add n9 n12
theorem n18_dim : Expr.HasDim units n18 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n9_dim n12_dim
theorem n18_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n18 = (((k 1) ^ 2) + ((k 2) ^ 2)) := by
  simp only [n18, Expr.eval, n9_eval, n12_eval]

def n19 : Expr Symbol := .atom .sigma
theorem n19_dim : Expr.HasDim units n19 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := units) .sigma
theorem n19_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n19 = sigma := by
  rfl

def n20 : Expr Symbol := .mul n7 n19
theorem n20_dim : Expr.HasDim units n20 (dimensions (-2) 0 0) := by
  apply castDim (Expr.HasDim.mul n7_dim n19_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n20_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n20 = (((k 0) ^ 2) * sigma) := by
  simp only [n20, Expr.eval, n7_eval, n19_eval]

def n21 : Expr Symbol := .add n18 n20
theorem n21_dim : Expr.HasDim units n21 (dimensions (-2) 0 0) := by
  exact Expr.HasDim.add n18_dim n20_dim
theorem n21_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n21 = ((((k 1) ^ 2) + ((k 2) ^ 2)) + (((k 0) ^ 2) * sigma)) := by
  simp only [n21, Expr.eval, n18_eval, n20_eval]

def n22 : Expr Symbol := .mul n14 n21
theorem n22_dim : Expr.HasDim units n22 (dimensions (-3) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n14_dim n21_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n22_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n22 = (mu * ((((k 1) ^ 2) + ((k 2) ^ 2)) + (((k 0) ^ 2) * sigma))) := by
  simp only [n22, Expr.eval, n14_eval, n21_eval]

def n23 : Expr Symbol := .mul n16 n19
theorem n23_dim : Expr.HasDim units n23 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n16_dim n19_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n23_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n23 = (rho * sigma) := by
  simp only [n23, Expr.eval, n16_eval, n19_eval]

def n24 : Expr Symbol := .div n22 n23
theorem n24_dim : Expr.HasDim units n24 (dimensions 0 (-2) 0) := by
  apply castDim (Expr.HasDim.div n22_dim n23_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n24_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n24 = ((mu * ((((k 1) ^ 2) + ((k 2) ^ 2)) + (((k 0) ^ 2) * sigma))) / (rho * sigma)) := by
  simp only [n24, Expr.eval, n22_eval, n23_eval]

def n25 : Expr Symbol := .scalar 3
theorem n25_dim : Expr.HasDim units n25 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 3) dimensions_zero.symm
theorem n25_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n25 = 3 := by
  rfl

theorem q3_solutions_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n5 = referenceRoot rho mu sigma k 0 := by
  cas_eval n5_eval

theorem q3_solutions_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n17 = referenceRoot rho mu sigma k 1 := by
  cas_eval n17_eval

theorem q3_solutions_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n24 = referenceRoot rho mu sigma k 2 := by
  cas_eval n24_eval

theorem q3_solutions_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n5 = referenceRoot rho mu sigma k 0 ∧
    Expr.eval (values rho mu sigma z k) n17 = referenceRoot rho mu sigma k 1 ∧
    Expr.eval (values rho mu sigma z k) n24 = referenceRoot rho mu sigma k 2 :=
  ⟨q3_solutions_cell0 rho mu sigma z k, q3_solutions_cell1 rho mu sigma z k h0, q3_solutions_cell2 rho mu sigma z k h0 h1⟩

theorem q3_solutions_dimensions :
    Expr.HasDim units n5 (dimensions 0 (-2) 0) ∧
    Expr.HasDim units n17 (dimensions 0 (-2) 0) ∧
    Expr.HasDim units n24 (dimensions 0 (-2) 0) :=
  ⟨n5_dim, n17_dim, n24_dim⟩

theorem q3_distinct_roots_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n5 = referenceRoot rho mu sigma k 0 := by
  cas_eval n5_eval

theorem q3_distinct_roots_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n17 = referenceRoot rho mu sigma k 1 := by
  cas_eval n17_eval

theorem q3_distinct_roots_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n24 = referenceRoot rho mu sigma k 2 := by
  cas_eval n24_eval

theorem q3_distinct_roots_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n5 = referenceRoot rho mu sigma k 0 ∧
    Expr.eval (values rho mu sigma z k) n17 = referenceRoot rho mu sigma k 1 ∧
    Expr.eval (values rho mu sigma z k) n24 = referenceRoot rho mu sigma k 2 :=
  ⟨q3_distinct_roots_cell0 rho mu sigma z k, q3_distinct_roots_cell1 rho mu sigma z k h0, q3_distinct_roots_cell2 rho mu sigma z k h0 h1⟩

theorem q3_distinct_roots_dimensions :
    Expr.HasDim units n5 (dimensions 0 (-2) 0) ∧
    Expr.HasDim units n17 (dimensions 0 (-2) 0) ∧
    Expr.HasDim units n24 (dimensions 0 (-2) 0) :=
  ⟨n5_dim, n17_dim, n24_dim⟩

theorem q3_root_count_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 := by
  cas_eval n25_eval

theorem q3_root_count_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 :=
  q3_root_count_cell0 rho mu sigma z k

theorem q3_root_count_dimensions :
    Expr.HasDim units n25 (dimensions 0 0 0) :=
  n25_dim

theorem q3_root_candidate_count_before_filter_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 := by
  cas_eval n25_eval

theorem q3_root_candidate_count_before_filter_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 :=
  q3_root_candidate_count_before_filter_cell0 rho mu sigma z k

theorem q3_root_candidate_count_before_filter_dimensions :
    Expr.HasDim units n25 (dimensions 0 0 0) :=
  n25_dim

theorem q3_root_candidate_count_after_filter_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 := by
  cas_eval n25_eval

theorem q3_root_candidate_count_after_filter_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 :=
  q3_root_candidate_count_after_filter_cell0 rho mu sigma z k

theorem q3_root_candidate_count_after_filter_dimensions :
    Expr.HasDim units n25 (dimensions 0 0 0) :=
  n25_dim

theorem q3_root_list_counts_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 := by
  cas_eval n25_eval

theorem q3_root_list_counts_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 := by
  cas_eval n25_eval

theorem q3_root_list_counts_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n25 = 3 ∧
    Expr.eval (values rho mu sigma z k) n25 = 3 :=
  ⟨q3_root_list_counts_cell0 rho mu sigma z k, q3_root_list_counts_cell1 rho mu sigma z k⟩

theorem q3_root_list_counts_dimensions :
    Expr.HasDim units n25 (dimensions 0 0 0) ∧
    Expr.HasDim units n25 (dimensions 0 0 0) :=
  ⟨n25_dim, n25_dim⟩

end
end S10Audit.CAS.WLRootsGeneric
