-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 0718871c408ea2839668d40f68c7ff143e9520e3be4dbb5dcd1e4cdad9f57ccd
import S10Audit.CAS.RerunReference

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.WLRootsParallel
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar 0
theorem n0_dim : Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 0) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = 0 := by
  rfl

def n1 : Expr Symbol := .atom .mu
theorem n1_dim : Expr.HasDim coordinateUnits n1 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .mu
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = mu := by
  rfl

def n2 : Expr Symbol := .atom .rho
theorem n2_dim : Expr.HasDim coordinateUnits n2 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .rho
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = rho := by
  rfl

def n3 : Expr Symbol := .div n1 n2
theorem n3_dim : Expr.HasDim coordinateUnits n3 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n1_dim n2_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = (mu / rho) := by
  simp only [n3, Expr.eval, n1_eval, n2_eval]

def n4 : Expr Symbol := .mul n0 n3
theorem n4_dim : Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = (0 * (mu / rho)) := by
  simp only [n4, Expr.eval, n0_eval, n3_eval]

def n5 : Expr Symbol := .scalar 729
theorem n5_dim : Expr.HasDim coordinateUnits n5 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 729) dimensions_zero.symm
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = 729 := by
  rfl

def n6 : Expr Symbol := .mul n5 n1
theorem n6_dim : Expr.HasDim coordinateUnits n6 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n5_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = (729 * mu) := by
  simp only [n6, Expr.eval, n5_eval, n1_eval]

def n7 : Expr Symbol := .div n6 n2
theorem n7_dim : Expr.HasDim coordinateUnits n7 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n6_dim n2_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = ((729 * mu) / rho) := by
  simp only [n7, Expr.eval, n6_eval, n2_eval]

def n8 : Expr Symbol := .scalar 2
theorem n8_dim : Expr.HasDim coordinateUnits n8 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2) dimensions_zero.symm
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = 2 := by
  rfl

def n9 : Expr Symbol := .scalar 3
theorem n9_dim : Expr.HasDim coordinateUnits n9 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 3) dimensions_zero.symm
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = 3 := by
  rfl

theorem stratum1_q3_solutions_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma WLLoci.parallelPoint 0 := by
  rerun_eval n4_eval

theorem stratum1_q3_solutions_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n7 = referenceRoot rho mu sigma WLLoci.parallelPoint 1 := by
  rerun_eval n7_eval

theorem stratum1_q3_solutions_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n7 = referenceRoot rho mu sigma WLLoci.parallelPoint 1 := by
  rerun_eval n7_eval

theorem stratum1_q3_solutions_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma WLLoci.parallelPoint 0 ∧
    Expr.eval (values rho mu sigma z k) n7 = referenceRoot rho mu sigma WLLoci.parallelPoint 1 ∧
    Expr.eval (values rho mu sigma z k) n7 = referenceRoot rho mu sigma WLLoci.parallelPoint 1 :=
  ⟨stratum1_q3_solutions_cell0 rho mu sigma z k, stratum1_q3_solutions_cell1 rho mu sigma z k h0, stratum1_q3_solutions_cell2 rho mu sigma z k h0⟩

theorem stratum1_q3_solutions_dimensions :
    Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n7 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n7 (dimensions 2 (-2) 0) :=
  ⟨n4_dim, n7_dim, n7_dim⟩

theorem stratum1_q3_distinct_roots_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma WLLoci.parallelPoint 0 := by
  rerun_eval n4_eval

theorem stratum1_q3_distinct_roots_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n7 = referenceRoot rho mu sigma WLLoci.parallelPoint 1 := by
  rerun_eval n7_eval

theorem stratum1_q3_distinct_roots_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma WLLoci.parallelPoint 0 ∧
    Expr.eval (values rho mu sigma z k) n7 = referenceRoot rho mu sigma WLLoci.parallelPoint 1 :=
  ⟨stratum1_q3_distinct_roots_cell0 rho mu sigma z k, stratum1_q3_distinct_roots_cell1 rho mu sigma z k h0⟩

theorem stratum1_q3_distinct_roots_dimensions :
    Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n7 (dimensions 2 (-2) 0) :=
  ⟨n4_dim, n7_dim⟩

theorem stratum1_q3_root_count_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n8 = 2 := by
  rerun_eval n8_eval

theorem stratum1_q3_root_count_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n8 = 2 :=
  stratum1_q3_root_count_cell0 rho mu sigma z k

theorem stratum1_q3_root_count_dimensions :
    Expr.HasDim coordinateUnits n8 (dimensions 0 0 0) :=
  n8_dim

theorem stratum1_q3_root_candidate_count_before_filter_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n9 = 3 := by
  rerun_eval n9_eval

theorem stratum1_q3_root_candidate_count_before_filter_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n9 = 3 :=
  stratum1_q3_root_candidate_count_before_filter_cell0 rho mu sigma z k

theorem stratum1_q3_root_candidate_count_before_filter_dimensions :
    Expr.HasDim coordinateUnits n9 (dimensions 0 0 0) :=
  n9_dim

theorem stratum1_q3_root_candidate_count_after_filter_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n9 = 3 := by
  rerun_eval n9_eval

theorem stratum1_q3_root_candidate_count_after_filter_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n9 = 3 :=
  stratum1_q3_root_candidate_count_after_filter_cell0 rho mu sigma z k

theorem stratum1_q3_root_candidate_count_after_filter_dimensions :
    Expr.HasDim coordinateUnits n9 (dimensions 0 0 0) :=
  n9_dim

theorem stratum1_q3_root_list_counts_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n9 = 3 := by
  rerun_eval n9_eval

theorem stratum1_q3_root_list_counts_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n8 = 2 := by
  rerun_eval n8_eval

theorem stratum1_q3_root_list_counts_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n9 = 3 ∧
    Expr.eval (values rho mu sigma z k) n8 = 2 :=
  ⟨stratum1_q3_root_list_counts_cell0 rho mu sigma z k, stratum1_q3_root_list_counts_cell1 rho mu sigma z k⟩

theorem stratum1_q3_root_list_counts_dimensions :
    Expr.HasDim coordinateUnits n9 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n8 (dimensions 0 0 0) :=
  ⟨n9_dim, n8_dim⟩

end
end S10Audit.CAS.WLRootsParallel
