-- Generated by scripts/S10_lean_cas_bridge.py; use --check to verify provenance.
-- Input SHA-256: 0718871c408ea2839668d40f68c7ff143e9520e3be4dbb5dcd1e4cdad9f57ccd
import S10Audit.CAS.RerunReference

set_option backward.isDefEq.respectTransparency false

namespace S10Audit.CAS.WLRootsPerpendicular
open S10Pilot S10Anisotropic
noncomputable section

def n0 : Expr Symbol := .scalar 0
theorem n0_dim : Expr.HasDim coordinateUnits n0 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 0) dimensions_zero.symm
theorem n0_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n0 = 0 := by
  rfl

def n1 : Expr Symbol := .atom .mu
theorem n1_dim : Expr.HasDim coordinateUnits n1 (dimensions (-1) (-2) 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .mu
theorem n1_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n1 = mu := by
  rfl

def n2 : Expr Symbol := .atom .rho
theorem n2_dim : Expr.HasDim coordinateUnits n2 (dimensions (-3) 0 1) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .rho
theorem n2_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n2 = rho := by
  rfl

def n3 : Expr Symbol := .div n1 n2
theorem n3_dim : Expr.HasDim coordinateUnits n3 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n1_dim n2_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n3_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n3 = (mu / rho) := by
  simp only [n3, Expr.eval, n1_eval, n2_eval]

def n4 : Expr Symbol := .mul n0 n3
theorem n4_dim : Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.mul n0_dim n3_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n4_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n4 = (0 * (mu / rho)) := by
  simp only [n4, Expr.eval, n0_eval, n3_eval]

def n5 : Expr Symbol := .scalar 2917
theorem n5_dim : Expr.HasDim coordinateUnits n5 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 2917) dimensions_zero.symm
theorem n5_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n5 = 2917 := by
  rfl

def n6 : Expr Symbol := .mul n5 n1
theorem n6_dim : Expr.HasDim coordinateUnits n6 (dimensions (-1) (-2) 1) := by
  apply castDim (Expr.HasDim.mul n5_dim n1_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n6_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n6 = (2917 * mu) := by
  simp only [n6, Expr.eval, n5_eval, n1_eval]

def n7 : Expr Symbol := .scalar 4
theorem n7_dim : Expr.HasDim coordinateUnits n7 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 4) dimensions_zero.symm
theorem n7_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n7 = 4 := by
  rfl

def n8 : Expr Symbol := .mul n7 n2
theorem n8_dim : Expr.HasDim coordinateUnits n8 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n7_dim n2_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n8_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n8 = (4 * rho) := by
  simp only [n8, Expr.eval, n7_eval, n2_eval]

def n9 : Expr Symbol := .div n6 n8
theorem n9_dim : Expr.HasDim coordinateUnits n9 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n6_dim n8_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n9_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n9 = ((2917 * mu) / (4 * rho)) := by
  simp only [n9, Expr.eval, n6_eval, n8_eval]

def n10 : Expr Symbol := .atom .sigma
theorem n10_dim : Expr.HasDim coordinateUnits n10 (dimensions 0 0 0) := by
  exact Expr.HasDim.atom (u := coordinateUnits) .sigma
theorem n10_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n10 = sigma := by
  rfl

def n11 : Expr Symbol := .mul n8 n10
theorem n11_dim : Expr.HasDim coordinateUnits n11 (dimensions (-3) 0 1) := by
  apply castDim (Expr.HasDim.mul n8_dim n10_dim)
  norm_num [dimensions_mul, dimensions_zero]
theorem n11_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n11 = ((4 * rho) * sigma) := by
  simp only [n11, Expr.eval, n8_eval, n10_eval]

def n12 : Expr Symbol := .div n6 n11
theorem n12_dim : Expr.HasDim coordinateUnits n12 (dimensions 2 (-2) 0) := by
  apply castDim (Expr.HasDim.div n6_dim n11_dim)
  norm_num [dimensions_div, dimensions_zero]
theorem n12_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n12 = ((2917 * mu) / ((4 * rho) * sigma)) := by
  simp only [n12, Expr.eval, n6_eval, n11_eval]

def n13 : Expr Symbol := .scalar 3
theorem n13_dim : Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) := by
  exact castDim (Expr.HasDim.scalar 3) dimensions_zero.symm
theorem n13_eval (rho mu sigma z : ℝ) (k : Vec 3) :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rfl

theorem stratum2_q3_solutions_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 := by
  rerun_eval n4_eval

theorem stratum2_q3_solutions_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n9 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 := by
  rerun_eval n9_eval

theorem stratum2_q3_solutions_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n12 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 := by
  rerun_eval n12_eval

theorem stratum2_q3_solutions_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 ∧
    Expr.eval (values rho mu sigma z k) n9 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 ∧
    Expr.eval (values rho mu sigma z k) n12 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 :=
  ⟨stratum2_q3_solutions_cell0 rho mu sigma z k, stratum2_q3_solutions_cell1 rho mu sigma z k h0, stratum2_q3_solutions_cell2 rho mu sigma z k h0 h1⟩

theorem stratum2_q3_solutions_dimensions :
    Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n9 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n12 (dimensions 2 (-2) 0) :=
  ⟨n4_dim, n9_dim, n12_dim⟩

theorem stratum2_q3_distinct_roots_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 := by
  rerun_eval n4_eval

theorem stratum2_q3_distinct_roots_cell1 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) :
    Expr.eval (values rho mu sigma z k) n9 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 := by
  rerun_eval n9_eval

theorem stratum2_q3_distinct_roots_cell2 (rho mu sigma z : ℝ) (k : Vec 3) (_h0 : rho ≠ 0) (_h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n12 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 := by
  rerun_eval n12_eval

theorem stratum2_q3_distinct_roots_values (rho mu sigma z : ℝ) (k : Vec 3) (h0 : rho ≠ 0) (h1 : sigma ≠ 0) :
    Expr.eval (values rho mu sigma z k) n4 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 0 ∧
    Expr.eval (values rho mu sigma z k) n9 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 1 ∧
    Expr.eval (values rho mu sigma z k) n12 = referenceRoot rho mu sigma WLLoci.perpendicularPoint 2 :=
  ⟨stratum2_q3_distinct_roots_cell0 rho mu sigma z k, stratum2_q3_distinct_roots_cell1 rho mu sigma z k h0, stratum2_q3_distinct_roots_cell2 rho mu sigma z k h0 h1⟩

theorem stratum2_q3_distinct_roots_dimensions :
    Expr.HasDim coordinateUnits n4 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n9 (dimensions 2 (-2) 0) ∧
    Expr.HasDim coordinateUnits n12 (dimensions 2 (-2) 0) :=
  ⟨n4_dim, n9_dim, n12_dim⟩

theorem stratum2_q3_root_count_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rerun_eval n13_eval

theorem stratum2_q3_root_count_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 :=
  stratum2_q3_root_count_cell0 rho mu sigma z k

theorem stratum2_q3_root_count_dimensions :
    Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) :=
  n13_dim

theorem stratum2_q3_root_candidate_count_before_filter_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rerun_eval n13_eval

theorem stratum2_q3_root_candidate_count_before_filter_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 :=
  stratum2_q3_root_candidate_count_before_filter_cell0 rho mu sigma z k

theorem stratum2_q3_root_candidate_count_before_filter_dimensions :
    Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) :=
  n13_dim

theorem stratum2_q3_root_candidate_count_after_filter_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rerun_eval n13_eval

theorem stratum2_q3_root_candidate_count_after_filter_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 :=
  stratum2_q3_root_candidate_count_after_filter_cell0 rho mu sigma z k

theorem stratum2_q3_root_candidate_count_after_filter_dimensions :
    Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) :=
  n13_dim

theorem stratum2_q3_root_list_counts_cell0 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rerun_eval n13_eval

theorem stratum2_q3_root_list_counts_cell1 (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 := by
  rerun_eval n13_eval

theorem stratum2_q3_root_list_counts_values (rho mu sigma z : ℝ) (k : Vec 3)  :
    Expr.eval (values rho mu sigma z k) n13 = 3 ∧
    Expr.eval (values rho mu sigma z k) n13 = 3 :=
  ⟨stratum2_q3_root_list_counts_cell0 rho mu sigma z k, stratum2_q3_root_list_counts_cell1 rho mu sigma z k⟩

theorem stratum2_q3_root_list_counts_dimensions :
    Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) ∧
    Expr.HasDim coordinateUnits n13 (dimensions 0 0 0) :=
  ⟨n13_dim, n13_dim⟩

end
end S10Audit.CAS.WLRootsPerpendicular
