import S11D3Bulk.Census

/-! K1–K4: all new theorem roots, including analytic helpers. -/
#print axioms S11D3Bulk.density_identity
#print axioms S11D3Bulk.all_invariant_densities
#print axioms S11D3Bulk.lagrangian_increment
#print axioms S11D3Bulk.lagrangian_variation
#print axioms S11D3Bulk.momentum_eq
#print axioms S11D3Bulk.momentum_smul
#print axioms S11D3Bulk.smooth_momentum
#print axioms S11D3Bulk.smooth_eulerLagrange
#print axioms S11D3Bulk.partial_add
#print axioms S11D3Bulk.partial_sub
#print axioms S11D3Bulk.partial_neg
#print axioms S11D3Bulk.partial_const_mul
#print axioms S11D3Bulk.partial_mul
#print axioms S11D3Bulk.partial_zero
#print axioms S11D3Bulk.partial_second
#print axioms S11D3Bulk.partial_commute
#print axioms S11D3Bulk.linearDensity_eq
#print axioms S11D3Bulk.lagrangian_change
#print axioms S11D3Bulk.linearDensity_self
#print axioms S11D3Bulk.integrable_linear_term
#print axioms S11D3Bulk.integrable_linearDensity
#print axioms S11D3Bulk.integrable_test_lagrangian
#print axioms S11D3Bulk.relative_density_integrable
#print axioms S11D3Bulk.relativeAction_expansion
#print axioms S11D3Bulk.relativeAction_hasDerivAt
#print axioms S11D3Bulk.integrable_el_term
#print axioms S11D3Bulk.integrated_variation_by_parts
#print axioms S11D3Bulk.relativeAction_deriv_eq_eulerLagrange
#print axioms S11D3Bulk.actionStationary_iff_eulerLagrange
#print axioms S11D3Bulk.gradDiv_eq
#print axioms S11D3Bulk.eulerLagrange_eq
#print axioms S11D3Bulk.boundary_identity
#print axioms S11D3Bulk.null_density_is_divergence
#print axioms S11D3Bulk.homogeneous_operator
#print axioms S11D3Bulk.momentum_contraction
#print axioms S11D3Bulk.eulerLagrange_planeWave
#print axioms S11D3Bulk.modal_longitudinal
#print axioms S11D3Bulk.modal_transverse
#print axioms S11D3Bulk.modal_zero_wavevector
#print axioms S11D3Bulk.bulkEquivalent_iff
#print axioms S11D3Bulk.bulkEquivalent_response
#print axioms S11D3Bulk.response_surjective
#print axioms S11D3Bulk.variationallyNull_iff
#print axioms S11D3Bulk.null_parameterization
#print axioms S11D3Bulk.nullSpace_identification
#print axioms S11D3Bulk.bulk_response_dimension
#print axioms S11D3Bulk.null_dimension
#print axioms S11D3Bulk.null_nonzero_example
#print axioms S11D3Bulk.exists_nonzero_firstVariation
