import S11D5Invariants.Controls

/-! D5.1–D5.4 selected standard-axiom audit roots. -/
#print axioms S11D5Invariants.coordinates_decode
#print axioms S11D5Invariants.decode_coordinates
#print axioms S11D5Invariants.frame_expansion
#print axioms S11D5Invariants.quadratic_representation
#print axioms S11D5Invariants.sum_five
#print axioms S11D5Invariants.conjugate_neg
#print axioms S11D5Invariants.orthogonal_det
#print axioms S11D5Invariants.SO_iff_O
#print axioms S11D5Invariants.rotationXY_orthogonal
#print axioms S11D5Invariants.rotationYZ_orthogonal
#print axioms S11D5Invariants.rotationZW_orthogonal
#print axioms S11D5Invariants.rotationWV_orthogonal
#print axioms S11D5Invariants.coordinates_rotationXY
#print axioms S11D5Invariants.coordinates_rotationYZ
#print axioms S11D5Invariants.coordinates_rotationZW
#print axioms S11D5Invariants.coordinates_rotationWV
#print axioms S11D5Invariants.reflection_orthogonal
#print axioms S11D5Invariants.reflection_det
#print axioms S11D5Invariants.trace_conjugate
#print axioms S11D5Invariants.conjugate_mul
#print axioms S11D5Invariants.conjugate_transpose
#print axioms S11D5Invariants.traceSquare_apply
#print axioms S11D5Invariants.traceOfSquare_apply
#print axioms S11D5Invariants.frobeniusSquare_apply
#print axioms S11D5Invariants.invariantForm_apply
#print axioms S11D5Invariants.invariantForm_O
#print axioms S11D5Invariants.invariantForm_SO
#print axioms S11D5Invariants.polynomial_vec
#print axioms S11D5Invariants.invariant_polynomial
#print axioms S11D5Invariants.SO_classification
#print axioms S11D5Invariants.O_classification
#print axioms S11D5Invariants.invariantForm_injective
#print axioms S11D5Invariants.SO_unique
#print axioms S11D5Invariants.odd_classification
#print axioms S11D5Invariants.so_eq_o
#print axioms S11D5Invariants.odd_eq_bot
#print axioms S11D5Invariants.soMap_bijective
#print axioms S11D5Invariants.so_dimension
#print axioms S11D5Invariants.o_dimension
#print axioms S11D5Invariants.odd_dimension
#print axioms S11D5Invariants.census
#print axioms S11D5Invariants.trace_not_omittable
#print axioms S11D5Invariants.traceOfSquare_not_omittable
#print axioms S11D5Invariants.frobenius_not_omittable
#print axioms S11D5Invariants.nonzero_invariant_exists
#print axioms S11D5Invariants.zero_invariant
#print axioms S11D5Invariants.nonzero_odd_impossible
#print axioms S11D5Invariants.single_entry_not_invariant
#print axioms S11D5Invariants.trace_normalization
#print axioms S11D5Invariants.pair_normalization
#print axioms S11D5Invariants.frobenius_normalization
