import S11D4Bulk.Controls

/-! D4C.1–D4C.4: selected roots include all new theorem declarations. -/
#print axioms S11D4Bulk.Even.lagrangian_increment
#print axioms S11D4Bulk.Even.lagrangian_variation
#print axioms S11D4Bulk.Even.momentum_eq
#print axioms S11D4Bulk.Even.momentum_smul
#print axioms S11D4Bulk.Even.smooth_momentum
#print axioms S11D4Bulk.Even.smooth_eulerLagrange
#print axioms S11D4Bulk.density_identity
#print axioms S11D4Bulk.all_invariant_densities
#print axioms S11D4Bulk.lagrangian_increment
#print axioms S11D4Bulk.lagrangian_variation
#print axioms S11D4Bulk.momentum_eq
#print axioms S11D4Bulk.momentum_time
#print axioms S11D4Bulk.smooth_momentum
#print axioms S11D4Bulk.smooth_eulerLagrange
#print axioms S11D4Bulk.eulerLagrange_even
#print axioms S11D4Bulk.linearDensity_eq
#print axioms S11D4Bulk.lagrangian_change
#print axioms S11D4Bulk.linearDensity_self
#print axioms S11D4Bulk.integrable_linear_term
#print axioms S11D4Bulk.integrable_linearDensity
#print axioms S11D4Bulk.integrable_test_lagrangian
#print axioms S11D4Bulk.relative_density_integrable
#print axioms S11D4Bulk.relativeAction_expansion
#print axioms S11D4Bulk.relativeAction_hasDerivAt
#print axioms S11D4Bulk.integrable_el_term
#print axioms S11D4Bulk.integrated_variation_by_parts
#print axioms S11D4Bulk.relativeAction_deriv_eq_eulerLagrange
#print axioms S11D4Bulk.actionStationary_iff_eulerLagrange
#print axioms S11D4Bulk.Even.gradDiv_eq
#print axioms S11D4Bulk.Even.eulerLagrange_eq
#print axioms S11D4Bulk.Even.boundary_identity
#print axioms S11D4Bulk.Even.homogeneous_operator
#print axioms S11D4Bulk.Even.momentum_contraction
#print axioms S11D4Bulk.Even.eulerLagrange_planeWave
#print axioms S11D4Bulk.Even.modal_longitudinal
#print axioms S11D4Bulk.Even.modal_transverse
#print axioms S11D4Bulk.Even.modal_zero_wavevector
#print axioms S11D4Bulk.eulerLagrange_eq
#print axioms S11D4Bulk.null_density_is_divergence
#print axioms S11D4Bulk.homogeneous_operator
#print axioms S11D4Bulk.eulerLagrange_planeWave
#print axioms S11D4Bulk.modal_longitudinal
#print axioms S11D4Bulk.modal_transverse
#print axioms S11D4Bulk.modal_zero_wavevector
#print axioms S11D4Bulk.bulkEquivalent_iff
#print axioms S11D4Bulk.bulkEquivalent_response
#print axioms S11D4Bulk.response_surjective
#print axioms S11D4Bulk.variationallyNull_iff
#print axioms S11D4Bulk.null_parameterization
#print axioms S11D4Bulk.nullSpace_identification
#print axioms S11D4Bulk.bulk_response_dimension
#print axioms S11D4Bulk.null_dimension
#print axioms S11D4Bulk.null_nonzero_example
#print axioms S11D4Bulk.exists_nonzero_firstVariation
#print axioms S11D4Bulk.even_null_density_nonzero
#print axioms S11D4Bulk.even_momentum_normalization
#print axioms S11D4Bulk.odd_density_normalization
#print axioms S11D4Bulk.odd_momentum_normalization
#print axioms S11D4Bulk.partial_coordinate
#print axioms S11D4Bulk.affineWitness_smooth
#print axioms S11D4Bulk.affineWitness_jet
#print axioms S11D4Bulk.even_current_normalization
#print axioms S11D4Bulk.odd_current_normalization
#print axioms S11D4Bulk.transverse_response
#print axioms S11D4Bulk.longitudinal_response
#print axioms S11D4Bulk.mixed_null_positive
#print axioms S11D4Bulk.mixed_null_firstVariation
