import S11D5Bulk.Controls

/-! D5B.1–D5B.4: audit all new theorem roots. -/
#print axioms S11D5Bulk.density_identity
#print axioms S11D5Bulk.all_invariant_densities
#print axioms S11D5Bulk.lagrangian_increment
#print axioms S11D5Bulk.lagrangian_variation
#print axioms S11D5Bulk.momentum_eq
#print axioms S11D5Bulk.momentum_time
#print axioms S11D5Bulk.momentum_smul
#print axioms S11D5Bulk.smooth_momentum
#print axioms S11D5Bulk.smooth_eulerLagrange
#print axioms S11D5Bulk.linearDensity_eq
#print axioms S11D5Bulk.lagrangian_change
#print axioms S11D5Bulk.linearDensity_self
#print axioms S11D5Bulk.integrable_linear_term
#print axioms S11D5Bulk.integrable_linearDensity
#print axioms S11D5Bulk.integrable_test_lagrangian
#print axioms S11D5Bulk.relative_density_integrable
#print axioms S11D5Bulk.relativeAction_expansion
#print axioms S11D5Bulk.relativeAction_hasDerivAt
#print axioms S11D5Bulk.integrable_el_term
#print axioms S11D5Bulk.integrated_variation_by_parts
#print axioms S11D5Bulk.relativeAction_deriv_eq_eulerLagrange
#print axioms S11D5Bulk.actionStationary_iff_eulerLagrange
#print axioms S11D5Bulk.gradDiv_eq
#print axioms S11D5Bulk.eulerLagrange_eq
#print axioms S11D5Bulk.boundary_identity
#print axioms S11D5Bulk.null_density_is_divergence
#print axioms S11D5Bulk.homogeneous_operator
#print axioms S11D5Bulk.momentum_contraction
#print axioms S11D5Bulk.eulerLagrange_planeWave
#print axioms S11D5Bulk.modal_longitudinal
#print axioms S11D5Bulk.modal_transverse
#print axioms S11D5Bulk.modal_zero_wavevector
#print axioms S11D5Bulk.bulkEquivalent_iff
#print axioms S11D5Bulk.bulkEquivalent_response
#print axioms S11D5Bulk.response_surjective
#print axioms S11D5Bulk.variationallyNull_iff
#print axioms S11D5Bulk.null_parameterization
#print axioms S11D5Bulk.nullSpace_identification
#print axioms S11D5Bulk.bulk_response_dimension
#print axioms S11D5Bulk.null_dimension
#print axioms S11D5Bulk.null_nonzero_example
#print axioms S11D5Bulk.exists_nonzero_firstVariation
#print axioms S11D5Bulk.even_null_density_nonzero
#print axioms S11D5Bulk.even_momentum_normalization
#print axioms S11D5Bulk.partial_coordinate
#print axioms S11D5Bulk.affineWitness_smooth
#print axioms S11D5Bulk.affineWitness_jet
#print axioms S11D5Bulk.even_current_normalization
#print axioms S11D5Bulk.transverse_response
#print axioms S11D5Bulk.longitudinal_response
#print axioms S11D5Bulk.null_positive
#print axioms S11D5Bulk.null_firstVariation

#print axioms S11D5Bulk.fifth_transverse_response
#print axioms S11D5Bulk.fifth_longitudinal_response
