import S11OddDynamics.Mixing

/-! E1–E4 theorem dependency audit. -/
#print axioms S11OddDynamics.density_identity
#print axioms S11OddDynamics.lagrangian_increment
#print axioms S11OddDynamics.lagrangian_smul
#print axioms S11OddDynamics.lagrangian_variation
#print axioms S11OddDynamics.momentum_eq
#print axioms S11OddDynamics.momentum_smul
#print axioms S11OddDynamics.smooth_momentum
#print axioms S11OddDynamics.smooth_eulerLagrange
#print axioms S11OddDynamics.coordDeriv_const_mul
#print axioms S11OddDynamics.coordDeriv_zero
#print axioms S11OddDynamics.eulerLagrange_eq
#print axioms S11OddDynamics.modalAction_eq
#print axioms S11OddDynamics.modal_variation
#print axioms S11OddDynamics.momentum_contraction
#print axioms S11OddDynamics.eulerLagrange_planeWave
#print axioms S11OddDynamics.linearDensity_eq
#print axioms S11OddDynamics.lagrangian_change
#print axioms S11OddDynamics.linearDensity_self
#print axioms S11OddDynamics.integrable_linear_term
#print axioms S11OddDynamics.integrable_linearDensity
#print axioms S11OddDynamics.integrable_test_lagrangian
#print axioms S11OddDynamics.relative_density_integrable
#print axioms S11OddDynamics.relativeAction_expansion
#print axioms S11OddDynamics.relativeAction_hasDerivAt
#print axioms S11OddDynamics.integrable_el_term
#print axioms S11OddDynamics.integrated_variation_by_parts
#print axioms S11OddDynamics.relativeAction_deriv_eq_eulerLagrange
#print axioms S11OddDynamics.actionStationary_iff_eulerLagrange
#print axioms S11OddDynamics.dot_turn
#print axioms S11OddDynamics.turn_dot
#print axioms S11OddDynamics.normSq_turn
#print axioms S11OddDynamics.normSq_eq_zero_iff
#print axioms S11OddDynamics.polarization_reconstruction
#print axioms S11OddDynamics.polarization_decomposition
#print axioms S11OddDynamics.modalOperator_longitudinal
#print axioms S11OddDynamics.modalOperator_transverse
#print axioms S11OddDynamics.cross_pairing
#print axioms S11OddDynamics.mixing_iff
#print axioms S11OddDynamics.modalOperator_zero_beta
#print axioms S11OddDynamics.modalOperator_zero_wavevector
#print axioms S11OddDynamics.mixing_cases
#print axioms S11OddDynamics.witness_smooth
#print axioms S11OddDynamics.witness_eulerLagrange
#print axioms S11OddDynamics.witness_not_stationary
#print axioms S11OddDynamics.exists_nonzero_firstVariation
#print axioms S11OddDynamics.zero_beta_stationary
#print axioms S11OddDynamics.variationallyNull_iff
