#!/usr/bin/env python3
from __future__ import annotations
import sympy as sp


def banner(title: str) -> None:
    line = "=" * 88
    print("\n" + line)
    print(title)
    print(line)


def expect_zero(name: str, expr):
    if isinstance(expr, sp.MatrixBase):
        expr = expr.applyfunc(lambda z: sp.simplify(sp.expand(z)))
        print(f"{name} =")
        sp.pprint(expr)
        if any(entry != 0 for entry in expr):
            raise AssertionError(f"{name} is not zero")
    else:
        expr = sp.simplify(sp.expand(expr))
        print(f"{name} = {expr}")
        if expr != 0:
            raise AssertionError(f"{name} is not zero")


"""
5pn_stage180_adiabatic_elastic_orbit_lock_summary.py

Stage 180 — consolidated theorem ledger after adding the exact projector/compiler
for the adiabatic-elastic branch-selection problem.
"""

banner("STAGE 180 — CONSOLIDATED ADIABATIC-ELASTIC ORBIT-LOCK LEDGER")

chi0s, deltaUs = sp.symbols("chi0_star deltaU_star", positive=True, real=True)
Estar, Fstar = sp.symbols("E_star F_star", real=True)
eps_eta_star = sp.symbols("epsilon_eta_star", positive=True, real=True)

# Observable -> quotient -> dependent mismatch chain.
Theta1, Xi1, Rsum = sp.symbols("Theta_1 Xi_1 Rsum", real=True)
dlnCtr = sp.simplify(- (1 + chi0s) * (1 + deltaUs) * (1 + chi0s + deltaUs) / (chi0s * deltaUs) * Theta1)
dlnCnt = sp.simplify(Xi1 + 2 * (1 + chi0s + deltaUs) / deltaUs * Theta1)
dlnEta = sp.simplify(- (1 - eps_eta_star) / eps_eta_star * Rsum)

mT = sp.simplify(dlnCtr / (1 + chi0s))
mKeta = sp.simplify(-dlnEta)
mMu = sp.simplify(dlnCnt + Fstar * dlnCtr / (1 + chi0s) - dlnEta)

print("mismatch_T(Theta_1) =", mT)
print("mismatch_Keta(R_1+Xi_1) =", mKeta)
print("mismatch_mu(Theta_1,Xi_1,R_1+Xi_1) =", mMu)

# Zero-defect specialization.
zero_defect = {Theta1: 0, Xi1: 0, Rsum: 0}
expect_zero("mismatch_T on zero-defect branch", mT.subs(zero_defect))
expect_zero("mismatch_Keta on zero-defect branch", mKeta.subs(zero_defect))
expect_zero("mismatch_mu on zero-defect branch", mMu.subs(zero_defect))

print("\nAdiabatic-elastic verdict:")
print("  delta ln Theta_w = 0 kills the thermal wall channel,")
print("  eps_L = eps_v = eps_T = 0 kills the scalar off-bundle escape,")
print("  and the remaining branch-selection theorem is exactly the vanishing of the")
print("  dependent-coordinate mismatch triple above.")

print("\nEquivalently, the true moving-throat branch is locked to one G_* orbit iff")
print("  Theta_1 = Xi_1 = R_1 + Xi_1 = 0,")
print("or, microscopically, iff")
print("  (Delta_T, Delta_Keta, Delta_mu)")
print("follow the exact Stage-170 orbit law generated by the five free similarity directions.")

banner("FINAL STAGE-180 LEDGER")
print("1. The adiabatic-elastic closure removes every first-order failure channel except")
print("   motion in the exact Stage-170 quotient coordinates.")
print("2. The quotient projector/compiler from Stages 175–179 shows that this remaining")
print("   motion is equivalent to the mismatch of the dependent microscopic triple")
print("      (Delta_T, Delta_Keta, Delta_mu)")
print("   from the exact single-orbit law.")
print("3. Therefore the remaining PDE theorem gap is now fully localized:")
print("   prove that the actual moving-throat dynamics makes those three dependent")
print("   coordinates follow the Stage-170 orbit law on the adiabatic-elastic branch.")
print("4. If that is true, the branch stays on one exact G_* orbit and the full first-order")
print("   weak-axisymmetric defect vanishes automatically.")
