#!/usr/bin/env python3
"""
Broad-sweep numbering-reconciliation INVENTORY generator (read-only).

Scope: notes/stages/moving_throat_pde_stageNNN_*.md ONLY (the ~236 stage notes).
Emits an exhaustive candidate worklist of every body cross-reference token that
could be a stale stage number, classified by direction relative to the note's OWN
canonical number (from its filename). This is the deferred ~1,200-mention pool that
Phase 1 (deterministic A/B/C) and Phase 2 (Class-D high-signal 57 citing notes +
deferred tail) did NOT individually resolve.

NEVER decides stale-vs-canonical here -- that is content work for the classifier
agents. This only enumerates candidates + context so nothing is missed.

Token forms captured (body only; the H1 line 1 is Class-B, already done):
  - Stage NNN  / Stage-NNN / Stages NNN(-MMM)   -> bare prose refs (+ ranges)
  - \mathcal S_{NNN} / \mathcal{S}_{NNN} / S_{NNN}  -> object-subscript refs
  - stage:NNN  -> \ref/\label style refs
  - stageNNN_<stem>  -> stem citations living in body prose

Direction (per cited number c vs self s): fwd (c>s) | back (c<s) | self (c==s).
PRIMARY pool = forward bare-prose refs + ALL special-form refs (these are where the
stale-old-number-for-an-upstream-stage pattern lives). SECONDARY = backward bare
refs (mostly genuine upstream citations; lower yield, listed collapsed for a later
optional pass).
"""
import os, re, glob

NOTES = os.path.join(os.path.dirname(__file__), "..", "notes", "stages")
OUT = os.path.join(os.path.dirname(__file__), "NUMBERING_BROAD_SWEEP_WORKLIST.md")

re_self = re.compile(r"stage(\d{3})_")
# bare prose: Stage / Stages, optional hyphen/space, number, optional range tail
re_bare = re.compile(r"\bStages?[ \-]?(\d{1,3})(?:\s*[–\-]\s*(\d{1,3}))?")
re_mathcal = re.compile(r"\\mathcal\s*\{?\s*S\s*\}?_\{?(\d{1,3})\}?")
re_label = re.compile(r"stage:(\d{1,3})")
re_stem = re.compile(r"\bstage(\d{3})_[a-z0-9_]+")

def band(n):
    # cluster partition for parallel classifier agents
    for lo, hi in [(1,90),(91,135),(136,163),(164,200),(201,234),(235,253)]:
        if lo <= n <= hi:
            return f"{lo:03d}-{hi:03d}"
    return "other"

rows = []  # (self, file, lineno, kind, cited, direction, text)
for path in sorted(glob.glob(os.path.join(NOTES, "moving_throat_pde_stage*.md"))):
    fn = os.path.basename(path)
    m = re_self.search(fn)
    if not m:
        continue
    self = int(m.group(1))
    with open(path, encoding="utf-8") as fh:
        lines = fh.readlines()
    for i, line in enumerate(lines, start=1):
        if i == 1:
            continue  # H1 = Class B (done)
        for mm in re_bare.finditer(line):
            c = int(mm.group(1))
            if c < 1 or c > 253:
                continue
            d = "fwd" if c > self else ("back" if c < self else "self")
            rng = mm.group(2)
            kind = "bare-range" if rng else "bare"
            cited = f"{c}-{rng}" if rng else str(c)
            rows.append((self, fn, i, kind, cited, d, line.strip()))
        for mm in re_mathcal.finditer(line):
            c = int(mm.group(1))
            d = "fwd" if c > self else ("back" if c < self else "self")
            rows.append((self, fn, i, "mathcalS", str(c), d, line.strip()))
        for mm in re_label.finditer(line):
            c = int(mm.group(1))
            d = "fwd" if c > self else ("back" if c < self else "self")
            rows.append((self, fn, i, "label-ref", str(c), d, line.strip()))
        for mm in re_stem.finditer(line):
            c = int(mm.group(1))
            if c == self:
                continue  # self-stem in own body = fine
            d = "fwd" if c > self else "back"
            rows.append((self, fn, i, "stem-cite", str(c), d, line.strip()))

# de-dup identical (file,line,kind,cited)
seen = set(); uniq = []
for r in rows:
    key = (r[1], r[2], r[3], r[4])
    if key in seen:
        continue
    seen.add(key); uniq.append(r)
rows = uniq

primary = [r for r in rows if (r[3].startswith("bare") and r[5] == "fwd")
           or r[3] in ("mathcalS", "label-ref", "stem-cite")]
secondary = [r for r in rows if r not in primary]

def fmt(r):
    self, fn, ln, kind, cited, d, text = r
    stem = fn.replace("moving_throat_pde_stage", "").replace(".md", "")
    snip = (text[:120] + "…") if len(text) > 120 else text
    snip = snip.replace("|", "\\|")
    return f"| {self:03d} | {stem} | {ln} | {kind} | {cited} | {d} | {snip} |"

# group primary by band then file
from collections import defaultdict
byband = defaultdict(list)
for r in primary:
    byband[band(r[0])].append(r)

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("# Numbering Broad-Sweep — candidate INVENTORY (read-only, machine-generated)\n\n")
    fh.write("Generated by `redteam/broad_sweep_scan.py`. Scope = the ~236 stage notes only.\n")
    fh.write("Every row is a CANDIDATE; stale-vs-canonical is content work for classifier agents.\n")
    fh.write("Ground truth = filename/`\\label{stage:NNN}`; NEVER offset-sweep. H1 (line 1) excluded (Class B done).\n\n")
    fh.write(f"- PRIMARY candidates (forward bare refs + all special forms): **{len(primary)}**\n")
    fh.write(f"- SECONDARY (backward bare refs; mostly genuine, optional later): **{len(secondary)}**\n")
    fh.write(f"- distinct notes with ≥1 PRIMARY candidate: **{len(set(r[1] for r in primary))}**\n\n")
    # per-band primary counts
    fh.write("## PRIMARY counts by band (classifier-agent clusters)\n\n")
    fh.write("| band | candidates | notes |\n| --- | ---: | ---: |\n")
    for b in sorted(byband):
        rs = byband[b]
        fh.write(f"| {b} | {len(rs)} | {len(set(r[1] for r in rs))} |\n")
    fh.write("\n")
    # kind histogram
    kinds = defaultdict(int)
    for r in primary:
        kinds[r[3]] += 1
    fh.write("## PRIMARY by token kind\n\n")
    for k in sorted(kinds):
        fh.write(f"- `{k}`: {kinds[k]}\n")
    fh.write("\n---\n\n")
    for b in sorted(byband):
        fh.write(f"## PRIMARY band {b}\n\n")
        fh.write("| self | stem | line | kind | cited | dir | context |\n")
        fh.write("| ---: | --- | ---: | --- | --- | --- | --- |\n")
        for r in sorted(byband[b], key=lambda r: (r[0], r[2])):
            fh.write(fmt(r) + "\n")
        fh.write("\n")
    # secondary collapsed (counts per file only)
    fh.write("---\n\n## SECONDARY (backward bare refs) — collapsed per note (optional later pass)\n\n")
    fh.write("| self | stem | backward-ref count |\n| ---: | --- | ---: |\n")
    sec_by_file = defaultdict(int)
    sec_self = {}
    for r in secondary:
        sec_by_file[r[1]] += 1; sec_self[r[1]] = r[0]
    for fn in sorted(sec_by_file, key=lambda f: sec_self[f]):
        stem = fn.replace("moving_throat_pde_stage", "").replace(".md", "")
        fh.write(f"| {sec_self[fn]:03d} | {stem} | {sec_by_file[fn]} |\n")

print(f"PRIMARY={len(primary)}  SECONDARY={len(secondary)}  "
      f"notes_with_primary={len(set(r[1] for r in primary))}")
for b in sorted(byband):
    print(f"  band {b}: {len(byband[b])} candidates / {len(set(r[1] for r in byband[b]))} notes")
print(f"written -> {os.path.relpath(OUT)}")
