#!/usr/bin/env python3
"""Small symbolic checks for the independent S11c-c physics-spec review."""

import sympy as sp


def section(title):
    print(f"\n=== {title} ===")


# 1. First shape derivative of the upper-half-space Neumann-to-Dirichlet map.
# Let the exterior be z > d*f(x), K=omega/c, q(k)^2=K^2-k^2, and use
# outgoing modes exp(i*q*z).  Prescribe the outward conormal datum g.
section("CURVED N-TO-D KERNEL HAS TWO MOMENTA / TWO q FACTORS")
k, kp, K, qk, qkp = sp.symbols("k kp K q_k q_kp", nonzero=True)
boundary_rhs_raw = qkp**2 - (k - kp) * kp
boundary_rhs = sp.expand(boundary_rhs_raw.subs(qkp**2, K**2 - kp**2))
# phi0(kp,0)=g(kp)/(i*qkp).  At first shape order,
# d_z phi1(k,0)=(K^2-k*kp) f(k-kp) phi0(kp,0), while evaluating
# phi on z=d*f adds f*g.  The displayed coefficient multiplies f(k-kp)g(kp).
ntod_shape_coeff = sp.simplify(1 + boundary_rhs / ((sp.I * qk) * (sp.I * qkp)))
print("boundary_rhs_raw =", boundary_rhs_raw)
print("using q_kp^2 = K^2-kp^2 ->", boundary_rhs)
print("NtoD_shape_coefficient(k,kp) =", ntod_shape_coeff)
print("depends_on_q_k =", ntod_shape_coeff.has(qk))
print("depends_on_q_kp =", ntod_shape_coeff.has(qkp))

# A constant vertical translation has k=kp and must cancel from the DtN map.
constant_shift = sp.simplify(
    ntod_shape_coeff.subs({kp: k, qkp: qk}).subs(qk**2, K**2 - k**2)
)
print("constant_height_shift_coefficient =", constant_shift)

# One leg can be propagating while the other is evanescent.
mixed = sp.simplify(
    ntod_shape_coeff.subs({K: 5, k: 3, kp: 6, qk: 4, qkp: sp.I * sp.sqrt(11)})
)
print("mixed_example_K5_k3_PROP_kp6_EVAN =", mixed)


# 2. Opposite graph slopes do not mean opposite oriented-normal tilt.  With
# h_s=s*W/2 and n_s=s*(-grad(h_s),1), the tangential correction is face-even.
section("GRAPH-SLOPE PARITY VERSUS ORIENTED-NORMAL PARITY")
gradW = sp.symbols("gradW")
graph_slope_plus = gradW / 2
graph_slope_minus = -gradW / 2
normal_plus = sp.Matrix([-gradW / 2, 1])
normal_minus = sp.Matrix([-gradW / 2, -1])
print("graph_slopes_plus_minus =", (graph_slope_plus, graph_slope_minus))
print("oriented_normals_plus_minus =", (normal_plus, normal_minus))
print("face_even_part_of_normal =", sp.simplify((normal_plus + normal_minus) / 2))
print("face_odd_part_of_normal =", sp.simplify((normal_plus - normal_minus) / 2))


# 3. Extracting a slab off-diagonal block before bulk elimination can miss a
# block generated by the eliminated pressure response.
section("BULK ELIMINATION AND OFF-DIAGONAL EXTRACTION DO NOT COMMUTE")
x, y, p, alpha = sp.symbols("x y p alpha")
open_residual = sp.Matrix([x + p, y])
open_jacobian = open_residual.jacobian([x, y])
open_xy_block = open_jacobian[0, 1]
substitute_into_open_block = open_xy_block.subs(p, alpha * y)
closed_residual = open_residual.subs(p, alpha * y)
closed_jacobian = closed_residual.jacobian([x, y])
closed_xy_block = closed_jacobian[0, 1]
print("open_residual =", open_residual)
print("open_slab_jacobian_treating_p_independent =", open_jacobian)
print("open_x_from_y_block =", open_xy_block)
print("substitute_p_eq_alpha_y_into_open_block =", substitute_into_open_block)
print("closed_residual =", closed_residual)
print("closed_slab_jacobian =", closed_jacobian)
print("extract_block_after_elimination =", closed_xy_block)
print("noncommutation_residual =", sp.simplify(closed_xy_block - substitute_into_open_block))


# 4. The B0c elimination becomes an operator inverse for a curved DtN, and the
# theta mass row contains Lambda_A/Lambda_V but not the reciprocal traction
# coefficient Lambda_X.
section("FACE CLOSURE: OPERATOR INVERSE AND THETA-ROW CHANNELS")
Z, LA, LV, LX, rhom, V, mu, J, pressure, mass = sp.symbols(
    "Z Lambda_A Lambda_V Lambda_X rho_m V mu J p mass"
)
face_solution = sp.solve(
    [
        sp.Eq(pressure, Z * (V + J / rhom)),
        sp.Eq(J, LA * (mu - pressure / rhom) + LV * V),
    ],
    [pressure, J],
    dict=True,
)[0]
closure_residual = J - LA * (mu - pressure / rhom) - LV * V
theta_open = mass + J - closure_residual
print("scalar_flat_face_pressure_solution =", sp.factor(face_solution[pressure]))
print("curved_operator_left_factor = I + (Lambda_A/rho_m**2)*Z")
print("theta_row_after_evolution_minus_closure =", sp.expand(theta_open))
print("theta_row_depends_on_Lambda_X =", theta_open.has(LX))


# 5. For a nonlocal/mode-mixing impedance, entrywise real and imaginary parts
# do not define dissipation and reactance.  The boundary-power pairing uses the
# Hermitian part with the appropriate surface measure.
section("NONLOCAL DISSIPATION REQUIRES THE HERMITIAN OPERATOR PART")
Z_real_skew = sp.Matrix([[0, 1], [-1, 0]])
Z_imag_hermitian = sp.Matrix([[0, sp.I], [-sp.I, 0]])
vec = sp.Matrix([1, -sp.I])
print("real_skew_entrywise_real =", Z_real_skew.applyfunc(sp.re))
print("real_skew_Hermitian_part =", sp.simplify((Z_real_skew + Z_real_skew.adjoint()) / 2))
print("imag_Hermitian_entrywise_real =", Z_imag_hermitian.applyfunc(sp.re))
print(
    "imag_Hermitian_Hermitian_part =",
    sp.simplify((Z_imag_hermitian + Z_imag_hermitian.adjoint()) / 2),
)
print("power_pairing_for_vec =", sp.simplify((vec.adjoint() * Z_imag_hermitian * vec)[0]))


# 6. The prescribed global width scaling z=W(x)*y is not asymptotically the
# identity.  Its first-order transformed Laplacian has coefficients linear in
# y, and even an exactly outgoing plane wave has a secular first variation.
section("GLOBAL WIDTH-SCALING FLATTENING IS SECULAR AT INFINITY")
xx, yy, W0, d, q = sp.symbols("x y W0 d q", nonzero=True)
f = sp.Function("f")(xx)
u = sp.Function("u")(xx, yy)


def Dx(expr):
    return sp.diff(expr, xx) - yy * d * sp.diff(f, xx) * sp.diff(expr, yy)


def Dz(expr):
    return (1 / W0) * (1 - d * f) * sp.diff(expr, yy)


laplacian = sp.series(Dx(Dx(u)) + Dz(Dz(u)), d, 0, 2).removeO().expand()
laplacian_correction = sp.simplify(laplacian.coeff(d))
mapped_outgoing = sp.exp(sp.I * q * W0 * (1 + d * f) * yy)
mapped_outgoing_first_variation = sp.simplify(
    sp.diff(mapped_outgoing, d).subs(d, 0) / sp.exp(sp.I * q * W0 * yy)
)
print("transformed_laplacian_to_O(d) =", laplacian)
print("O(d)_coefficient =", laplacian_correction)
print("coefficient_of_y_in_O(d)_operator =", sp.expand(laplacian_correction).coeff(yy))
print("relative_first_variation_of_outgoing_wave =", mapped_outgoing_first_variation)


# 7. The rest-frame operator correction q*v/omega is not a uniform control on
# the selected normal root or impedance near q=0.
section("CONVECTIVE REST-FRAME EXPANSION IS NONUNIFORM AT GRAZING")
omega, v, c, rho, q0, kt = sp.symbols(
    "omega v c rho q0 k", positive=True, finite=True
)
qq = sp.symbols("q")
dispersion = (omega - v * qq) ** 2 - c**2 * (kt**2 + qq**2)
dq_dv_at_rest = sp.simplify(
    -sp.diff(dispersion, v) / sp.diff(dispersion, qq)
).subs({v: 0, qq: q0})
root_relative_correction = sp.simplify(v * dq_dv_at_rest / q0)
operator_smallness = q0 * v / omega
print("convective_dispersion =", sp.expand(dispersion))
print("dq_dv_at_v0 =", dq_dv_at_rest)
print("relative_normal_root_correction =", root_relative_correction)
print("stated_operator_smallness =", operator_smallness)
print("limit_q_to_0_stated_smallness =", sp.limit(operator_smallness, q0, 0, dir="+"))
print(
    "limit_q_to_0_abs_root_correction =",
    sp.limit(sp.Abs(root_relative_correction), q0, 0, dir="+"),
)
sound_cone_factorization = sp.factor(dispersion.subs(omega, c * kt))
print("exact_dispersion_at_rest_sound_cone =", sound_cone_factorization)
print(
    "sound_cone_normal_roots =",
    sp.solve(sp.Eq(sound_cone_factorization, 0), qq),
)
