#!/usr/bin/env python3
from __future__ import annotations

import os
import sys
import sympy as sp

sys.path.insert(0, os.path.dirname(__file__))
from fivepn_stage315_317_common import *

"""
Stage 317 — exact reduced actual-branch orbit tester.

This stage turns the Stage-315/316 continuum monomial drift laws into a ready-to-use
actual-branch tester.  The tester acts on the reduced drift vector

    d = (dln chi0, dln deltaU, dln ZhatW, dln epsilonW, dln epsilon_eta)

and returns either
    (Sigma_tr, Sigma_nt, Sigma_eta)
or, equivalently,
    (Theta_1, Xi_1, R_1).

The key result is that this reduced tester has exact rank 3 and a 2-dimensional
zero-defect kernel, so the actual coherent orbit-lock branch is an exact 2-plane in
this reduced continuum state space.
"""

if __name__ == "__main__":
    banner("STAGE 317 — REDUCED ACTUAL-BRANCH ORBIT TESTER")

    chi0_star, deltaU_star, epsW_star, eps_star, epsEta_star = sp.symbols(
        "chi0_star deltaU_star epsilonW_star epsilon_star epsilon_eta_star",
        positive=True,
        real=True,
    )
    dln_chi0, dln_deltaU, dln_ZhatW, dln_epsW, dln_epsEta = sp.symbols(
        "dlnchi0 dlndeltaU dlnZhatW dlnepsilonW dlnepsilon_eta", real=True
    )

    dvec = sp.Matrix([dln_chi0, dln_deltaU, dln_ZhatW, dln_epsW, dln_epsEta])
    sigmas = continuum_monomial_drifts(
        dln_chi0, dln_deltaU, dln_ZhatW, dln_epsW, dln_epsEta,
        chi0_star, deltaU_star, epsW_star, eps_star,
    )
    defects = defect_map_from_sigmas(
        sigmas["Sigma_tr"], sigmas["Sigma_nt"], sigmas["Sigma_eta"],
        chi0_star, deltaU_star, epsEta_star,
    )

    subbanner("I. Exact reduced drift-to-monomial projector")
    Mred = sp.Matrix([
        [sp.diff(sigmas["Sigma_tr"], x) for x in dvec],
        [sp.diff(sigmas["Sigma_nt"], x) for x in dvec],
        [sp.diff(sigmas["Sigma_eta"], x) for x in dvec],
    ])
    print("M_red =")
    sp.pprint(Mred)
    print("rank(M_red) =", Mred.rank())

    subbanner("II. Exact reduced drift-to-defect projector")
    Pred = sp.Matrix([
        [sp.diff(defects["Theta1"], x) for x in dvec],
        [sp.diff(defects["Xi1"], x) for x in dvec],
        [sp.diff(defects["R1"], x) for x in dvec],
    ])
    print("P_red =")
    sp.pprint(Pred)
    print("rank(P_red) =", Pred.rank())

    subbanner("III. Exact 2-plane of reduced zero-defect drifts")
    codrifts = required_codrifts_for_orbit_lock(
        dln_chi0, dln_epsW,
        chi0_star, deltaU_star, epsW_star, eps_star,
    )
    vchi = reduced_zero_defect_basis(chi0_star, deltaU_star, epsW_star, eps_star)["v_chi"]
    vepsW = reduced_zero_defect_basis(chi0_star, deltaU_star, epsW_star, eps_star)["v_epsW"]

    print("Required codrifts for exact orbit lock:")
    print("dln deltaU =")
    sp.pprint(codrifts["dln_deltaU"])
    print("dln ZhatW =")
    sp.pprint(codrifts["dln_ZhatW"])
    print("dln epsilon_eta =")
    sp.pprint(codrifts["dln_epsEta"])

    print("Zero-defect basis vector generated by dln chi0 = 1:")
    sp.pprint(vchi)
    print("Zero-defect basis vector generated by dln epsilonW = 1:")
    sp.pprint(vepsW)

    expect_zero("M_red v_chi", sp.simplify(Mred * vchi))
    expect_zero("M_red v_epsW", sp.simplify(Mred * vepsW))
    expect_zero("P_red v_chi", sp.simplify(Pred * vchi))
    expect_zero("P_red v_epsW", sp.simplify(Pred * vepsW))

    subbanner("IV. Exact codimension and orbit-lock interpretation")
    print("The reduced actual-branch tester has codimension 3 inside the 5-drift space,")
    print("so its exact zero-defect kernel is 2-dimensional.")
    print()
    print("A convenient basis is")
    print("  v_chi  = (1, -(1+deltaU_*)/(1+chi0_*), -F_* (1+deltaU_*)/(1+chi0_*), 0, 0),")
    print("  v_epsW = (0, 0, -E_*, 1, 0).")
    print()
    print("So the actual coherent branch is on the exact similarity orbit iff its reduced")
    print("drift vector lies in span{v_chi, v_epsW}.")
