#!/usr/bin/env python3
from __future__ import annotations

import sympy as sp
from fivepn_stage199_201_common import banner, subbanner, expect_zero

"""
Stage 216 — support-blind mixed-sector first-order packet-null condition.

What this script does
---------------------
1. Builds the same explicit positive isotropic finite-throat prototype used in the
   recent 5PN weak-axisymmetric work.
2. Computes the *true* first-order packet-tangency slopes
      u2^(1), u4^(1), Xi_load = P1/P0
   rather than the surrogate (K1, H_even) gates.
3. Restricts to the support-blind mixed sector with free input drifts
      (alpha_K, alpha_GW, alpha_R),
   and dependent co-drifts
      alpha_deltaU, alpha_OW
   generated by the normalized orbit relations.
4. Builds the exact 3x3 packet-null matrix in those three free directions.
5. Proves that a nontrivial support-blind first-order endgame-null corridor exists
   only on a codimension-1 affine relation between the orbit constants (E_*,F_*).

Interpretation
--------------
This is the first exact test of the tempting support-blind mixed corridor against
 the *actual* first-order Packet-A/B endgame, not just the lower-bound surrogate
 even gates. The result is sharply narrower than before: the corridor exists only
 on one affine line in the (E_*,F_*) plane.
"""


def differential(expr: sp.Expr, prims: list[sp.Symbol], dlogs: list[sp.Symbol]) -> sp.Expr:
    return sp.simplify(sum(sp.diff(expr, p) * p * dp for p, dp in zip(prims, dlogs)))


if __name__ == "__main__":
    banner("STAGE 216 — SUPPORT-BLIND MIXED-SECTOR FIRST-ORDER PACKET-NULL CONDITION")

    # ------------------------------------------------------------------
    # I. Explicit positive isotropic prototype branch
    # ------------------------------------------------------------------
    subbanner("I. Explicit positive isotropic prototype branch")

    pi = sp.pi
    I_cross = sp.simplify(sp.Rational(8, 3) / pi)

    lambda_B = sp.Integer(1)
    varpi = sp.Integer(2)
    GU = sp.Integer(1)
    GW = sp.Integer(1)
    R = sp.Rational(1, 2)
    OU = sp.Rational(3, 2)
    OW = sp.Integer(2)
    M = sp.Integer(1)

    C = sp.simplify(lambda_B * I_cross)
    Delta = sp.simplify(OU**2 * OW**2 - R**2)
    P = sp.simplify(OU**2 * GW + R * GU)
    Q = sp.simplify(GU**2 * OW**2 + 2 * GU * GW * R + GW**2 * OU**2)
    H = sp.simplify(GU**2 + GW**2)
    S2 = sp.simplify(OU**2 + OW**2)

    B0 = sp.simplify(C**2 / varpi**2)
    B2 = sp.simplify(C**2 / varpi**4)
    B4 = sp.simplify(C**2 / varpi**6)
    Z0 = sp.simplify(Q / Delta)
    Z2 = sp.simplify((Q * S2 - H * Delta) / Delta**2)
    Z4 = sp.simplify((Q * (S2**2 - Delta) - S2 * H * Delta) / Delta**3)
    N0 = sp.simplify(P**2 / Delta**2)

    # Fix K on the exact isotropic one-pole surface.
    K = sp.simplify((3 * (M + B2 + Z2) ** 2 + (B0 + Z0) * (B4 + Z4)) / (B4 + Z4))
    D0 = sp.simplify(K - B0 - Z0)
    D2 = sp.simplify(-(M + B2 + Z2))
    D4 = sp.simplify(-(B4 + Z4))
    u2 = sp.simplify(-D2 / D0)

    print("u2(explicit isotropic prototype) =")
    sp.pprint(u2)
    print("u2 - 1/9 =")
    sp.pprint(sp.simplify(u2 - sp.Rational(1, 9)))

    # ------------------------------------------------------------------
    # II. Support-blind mixed family generated by the normalized orbit relations
    # ------------------------------------------------------------------
    subbanner("II. Support-blind mixed family")

    alpha_K, alpha_GW, alpha_R = sp.symbols("alpha_K alpha_GW alpha_R", real=True)
    E_star, F_star = sp.symbols("E_star F_star", real=True)

    chi0 = sp.simplify(R * GU / (OU**2 * GW))
    deltaU = sp.Integer(1)

    alpha_deltaU = sp.simplify(-(1 + deltaU) / (1 + chi0) * (alpha_R - alpha_GW))
    alpha_M = alpha_K
    alpha_OW = sp.simplify((alpha_GW + E_star * alpha_R - sp.Rational(1, 2) * F_star * alpha_deltaU) / (E_star + 2))

    print("chi0 =")
    sp.pprint(chi0)
    print("alpha_deltaU =")
    sp.pprint(alpha_deltaU)
    print("alpha_OW =")
    sp.pprint(alpha_OW)

    prims = [sp.Symbol("GW"), sp.Symbol("R"), sp.Symbol("OW")]
    dlogs = [alpha_GW, alpha_R, alpha_OW]

    GWs, Rs, OWs = prims
    Delta_expr = OU**2 * OWs**2 - Rs**2
    P_expr = OU**2 * GWs + Rs * GU
    Q_expr = GU**2 * OWs**2 + 2 * GU * GWs * Rs + GWs**2 * OU**2
    H_expr = GU**2 + GWs**2
    S2_expr = OU**2 + OWs**2

    subs = {GWs: GW, Rs: R, OWs: OW}
    Delta01 = sp.simplify(differential(Delta_expr, prims, dlogs).subs(subs))
    P01 = sp.simplify(differential(P_expr, prims, dlogs).subs(subs))
    Q01 = sp.simplify(differential(Q_expr, prims, dlogs).subs(subs))
    H01 = sp.simplify(differential(H_expr, prims, dlogs).subs(subs))
    S201 = sp.simplify(differential(S2_expr, prims, dlogs).subs(subs))

    Z2_num = sp.simplify(Q * S2 - H * Delta)
    Z4_num = sp.simplify(Q * (S2**2 - Delta) - S2 * H * Delta)

    Z01 = sp.simplify((Q01 * Delta - Q * Delta01) / Delta**2)
    Z21 = sp.simplify(((Q01 * S2 + Q * S201 - H01 * Delta - H * Delta01) * Delta - 2 * Z2_num * Delta01) / Delta**3)
    Z41 = sp.simplify(((Q01 * (S2**2 - Delta) + Q * (2 * S2 * S201 - Delta01) - (S201 * H * Delta + S2 * H01 * Delta + S2 * H * Delta01)) * Delta - 3 * Z4_num * Delta01) / Delta**4)
    N01 = sp.simplify(2 * N0 * (P01 / P - Delta01 / Delta))

    D01 = sp.simplify(K * alpha_K - Z01)
    D21 = sp.simplify(-(M * alpha_M + Z21))
    D41 = sp.simplify(-Z41)

    u2_1 = sp.simplify((-D0 * D21 + D2 * D01) / D0**2)
    u4_1 = sp.simplify((D0 * (-D0 * D41 + 2 * D2 * D21 - D4 * D01) + 2 * D01 * (D0 * D4 - D2**2)) / D0**3)
    Xi_load = sp.simplify(N01 / N0 - D01 / D0)

    print("u2^(1) =")
    sp.pprint(u2_1)
    print("u4^(1) =")
    sp.pprint(u4_1)
    print("Xi_load =")
    sp.pprint(Xi_load)

    # ------------------------------------------------------------------
    # III. Exact packet-null matrix and determinant line
    # ------------------------------------------------------------------
    subbanner("III. Exact packet-null matrix")

    free = [alpha_K, alpha_GW, alpha_R]
    M_packet = sp.Matrix(
        [
            [sp.simplify(sp.diff(u2_1, v)) for v in free],
            [sp.simplify(sp.diff(u4_1, v)) for v in free],
            [sp.simplify(sp.diff(Xi_load, v)) for v in free],
        ]
    )

    print("M_packet =")
    sp.pprint(M_packet)

    det_packet = sp.factor(sp.together(sp.simplify(M_packet.det())))
    print("det(M_packet) =")
    sp.pprint(det_packet)

    # Pull out the affine E/F numerator of the determinant.
    det_num = sp.factor(sp.together(det_packet).as_numer_denom()[0])
    affine = sp.factor(det_num / (-pi**2 * (8575 + 12717 * pi**2) ** 2))
    print("Affine orbit-line factor =")
    sp.pprint(affine)

    coeff_E = sp.simplify(sp.diff(affine, E_star))
    coeff_F = sp.simplify(sp.diff(affine, F_star))
    coeff_0 = sp.simplify(affine.subs({E_star: 0, F_star: 0}))

    F_crit = sp.simplify(-(coeff_E * E_star + coeff_0) / coeff_F)

    print("coeff_E =")
    sp.pprint(coeff_E)
    print("coeff_F =")
    sp.pprint(coeff_F)
    print("coeff_0 =")
    sp.pprint(coeff_0)
    print("F_crit(E_star) =")
    sp.pprint(F_crit)

    expect_zero("packet-null determinant on the affine line", sp.simplify(M_packet.det().subs(F_star, F_crit)))

    # Concrete rank checks.
    sample_constructive = {E_star: sp.Rational(1, 4), F_star: sp.Rational(5, 6)}
    sample_illustrative = {E_star: sp.Integer(1), F_star: sp.Integer(1)}
    M_constructive = sp.Matrix([[sp.simplify(x.subs(sample_constructive)) for x in row] for row in M_packet.tolist()])
    M_illustrative = sp.Matrix([[sp.simplify(x.subs(sample_illustrative)) for x in row] for row in M_packet.tolist()])

    print("rank at (E_*,F_*) = (1/4, 5/6) =", M_constructive.rank())
    print("rank at (E_*,F_*) = (1, 1) =", M_illustrative.rank())

    banner("STAGE 216 LEDGER")
    print("1. On the explicit isotropic overlap prototype, the baseline u2 is not 1/9, so")
    print("   the true first-order packet-tangency conditions must be enforced directly via")
    print("      u2^(1) = 0,  u4^(1) = 0,  Xi_load = 0,")
    print("   rather than by the canonical surrogate pair (K1, H_even).")
    print("2. In the support-blind mixed sector, those three true conditions form an exact 3x3")
    print("   homogeneous linear system in (alpha_K, alpha_GW, alpha_R).")
    print("3. A nontrivial support-blind first-order packet-null corridor exists only when")
    print("      F_* = F_crit(E_*),")
    print("   i.e. on one affine codimension-1 line in the (E_*,F_*) plane.")
    print("4. At the representative constructive point (E_*,F_*) = (1/4, 5/6), the matrix has")
    print("   rank 3, so the support-blind packet-null system is trivial there.")
