#!/bin/bash
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3; A=$SP/directives/S11c_a_SHARED_PHYSICS.md
claim () { printf '## %s\n\n```\n$ %s\n' "$1" "$2"; eval "$2"; printf '```\n\n'; }
cat <<'HDR'
# _measurements — S11c_a_repair2_directive.md

Regenerated by `scratchpad/gen_s11c_a_repair2_meas.sh` (each command RUN, not transcribed).
Relays Grok's re-review findings; each claim about the spec / decisions carries its command (rule 2).
HDR
claim "baseline — repair-1 reviewed spec is at HEAD 9365c39c" \
  "git -C /var/projects/toy_physics log --oneline -1 9365c39c -- $A"
claim "FIX A — §3a ρ_4D^α identity has NO branch superscript (the N4 hole)" \
  "sed -n '313,316p' $A"
claim "FIX A — §2c branches every Q_bg (incl. ρ_4D,bg⁰) L:Q(x) M:Q(χ)" \
  "sed -n '232,240p' $A"
claim "FIX B — §3b t_s^α carries + t_hold,s⁰, and feeds δ_v𝒲" \
  "sed -n '351,352p;363p' $A"
claim "FIX B — N15 assigns the variable-coefficient operator + background invariants to S11c-b" \
  "grep -n 'N15' $SP/directives/S11c_decisions.md | head -3"
claim "FIX C — §5a T-h corruption is the T-g substitution Σ_E(x(X,t))→Σ_E(X,t) (no-op on Eulerian T-h)" \
  "sed -n '470,472p' $A"
