#!/bin/bash
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3
A=$SP/directives/S11c_c1_SHARED_PHYSICS.md
D=$SP/directives/S11c_c1_sympy_build_directive.md
DES=$SP/directives/export_ledger_bind_closure_design.md
B=$SP/scripts/S11b_exports.py
CA=$SP/scripts/S11c_a_exports.py
CB=$SP/scripts/S11c_b_exports.py
FOLD=$SP/scripts/ledger_fold.py
SCAN=$SP/directives/_measurements/c1_migration_import_keys_scan.py
claim () { printf '## %s\n\n```\n$ %s\n' "$1" "$2"; eval "$2"; printf '```\n\n'; }
present () { for k in $2; do n=$(grep -cE "^    '$k':     \{" "$1"); printf '%-46s %s\n' "$k" "$([ "$n" -ge 1 ] && echo PRESENT || echo MISSING)"; done; }
export -f present
cat <<'HDR'
# _measurements — S11c_c1_sympy_build_directive.md

Regenerated by `_measurements/gen_s11c_c1_sympy_build_meas.sh` (each command RUN, not transcribed).
The build directive wraps the committed S11c-c1 spec (§1/§7 amended by the export-architecture migration to
the fold / own-rows-delta topology) and the two-leg-gated bind-closure design. It adds no physics — it pins the
fold import, the EXACT `IMPORT_KEYS` manifest (reconciled from both review legs), the 6-input digest, F9, and
the §D3 guard. Every binding and the manifest carry their command.
HDR
claim "authority — the S11c-c1 spec history (first committed db5cbf88; then the migration amendment)" \
  "git -C /var/projects/toy_physics log --oneline -- $A | head -4"
claim "design authority — the bind-closure design is committed (c04e071f; §D3 refined fd8c89d0); F10 superseded (4274b403)" \
  "git -C /var/projects/toy_physics log --oneline -- $DES | head -3; git -C /var/projects/toy_physics log --oneline --grep='F10 SUPERSEDED' | head -1"
claim "the fold module ledger_fold.py exists and is committed (verified 1be64084); it is a 6th BUILD_INPUT_DIGESTS input" \
  "git -C /var/projects/toy_physics log --oneline -- $FOLD | head -3; grep -nE 'def load_model|def check_consumer|def assert_lookups_equal_manifest|def assert_delta_is_minimal' $FOLD"
claim "the frozen base S11c_b_exports.py is PLAIN GIT (annex.largefiles=nothing) and the SINGLE atomic base carrying the whole model" \
  "git -C /var/projects/toy_physics check-attr annex.largefiles -- $CB; git -C /var/projects/toy_physics cat-file -t HEAD:$CB"
claim "IMPORT_KEYS manifest — RUN the scan against the real frozen base: 44 roots, 193-row closure, 0 ambiguity; the 5 removed over-declarations are NOT in the closure (mu_R stays reachable via mu_theta_operator)" \
  "cd $SP/scripts && python3 ../directives/_measurements/c1_migration_import_keys_scan.py"
claim "the directive declares those 44 roots explicitly (the IMPORT_KEYS block) and names the NOT-bound exclusions" \
  "grep -nE 'IMPORT_KEYS. explicitly and exactly|44 roots . 193-row|NOT bound by c1 — reserved for c2' $D"
claim "μ_θ operand — S11CB_MU_THETA_OPERATOR binds row mu_theta_operator (S11c_b_exports.py); NOT re-derived, carried opaque" \
  "grep -nE \"^    'mu_theta_operator':     \\{\" $CB | head -1"
claim "the nine S11c-a T-substrate rows are all PRESENT in the frozen base" \
  "present $CB 'face_normal conormal_deriv face_measure_shape_deriv face_velocity relative_flux kinematic_balance traction face_shift closure_shape_deriv'"
claim "the S11b flat B0b/B0c §5c/§5d regression rows + omega + epsilon_shape + the two rho_br reps are all PRESENT" \
  "present $CB 'z_impermeable z_by_regime z_by_parity added_mass grazing_behaviour face_response face_response_coeffs permeable_dissipative_by_regime_and_parity degenerate_loci_equations omega epsilon_shape rho_br rho_br_bg_rho4_constant q_out v_bulk_normal_0 c_s0 rho_m W_0 e_W'"
claim "NOT bound (over-declarations both legs removed) are present-but-unused — mu_R is reachable via mu_theta_operator, the modulus/4D-density/contrast rows are structurally absent from c1" \
  "cd $SP/scripts && python3 -c \"import ledger_fold as lf; f,_=lf.load_model('S11c_b_exports.py'); print({k:(k in f) for k in ['mu_R','mu_R_bg','m1_profile','rho_4D_bg_rho4_constant','rho_4D_bg_rhobr_constant','e_W_bg']})\""
claim "F9c face_response split — the bare rows are S11b's (c1's §5c/§5d regression operands); c1 writes its own as s11c_c1_ prefixed (the prefix is not yet in the frozen base)" \
  "cd $SP/scripts && python3 -c \"import ledger_fold as lf; f,_=lf.load_model('S11c_b_exports.py'); print('face_response step=',f['face_response']['step']); print('s11c_c1_face_response present=', 's11c_c1_face_response' in f)\""
claim "own-rows DELTA topology (design §D2): directive says delta only, NOT accumulated; supersedes F10" \
  "grep -nE 'own-rows delta only|NOT the accumulated model|supersedes .F10.' $D | head -4"
claim "the §D3 guard the directive requires before publication (check_consumer + smoke-test + minimal-mode)" \
  "grep -nE 'check_consumer\\(fold|assert_lookups_equal_manifest|assert_delta_is_minimal' $D"
claim "the 6-input BUILD_INPUT_DIGESTS (full ancestry + ledger_fold.py); ancestry sha-chain verified: S11c_b embeds S11c_a's sha embeds S11b's sha" \
  "grep -nE 'six inputs the c1 spec §7 requires|ledger_fold.py.. .All six are read' $D | head -2"
claim "F9 totality is TOTAL over imported row shapes (:171-186) — applied whole, not restated" \
  "sed -n '171,176p' $SP/directives/S11_export_chain_decisions_v2.md"
claim "T7 comparator contract (:53-60) — rejects a native boolean as a residual operand" \
  "sed -n '53,60p' $SP/directives/S11_C17_C18_spec_repair_decisions_v2.md"
claim "class vocabulary (S9_REWRITE_PLAN:41) and D3 in-run round-trip (:217) — retained ALONGSIDE the new guard" \
  "sed -n '41p;217p' $SP/S9_REWRITE_PLAN.md"
claim "the comparator reads the two stdout .out tag streams, NOT the exports LEDGER (so the delta trim cannot blind it)" \
  "sed -n '4,10p' $SP/scripts/S11c_b_cross_engine_comparator.py"
claim "the migration was two-leg reviewed (Codex + Grok); the leg prompt is saved beside the directives" \
  "ls -la $SP/directives/_legs/c1_migration_review.md | awk '{print \$5\"  \"\$9}'"
