#!/bin/bash
# Regenerates directives/_measurements/S11c_a_SHARED_PHYSICS.md (post-fold).
# CLAUDE.md rule 2: every claim the S11c-a spec makes about the imported S11b
# setup carries the command that produced it. Run from repo root.
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3
S=$SP/directives/S11b_SHARED_PHYSICS.md

claim () { printf '## %s\n\n```\n$ %s\n' "$1" "$2"; eval "$2"; printf '```\n\n'; }

cat <<'HDR'
# _measurements — S11c_a_SHARED_PHYSICS.md  (post-fold, 2026-08-23)

Regenerated by `scratchpad/gen_s11c_a_spec_measurements.sh` (each command RUN, not transcribed).
The S11c-a spec supplies the S11b setup (§1) and takes its shape-derivative; every §1 claim about that
imported setup carries the command that produced it here (CLAUDE.md rule 2). The physics S11c-a *tests*
(the S11CA_* shape-derivatives) is computed by the engines, not asserted here.

HDR

claim "§1 — fields: u (3 comp), theta EULERIAN, e_W=dW/W0, rho_br0=rho_4D0 W0, twist modulus mu_R" \
  "sed -n '72,88p' $S"
claim "§1 — flat faces: n̂_± = ±ŵ, ζ_±=±δW/2, V_±=(∂_tζ_±)(±1)  (F1: orientation the tilt must keep)" \
  "sed -n '368p' $S"
claim "§1 — relative flux J_± along the outward normal; the outward sign appears ONCE" \
  "sed -n '194,201p' $S"
claim "§1 — face closure + affinity 𝒜=mu_s-dp/rho_m, mu_s=mu_theta/rho_br0 (SUPPLIED)" \
  "sed -n '212,227p' $S"
claim "§1 — the material virtual constraint (delta_v Sigma_mat=0); Sigma_E/Sigma_mat defs" \
  "sed -n '318,335p' $S"
claim "§1 — delta_v Sigma_E = 0 is forbidden as the constraint" \
  "sed -n '341p' $S"
claim "§1 — the PHYSICAL mass balance is a SEPARATE evolution equation (not delta_v Sigma_mat)" \
  "sed -n '356,357p' $S"
claim "§1 — the exact physical mass balance d_t Sigma + div(Sigma v) = -(J+ + J-)  (T-h linearises this)" \
  "sed -n '640p' $S"
claim "§1 — flat virtual work: delta_v x_±, traction t_±, delta_v W_bulk (T-d shape-differentiates it)" \
  "sed -n '370,372p' $S"
claim "§1 — B0a projection identity + the DYNAMIC-window term enumeration (T-f)" \
  "sed -n '595,606p' $S"
claim "§1 — interfacial mass balance v_bulk = V + J/rho_m (kinematics; T-c' tilts it)" \
  "sed -n '620,623p' $S"
claim "§1 — the energy U and its kappa_W |grad(dW)|^2 gradient term (2d admissibility)" \
  "sed -n '258,262p' $S"
claim "§1 — the drain v_dr = v_bulk_normal_0 (bulk NORMAL drain; scope limit only)" \
  "sed -n '99,111p' $S"
claim "§1 — rho_br0 freeze maps to the imported constant rho_br" \
  "sed -n '75p' $S"
claim "§1/N5 — the plane-wave k-real table is for the UNIFORM problem (⛔ not applied to the background)" \
  "sed -n '85,87p' $S"
claim "§6 — exit semantics: a physics finding EXITS 0; nonzero only on operational failure; no VERDICT" \
  "sed -n '543,546p' $S"
claim "T-c — B6 forbids getting the transverse coupling by a divergence-free argument" \
  "sed -n '819,823p' $S"
claim "2a — mu_R varies: grad(mu_R)!=0 is the principal mixing source; FORM now, MAGNITUDE needs interior R1" \
  "sed -n '1179p' $SP/V3_STEP_PLAN.md"
claim "N14 — live imported CONSTANT keys W_0/e_W/rho_br/mu_R/v_0 (F9 false-equal hazard if reused)" \
  "grep -nE \"'(W_0|e_W|rho_br|mu_R|v_0)': *\\{\" $SP/scripts/S11b_exports.py | head"
claim "N1/N2 — S11c-a is sub-step a of the staged family; its row lists W0(x), mu_R(x), rho_4D0" \
  "sed -n '41p' $SP/directives/S11c_decisions.md"
