#!/bin/bash
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3; A=$SP/directives/S11c_a_SHARED_PHYSICS.md
claim () { printf '## %s\n\n```\n$ %s\n' "$1" "$2"; eval "$2"; printf '```\n\n'; }
cat <<'HDR'
# _measurements — S11c_a_sympy_build_directive.md

Regenerated by `scratchpad/gen_s11c_a_sympy_build_meas.sh` (each command RUN, not transcribed).
The build directive wraps the closed S11c-a spec (2926c71c) + chain wiring; each claim carries its command.
HDR
claim "authority — the S11c-a spec is closed at HEAD 2926c71c" \
  "git -C /var/projects/toy_physics log --oneline -1 2926c71c -- $A"
claim "the μ_θ pin — §3a branched μ_s^α vs §4 T-i un-superscripted glyph" \
  "sed -n '317p' $A; echo '--- §4 T-i ---'; sed -n '441p' $A"
claim "§4 primary tasks T-0…T-i are the exports (controls are §5)" \
  "grep -nE '^- \*\*T-[0a-i]' $A | head -20"
claim "§5 controls (5a/5b/5c) are ablation evidence, not exports" \
  "grep -nE '^### 5[abc] ' $A"
claim "§7 name reservations + inherited F9 collision check" \
  "sed -n '528,538p' $A"
claim "inherited chain: import LEDGER from S11b_exports.py (the prior chain record)" \
  "grep -nE \"^'\" $SP/scripts/S11b_exports.py | head -1; echo '(S11b_exports.py present, row count):'; grep -cE \"^    '\" $SP/scripts/S11b_exports.py"
claim "FIX rho_m — bulk density is an S11b KNOB row (bind, do NOT re-originate)" \
  "sed -n '7292,7299p' $SP/scripts/S11b_exports.py"
claim "F9 totality is TOTAL over imported row shapes (:171-186)" \
  "sed -n '171,176p' $SP/directives/S11_export_chain_decisions_v2.md"
claim "F9c prefix generalization left open (:203); s11_/s11b_ taken" \
  "sed -n '203p' $SP/directives/S11_export_chain_decisions_v2.md"
claim "T7 comparator contract (:53-60)" \
  "sed -n '53,60p' $SP/directives/S11_C17_C18_spec_repair_decisions_v2.md"
claim "class vocabulary (S9_REWRITE_PLAN:41)" \
  "sed -n '41p' $SP/S9_REWRITE_PLAN.md"
claim "D3 in-run round-trip (S9_REWRITE_PLAN:217)" \
  "sed -n '217p' $SP/S9_REWRITE_PLAN.md"
