#!/bin/bash
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3; S=$SP/directives/S11b_SHARED_PHYSICS.md
claim () { printf '## %s\n\n```\n$ %s\n' "$1" "$2"; eval "$2"; printf '```\n\n'; }
cat <<'HDR'
# _measurements — S11c_a_recompose_directive.md

Regenerated by `scratchpad/gen_s11c_a_recompose_meas.sh` (each command RUN, not transcribed).
Every punch-list claim about the S11b spec carries the command that produced it (CLAUDE.md rule 2).
HDR
claim "base — the defective folded spec is at HEAD 82d14079" \
  "git -C /var/projects/toy_physics log --oneline -1 82d14079 -- $SP/directives/S11c_a_SHARED_PHYSICS.md"
claim "item 4 — zeta_c is an independent face combination (centre shift)" \
  "sed -n '89p' $S"
claim "item 5 — physical mass balance defines v=∂_t u (B1)" \
  "sed -n '640,646p' $S"
claim "item 6 — J_± is flux per unit FACE area (leaving the slab along the outward normal)" \
  "sed -n '208,211p' $S"
claim "item 7 — mu_theta held-fixed qualifier: (dU/dtheta)|_{u,e_W, all other fields fixed}" \
  "sed -n '224p' $S"
claim "item 11 — a control re-enters at the ENERGY or a supplied law, never at a result" \
  "sed -n '499,504p' $S"
claim "KEEP/9 — B6 forbids getting the transverse coupling by a divergence-free argument" \
  "sed -n '821,823p' $S"
claim "discipline — no VERDICT; a physics finding EXITS 0; nonzero only on operational failure" \
  "sed -n '543,546p' $S"
claim "discipline — exit-0 rule (:518)" \
  "sed -n '516,519p' $S"
claim "meta-rule — the structural rule: results reached by computation" \
  "sed -n '499p' $S"
claim "μ_R — grad(mu_R) mixing; FORM now, MAGNITUDE needs interior R1" \
  "sed -n '1179p' $SP/V3_STEP_PLAN.md"
