#!/bin/bash
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3
D=$SP/directives/export_ledger_bind_closure_design.md
CB=$SP/scripts/S11c_b_exports.py
CMP=$SP/scripts/S11c_b_cross_engine_comparator.py
GEN=$SP/directives/chain_accumulate_or_generate_decision.md
L=$SP/directives/_legs
claim () { printf '## %s\n\n```\n$ %s\n' "$1" "$2"; eval "$2"; printf '```\n\n'; }
cat <<'HDR'
# _measurements — export_ledger_bind_closure_design.md

Regenerated by `_measurements/gen_export_ledger_bind_closure_design_meas.sh` (each command RUN). The design's
load-bearing measured facts + the two-leg gate (deliberation + design-review, both convergent). Rule 2.
HDR
claim "the file the redesign shrinks: size + row count (58.75 MiB, 2441 rows)" \
  "wc -c $CB | awk '{printf \"%d bytes = %.2f MiB\n\",\$1,\$1/1048576}'; printf 'rows: '; grep -cE \"^    '[A-Za-z0-9_]+':     \\{\" $CB"
claim "term_origins = ~29.5% of the file (the largest unbound class)" \
  "awk '/^    '\"'\"'[A-Za-z0-9_]+'\"'\"':[ ]+\\{/{if(k!=\"\"){t+=b;if(k~/term_origin/)o+=b}match(\$0,/'\"'\"'[A-Za-z0-9_]+'\"'\"'/);k=substr(\$0,RSTART+1,RLENGTH-2);b=0}{b+=length(\$0)+1}END{t+=b;if(k~/term_origin/)o+=b;printf \"term_origins %.2f MiB of %.2f MiB = %.1f%%\n\",o/1048576,t/1048576,100*o/t}' $CB"
claim "comparator reads the .out tag streams, NOT the exports LEDGER (so narrowing/generate cannot blind it)" \
  "sed -n '9,10p' $CMP"
claim "D3 round-trip does NOT catch under-export: _restore builds Symbol() from srepr with no LEDGER lookup" \
  "sed -n '17,18p' $CB"
claim "the 2026-08-11 GENERATE decision (D2 implements it; F10 re-asserted the superseded accumulate)" \
  "sed -n '8,9p' $GEN"
claim "the face_response collision (D3/D2 fix): base has S11b flat face_response; c1's curved one is a different object ⇒ F9c write-key" \
  "grep -nE \"^    'face_response':     \\{\" $CB; grep -nE \"'step': 'S11b'\" $CB | head -1 | sed 's/^/(a nearby S11b step row) /'"
claim "coupling_kernel is present in the base (dropped from the minimum; c2 re-extracts, does not bind it — spec §0)" \
  "grep -nE \"^    'coupling_kernel':     \\{\" $CB; sed -n '34,35p' $SP/directives/S11c_c1_SHARED_PHYSICS.md"
claim "the GATE: deliberation (2 engines) + design-review (2 engines), both convergent, outputs saved beside the prompts" \
  "ls -la $L/export_ledger_minimum_*.out $L/export_ledger_bind_closure_design_review_*.out | awk '{print \$5\"  \"\$9}'"
claim "both design-review legs said NOT-SOUND-as-is and v2 folded their convergent must-fixes (v2 note in the design head)" \
  "grep -nE 'v2 folds the two decision legs|v2 changed \\(folded' $D"
