#!/bin/bash
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3; S=$SP/directives/S11b_SHARED_PHYSICS.md
claim () { printf '## %s\n\n```\n$ %s\n' "$1" "$2"; eval "$2"; printf '```\n\n'; }
cat <<'HDR'
# _measurements — S11c_a_SHARED_PHYSICS.md  (Codex-authored, rule-15 replacement)

Regenerated by `scratchpad/gen_s11c_a_spec_meas_v2.sh` (each command RUN, not transcribed).
Codex's spec INLINES the S11b setup as supplied equations rather than citing line-by-line; this twin
carries the S11b sources those inlined equations must be faithful to (CLAUDE.md rule 2), so §1 fidelity is
auditable. The physics S11c-a *tests* (the S11CA_* shape-derivatives) is computed by the engines.
HDR
claim "§1a fields / face DOFs: theta Eulerian, e_W, rho_br0; zeta_c independent centre shift" \
  "sed -n '72,89p' $S"
claim "§1a flat faces + relative flux (outward sign once, per face area)" \
  "sed -n '194,201p' $S; echo '---'; sed -n '368p' $S"
claim "§1c energy U + kinetic (with kappa_W gradient term)" \
  "sed -n '258,262p' $S"
claim "§1c mu_theta held-fixed qualifier (binding)" \
  "sed -n '224p' $S"
claim "§1c closure/affinity/traction/kinematic balance" \
  "sed -n '212,227p' $S; echo '---'; sed -n '370,372p' $S; echo '---'; sed -n '620,623p' $S"
claim "§1c physical mass balance defines v=∂_t u; the evolution law" \
  "sed -n '640,646p' $S"
claim "§1c virtual constraint material (delta_v Sigma_mat=0); delta_v x = delta_v u; delta_v Sigma_E forbidden" \
  "sed -n '318,341p' $S"
claim "§1b bulk acoustics + projection (dynamic window)" \
  "sed -n '162,171p' $S; echo '---'; sed -n '595,606p' $S"
claim "§6 no VERDICT; physics finding exits 0; structural rule (compute, not type)" \
  "sed -n '499,504p' $S; echo '---'; sed -n '543,546p' $S"
claim "T-c/B6 — transverse coupling NOT by a divergence-free argument" \
  "sed -n '819,823p' $S"
claim "the drain v_bulk_normal_0 (scope limit only)" \
  "sed -n '99,111p' $S"
claim "μ_R varies: grad(mu_R) mixing; FORM now, MAGNITUDE needs interior R1 (the only external cite)" \
  "sed -n '1179p' $SP/V3_STEP_PLAN.md"
claim "N14 live constant keys W_0/e_W/rho_br/mu_R/v_0 (F9 hazard if a varying object reuses them)" \
  "grep -nE \"'(W_0|e_W|rho_br|mu_R|v_0)': *\\{\" $SP/scripts/S11b_exports.py | head"
