#!/bin/bash
# Regenerates research/pde_ledger_v3/directives/_measurements/S11c_decisions.md
# CLAUDE.md rule 2: every artifact-claim in the S11c decision list carries the
# command that produced it. Run from repo root: bash <this> > <twin>.
# Regenerated after the one-leg fold (2026-08-23): new physics anchors from the
# two legs' verified findings are included.
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3

claim () {  # $1 = heading, $2 = command
  printf '## %s\n\n```\n$ %s\n' "$1" "$2"
  eval "$2"
  printf '```\n\n'
}

cat <<'HDR'
# _measurements — S11c_decisions.md

Regenerated by `scratchpad/gen_s11c_decisions_measurements.sh` (each command is RUN, not transcribed).
Every artifact-claim in `directives/S11c_decisions.md` carries the command that produced it here
(CLAUDE.md rule 2). Inherited-obligation pointers (F1–F9, the three script clauses, S11b `G`-items by ID)
are references to named rules, looked up by ID, not measured here. The physics anchors below are the ones
the two review legs (Codex + Grok) relied on and the orchestrator verified (rule 13) before folding.

HDR

# --- structure / chain ---
claim "N1 — S11c-a imports the S11b LEDGER (S11b_exports.py, 1958 rows)" \
  "sed -n '22p' $SP/steps/S11b_interface_coupling_law.md"
claim "N1 — S11b_exports.py exists on the export chain" \
  "ls $SP/scripts/ | grep -E '_exports.py\$'"
claim "N1 amended (2026-09-04) — from S11c-c1 onward the chain uses the generate-over-a-frozen-base topology; the design is two-leg-gated + committed (c04e071f/fd8c89d0), F10 superseded (4274b403)" \
  "grep -nE 'from S11c-c1 onward the chain uses the generate-over-a-frozen-base|imports the fold|own-rows delta' $SP/directives/S11c_decisions.md | head -3; git -C /var/projects/toy_physics log --oneline -- $SP/directives/export_ledger_bind_closure_design.md | head -2"
claim "N1 amended — the fold+guard module ledger_fold.py exists (a shared executable input added to a delta-writer's BUILD_INPUT_DIGESTS)" \
  "grep -nE 'def load_model|def check_consumer' $SP/scripts/ledger_fold.py"
claim "N1/N2 — S11b's single spec took eleven directive revisions (why the family is split finer)" \
  "sed -n '106p' $SP/steps/S11b_HANDOFF.md"
claim "Header — the unified S11b list ratified only C's SCOPE, not the requirement package" \
  "sed -n '12,15p' $SP/steps/S11b_HANDOFF.md"

# --- N3 tilted faces / full shape-derivative ---
claim "N3 — relative flux is measured along the face's outward normal (tilt changes it)" \
  "sed -n '193,196p' $SP/directives/S11b_SHARED_PHYSICS.md"

# --- N4 Eulerian vs material is a representation S11b already fixed ---
claim "N4 — theta is EULERIAN, not material" \
  "sed -n '73p' $SP/directives/S11b_SHARED_PHYSICS.md"
claim "N4 — the binding constraint is MATERIAL (delta_v Sigma_mat = 0); Sigma_E/Sigma_mat definitions" \
  "sed -n '320,332p' $SP/directives/S11b_SHARED_PHYSICS.md"
claim "N4 — delta_v Sigma_E = 0 is explicitly forbidden as the constraint" \
  "sed -n '340,341p' $SP/directives/S11b_SHARED_PHYSICS.md"

# --- N5/N15 order-count & broken translation invariance ---
claim "N15 — in-plane translation invariance: u enters only through gradients (broken by W0(x))" \
  "sed -n '283p' $SP/directives/S11b_SHARED_PHYSICS.md"

# --- N6 uniform coupling identically zero ---
claim "N6 — the uniform transverse coupling is identically zero (control is vacuous)" \
  "sed -n '75p' $SP/steps/S11b_interface_coupling_law.md"

# --- N7 normalization undetermined / form-vs-magnitude ---
claim "N7 — a vanishing/nonzero coupling's normalization must be fixed before a value/dimension" \
  "sed -n '824,825p' $SP/directives/S11b_SHARED_PHYSICS.md"
claim "N7 — the conversion FORM is available now with a generic profile; MAGNITUDE needs the interior (R1); coupling ∝ k·a, ∇μ_R mixes" \
  "sed -n '1179p' $SP/V3_STEP_PLAN.md"

# --- N8 blind WL / T7 ---
claim "N8 — the blind Wolfram engine is the only blindness control" \
  "sed -n '16,18p' $SP/directives/S9_export_chain_rebuild_directive.md"
claim "N8 — the T7 comparator contract is S11b G8(a)" \
  "grep -n 'G8\b\|frozen .T7.\|reject a native boolean' $SP/directives/S11b_unified_decisions.md"

# --- N10 scope boundary (G14) ---
claim "N10 — variable-coefficient coupling/leakage/unconditional-confinement is S11c (G14)" \
  "sed -n '134p' $SP/directives/S11b_unified_decisions.md"
claim "N10 — the DC/harmonic/sideband radiation audit is the nonlinear program, NOT S11c (G14)" \
  "sed -n '135p' $SP/directives/S11b_unified_decisions.md"

# --- N11 carry-ins ---
claim "N11a — the background-flow smallness domain: large k c_s0/|w| is NECESSARY, not sufficient" \
  "sed -n '159,161p' $SP/steps/S11b_interface_coupling_law.md"

# --- N14 the F9 naming hazard, made concrete on the live exports ---
claim "N14 — live keys: v_0 (S10 PREMISE) and v_bulk_normal_0 are DISTINCT (F9 false-equal hazard)" \
  "sed -n '13806,13816p' $SP/scripts/S11b_exports.py"
claim "N14 — G3: never reuse the key v_0 (F9 object comparison would prove a false equal)" \
  "grep -n 'never reuse the key\|false.equal\|EQUAL and silently merge' $SP/directives/S11b_unified_decisions.md"
