#!/bin/bash
set -uo pipefail
cd "${CLAUDE_PROJECT_DIR:-/var/projects/toy_physics}"
SP=research/pde_ledger_v3
A=$SP/directives/S11c_c1_SHARED_PHYSICS.md
D=$SP/directives/S11c_c1_sympy_build_directive.md
B=$SP/scripts/S11b_exports.py
CA=$SP/scripts/S11c_a_exports.py
CB=$SP/scripts/S11c_b_exports.py
CB_CMP=$SP/scripts/S11c_b_cross_engine_comparator.py
claim () { printf '## %s\n\n```\n$ %s\n' "$1" "$2"; eval "$2"; printf '```\n\n'; }
present () { for k in $2; do n=$(grep -cE "^    '$k':     \{" "$1"); printf '%-46s %s\n' "$k" "$([ "$n" -ge 1 ] && echo PRESENT || echo MISSING)"; done; }
export -f present
cat <<'HDR'
# _measurements — S11c_c1_sympy_build_directive.md

Regenerated by `_measurements/gen_s11c_c1_sympy_build_meas.sh` (each command RUN, not transcribed).
The build directive wraps the committed S11c-c1 spec (db5cbf88) + chain wiring; each binding carries its
command. The directive adds no physics — it pins bindings, the 5-input digest, F9, and the three deviations.
HDR
claim "authority — the S11c-c1 spec is committed db5cbf88 and UNCHANGED since (only that commit touches it)" \
  "git -C /var/projects/toy_physics log --oneline -- $A"
claim "the audit-script product name the directive writes" \
  "grep -nE 'S11c_c1_bulk_closure_sympy_audit\.py' $D | head -3"
claim "μ_θ operand — S11CB_MU_THETA_OPERATOR binds to row mu_theta_operator (S11c_b_exports.py); display begins (mu_theta,…)" \
  "grep -nE \"^    'mu_theta_operator':     \\{\" $CB; sed -n '5629p' $CB | cut -c1-90"
claim "S11c-a T-substrate rows (T-a..T-i) the curved face objects are built on — all PRESENT in S11c_a_exports.py" \
  "present $CA 'face_normal conormal_deriv face_measure_shape_deriv face_velocity relative_flux kinematic_balance traction face_shift closure_shape_deriv'"
claim "S11b flat B0b/B0c reference rows (the §5c/§5d regression operand B) + branch object + drain — all PRESENT in S11b_exports.py" \
  "present $B 'z_impermeable z_by_regime added_mass grazing_behaviour face_response face_response_coeffs permeable_dissipative_by_regime_and_parity q_out v_bulk_normal_0'"
claim "the IMMEDIATE PARENT S11c_b_exports.py (the incoming chain record c1 carries forward, N1) carries EVERY bound row merged flat" \
  "present $CB 'face_normal conormal_deriv face_measure_shape_deriv face_velocity relative_flux kinematic_balance traction face_shift closure_shape_deriv z_impermeable z_by_regime added_mass grazing_behaviour face_response permeable_dissipative_by_regime_and_parity q_out v_bulk_normal_0 mu_theta_operator c_s0 rho_m mu_R W_0 rho_br e_W'"
claim "chain growth (row-opening count per exports file): S11b < S11c_a < S11c_b" \
  "for f in $B $CA $CB; do printf '%s: ' \"\$f\"; grep -cE \"^    '[a-z0-9_]+':     \\{\" \"\$f\"; done"
claim "FIX rho_m — bulk density is an S11b KNOB row (bind, do NOT re-originate)" \
  "sed -n '7292,7299p' $B"
claim "§4 primary objects are the exports; §5 controls (5a-5e) are ablation evidence, not exports" \
  "grep -nE '^### 5[a-e] |^## 4 ' $A"
claim "the c1 spec §7 pins the FULL ancestry in BUILD_INPUT_DIGESTS (S11b + S11c_a + S11c_b exports) — the 5-input deviation from the earlier 3-pin sub-steps" \
  "grep -nE 'BUILD_INPUT_DIGESTS' $A"
claim "F9c taken prefixes s11_/s11b_/s11c_a_/s11c_b_ — fresh c1 prefix is s11c_c1_ (directive pins it)" \
  "grep -nE 's11c_c1_' $D | head -2"
claim "c1 HAS a §6 locus protocol (unlike S11c-a/S11c-b) — DEGENERATE_LOCI, finite-dim only; typed CAS booleans feed T7" \
  "grep -nE 'locus protocol|S11CC1_DEGENERATE_LOCI|STATUS_TOKEN' $A | head -6"
claim "N11a / §2b rest-frame limit — the convective operator is NOT constructed; grazing = strict v_bulk_normal_0=0; never aliased to v_0" \
  "grep -nE 'convective operator|v_bulk_normal_0=0|never aliased to .v_0' $A | head -6"
claim "F9 totality is TOTAL over imported row shapes (:171-186)" \
  "sed -n '171,176p' $SP/directives/S11_export_chain_decisions_v2.md"
claim "T7 comparator contract (:53-60) — rejects a native boolean as a residual operand" \
  "sed -n '53,60p' $SP/directives/S11_C17_C18_spec_repair_decisions_v2.md"
claim "class vocabulary (S9_REWRITE_PLAN:41) and D3 in-run round-trip (:217)" \
  "sed -n '41p;217p' $SP/S9_REWRITE_PLAN.md"
claim "EXPORT-TRIM motivation: the comparator reads the two stdout .out tag streams, NOT the exports LEDGER (so narrowing the export cannot blind it)" \
  "sed -n '4,10p' $CB_CMP"
claim "EXPORT-TRIM authority: spec §3b names EXACTLY what c2 consumes (the export keep-set)" \
  "sed -n '347,348p' $A"
claim "EXPORT-TRIM applied in the directive: narrow KEEP set + emit-only DROP set, cited to F10 (not a self-authorized D1 refinement)" \
  "grep -nE 'candidate EXPORT population is ONLY|NOT exported — emit-to-stdout ONLY|This is .F10. applied|does not amend .D1./§7 on its own authority' $D"
claim "EXPORT-TRIM authority F10: the model-level-register rule added to the export-chain decisions (resolves the model-vs-step split the file flagged open for a third step's evidence)" \
  "grep -nE '^## ⭐ F10|MADE in .F10. below' $SP/directives/S11_export_chain_decisions_v2.md"
claim "EXPORT-TRIM §7 reconciled: c1 spec §7 now names the CONSUMED objects + cites F10 (was 'the emitted PY_S11CC1_* objects')" \
  "grep -nE 'chain-\*\*CONSUMED\*\*|per .F10.' $A"
claim "EXPORT-TRIM gate: the change is gated by the S11c-c1 directive review (Grok CLEAR + Codex must-fix → this lawful recording); leg outputs saved beside the prompt" \
  "ls -la $SP/directives/_legs/S11c_c1_sympy_build_directive_review*.* | awk '{print \$5\"  \"\$9}'"
claim "EXPORT-TRIM finding (committed evidence at d1fe1bf0): the pre-trim full-primary export was 145.5 MB, two DISSIPATION-AUDIT rows 84.7 MB (56%) of it — step-level evidence, now emit-only under F10" \
  "git -C /var/projects/toy_physics show d1fe1bf0:research/pde_ledger_v3/directives/_measurements/S11c_c1_sympy_build_directive.md 2>/dev/null | grep -E 'pre-trim S11c_c1_exports.py size:|permeable_port_hermitian|permeable_dissipation_vs_omega_tau' | head -3; printf 'current export (rebuilt against F10, model-level register only): '; wc -c $SP/scripts/S11c_c1_exports.py 2>/dev/null | awk '{printf \"%.1f MB\n\",\$1/1048576}' || echo '(not yet rebuilt)'"
