# synthetic line 1
# synthetic line 2
# synthetic line 3
# synthetic line 4
# synthetic line 5
# synthetic line 6
# synthetic line 7
# synthetic line 8
# synthetic line 9
# synthetic line 10
# synthetic line 11
# synthetic line 12
# synthetic line 13
# synthetic line 14
# synthetic line 15
# synthetic line 16
# synthetic line 17
# synthetic line 18
# synthetic line 19
# synthetic line 20
# synthetic line 21
# synthetic line 22
# synthetic line 23
# synthetic line 24
# synthetic line 25
# synthetic line 26
# synthetic line 27
# synthetic line 28
# synthetic line 29
# synthetic line 30
# synthetic line 31
# synthetic line 32
# synthetic line 33
# synthetic line 34
# synthetic line 35
# synthetic line 36
# synthetic line 37
# synthetic line 38
# synthetic line 39
# synthetic line 40
# synthetic line 41
# synthetic line 42
# synthetic line 43
# synthetic line 44
# synthetic line 45
# synthetic line 46
# synthetic line 47
# synthetic line 48
# synthetic line 49
# synthetic line 50
# synthetic line 51
# synthetic line 52
# synthetic line 53
# synthetic line 54
# synthetic line 55
# synthetic line 56
# synthetic line 57
# synthetic line 58
# synthetic line 59
stiffness_dim = Dim(1, -1, -2, sp.Rational(1, 2))  # mass
# synthetic line 61
# synthetic line 62
# synthetic line 63
# synthetic line 64
# synthetic line 65
# synthetic line 66
# synthetic line 67
# synthetic line 68
# synthetic line 69
# synthetic line 70
# synthetic line 71
# synthetic line 72
# synthetic line 73
# synthetic line 74
# synthetic line 75
# synthetic line 76
# synthetic line 77
# synthetic line 78
# synthetic stiffness coefficient B
# synthetic line 80
dims['B'] = stiffness_dim  # mass
# synthetic line 82
# synthetic line 83
# synthetic line 84
# synthetic line 85
# synthetic line 86
# synthetic line 87
# synthetic line 88
# ACTIVE_MUTATION selects corrupt state
cE = B_dim * corrupt_factor  # mass
